---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: 使用SnapCenter 支援功能來備份SQL Server系統和使用者資料庫時、您必須選擇資源類型、例如資料庫、SQL Server執行個體和可用度群組（AG）。利用Snapshot複製技術來建立資源所在磁碟區的線上唯讀複本。 
---
= 支援的備份類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要使用SnapCenter 支援功能來備份SQL Server系統和使用者資料庫、您必須選擇資源類型、例如資料庫、SQL Server執行個體和可用度群組（AG）。利用Snapshot複製技術來建立資源所在磁碟區的線上唯讀複本。

您可以選取純複本選項、指定SQL Server不會刪減交易記錄。當您同時使用其他備份應用程式來管理SQL Server時、應該使用此選項。保持交易記錄不變、可讓任何備份應用程式還原系統資料庫。純複製備份與排程備份順序無關、不會影響資料庫的備份與還原程序。

|===
| 備份類型 | 說明 | 備份類型的純複本選項 


 a| 
完整備份與記錄備份
 a| 
備份系統資料庫、並將交易記錄予以捨去。

SQL Server會移除已提交至資料庫的項目、以縮短交易記錄。

完整備份完成後、此選項會建立交易記錄、以擷取交易資訊。一般而言、您應該選擇此選項。不過、如果您的備份時間短、您可以選擇不使用完整備份來執行交易記錄備份。

您無法為主要和msdb系統資料庫建立記錄備份。不過、您可以為模型系統資料庫建立記錄備份。
 a| 
備份系統資料庫檔案和交易記錄、而不需刪減記錄。

純複本備份無法做為差異基礎或差異備份、而且不會影響差異基礎。還原純複本完整備份與還原任何其他完整備份相同。



 a| 
完整資料庫備份
 a| 
備份系統資料庫檔案。

您可以為主要、模型及msdbb系統資料庫建立完整的資料庫備份。
 a| 
備份系統資料庫檔案。



 a| 
交易記錄備份
 a| 
備份被截掉的交易記錄、僅複製自最近的交易記錄備份以來所提交的交易。

如果您排程頻繁的交易記錄備份與完整資料庫備份、則可以選擇精細的還原點。
 a| 
備份交易記錄而不將其刪減。

此備份類型不會影響定期記錄備份的順序。純複本記錄備份對於執行線上還原作業非常有用。

|===