---
permalink: protect-scsql/concept_prerequisites_for_using_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: credential 
summary: 開始使用適用於SQL Server的外掛程式之前SnapCenter 、管理員必須先安裝及設定SnapCenter VMware Server、並執行必要的工作。 
---
= 使用SnapCenter Microsoft SQL Server的功能的先決條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
開始使用適用於SQL Server的外掛程式之前SnapCenter 、管理員必須先安裝及設定SnapCenter VMware Server、並執行必要的工作。

* 安裝及設定SnapCenter 靜態伺服器。
* 登入SnapCenter 到
* 新增或指派儲存系統連線、並建立認證資料、以設定SnapCenter 整個靜態環境。
+

NOTE: 不支援在不同叢集上使用相同名稱的多個SVM。SnapCenter每個SnapCenter 支援的SVM都必須有唯一的名稱。

* 新增主機、安裝外掛程式、探索（重新整理）資源、以及設定外掛程式。
* 執行Invoke-SmConfigureResources、將現有的Microsoft SQL Server資料庫從本機磁碟移至NetApp LUN、反之亦然。
+
如需執行Cmdlet的資訊、請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205["《軟件指令程式參考指南》SnapCenter"]

* 如果您使用SnapCenter VMware vCenter Server來保護位於VMware RDM LUN或VMDK上的SQL資料庫、則必須部署SnapCenter VMware vSphere的「支援VMware vSphere的支援中心」外掛程式、並以SnapCenter 「支援中心」登錄外掛程式。VMware vSphere的《VMware vCenter外掛程式》文件有更多資訊。SnapCenter
+
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["VMware vSphere文件的VMware外掛程式SnapCenter"]

* 使用SnapCenter 適用於Microsoft Windows的《支援Microsoft Windows的功能不實的外掛程式」來執行主機端儲存資源配置。
* 如果SnapVault 您想要備份複寫、請設定SnapMirror和不相關性。


如需詳細資訊、請參閱SnapCenter 《關於安裝的資訊：

針對VMware vSphere 4.1.1版的《VMware vSphere 4.1.1版》（《VMware vSphere 4.1.1版》）文件提供有關保護虛擬化資料庫和檔案系統的資訊。SnapCenter SnapCenter對於NetApp Data Broker 1.0和1.0.1、NetApp Data Broker 4.2.x使用者而言、文件中包含使用以Linux為基礎的NetApp Data Broker虛擬應用裝置（開放式虛擬應用裝置格式）所提供的VMware vSphere版《支援VMware vSphere的VMware外掛程式》來保護虛擬化資料庫和檔案系統的相關資訊。SnapCenter SnapCenter針對VMware vSphere 4.3的《VMware vSphere 4.3的VMware vCenter外掛程式》文件、提供SnapCenter 使用VMware vSphere虛擬應用裝置的Linux版《VMware vSphere的VMware vSphere虛擬應用程式》（開放式虛擬應用裝置格式）來保護虛擬化資料庫和檔案系統的相關資訊。SnapCenter SnapCenter

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["VMware vSphere文件的VMware外掛程式SnapCenter"]
