---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: 使用這個功能、您可以從資源群組或資料庫建立複本。SnapCenter您可以執行隨需複製、也可以排程資源群組或資料庫的循環複製作業。如果您定期複製備份、可以使用複本來開發應用程式、填入資料或恢復資料。 
---
= 執行Clone生命週期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用這個功能、您可以從資源群組或資料庫建立複本。SnapCenter您可以執行隨需複製、也可以排程資源群組或資料庫的循環複製作業。如果您定期複製備份、可以使用複本來開發應用程式、填入資料或恢復資料。

利用此功能、您可以排程在多個伺服器上同時執行多個複製作業。SnapCenter

.開始之前
* 複製到獨立式資料庫執行個體時、請確定掛載點路徑存在、而且是專用磁碟。
* 複製到容錯移轉叢集執行個體（FCI）時、請確定掛載點存在、它是共用磁碟、而且路徑和FCI應屬於同一個SQL資源群組。
* 如果來源資料庫或目標執行個體位於叢集共用Volume（CSV）上、則複製的資料庫將位於該CSV上。



NOTE: 對於虛擬環境（VMDDK / RDM）、請確定掛載點是專用磁碟。

.關於這項工作
* 可使用外掛主機SMCoreServiceHost.exe.Config檔案中的PredefinedWindows指令碼目錄金鑰來定義指令碼路徑。
+
如有需要、您可以變更此路徑並重新啟動SMcore服務。建議您使用預設的安全路徑。

+
金鑰的值可透過API：API /4.7/configsettings從交換器顯示

+
您可以使用Get API來顯示金鑰的值。不支援Set API。

* Clone生命週期精靈頁面上的大部分欄位都是不言自明的。下列資訊說明您可能需要指引的欄位。


.步驟
. 在左導覽窗格中、按一下*資源*、然後從清單中選取適當的外掛程式。
. 在「資源」頁面中、從*檢視*清單中選取*資料庫*或*資源群組*。
. 選取資源群組或資料庫、然後按一下* Clone生命週期*。
. 在「選項」頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
複製工作名稱
 a| 
指定有助於監控及修改複製生命週期工作的複製生命週期工作名稱。



 a| 
Clone伺服器
 a| 
選擇應放置複本的主機。



 a| 
實體複本執行個體
 a| 
選擇要複製資料庫的複製執行個體。此SQL執行個體必須位於指定的複製伺服器中。



 a| 
Clone字尾
 a| 
輸入要附加到複製資料庫的字尾、以識別該資料庫是否為複製。用於建立複製資源群組的每個SQL執行個體都必須具有唯一的資料庫名稱。例如、如果複製資源群組包含來自SQL執行個體「inst1」的來源資料庫「db1」、如果將「db1」複製到「inst1」、則複製資料庫名稱應為「db1_clone」。「`_clone」是必要的使用者定義字尾、因為資料庫會複製到同一個執行個體。如果將「db1'」複製到SQL執行個體「'inst2'」、則複製的資料庫名稱可以保留為「db1'」（後置字元為選用）、因為資料庫會複製到不同的執行個體。



 a| 
在路徑下自動指派掛載點或自動指派磁碟區掛載點
 a| 
選擇是否要在路徑下自動指派掛載點或Volume掛載點。選擇在路徑下自動指派磁碟區掛載點、即可提供特定目錄。將在該目錄中建立掛載點。在選擇此選項之前、您必須確定目錄為空。如果目錄中有資料庫、則在掛載作業之後、資料庫將處於無效狀態。

|===
. 在「位置」頁面中、選取要建立複本的儲存位置。
. 在「指令碼」頁面中、分別輸入應在複製作業之前或之後執行的預先記錄或PostScript路徑和引數。
+
例如、您可以執行指令碼來更新SNMP設陷、自動化警示、傳送記錄等等。

+

NOTE: 預先編寫或後製指令碼路徑不應包含磁碟機或共用區。路徑應相對於指令碼路徑。

+
預設指令碼逾時為60秒。

. 在「排程」頁面中、執行下列其中一項動作：
+
** 如果您要立即執行複製工作、請選取*立即執行*。
** 選擇* Configure schedule*（配置排程*）以決定複製作業應多久執行一次、何時開始複製排程、何時應執行複製作業、何時應到期、以及是否必須在排程到期後刪除複本。


. 在「通知」頁面的*電子郵件喜好設定*下拉式清單中、選取您要傳送電子郵件的案例。
+
您也必須指定寄件者和接收者的電子郵件地址、以及電子郵件的主旨。如果您要附加執行的複製作業報告、請選取*附加作業報告*。

+

NOTE: 對於電子郵件通知、您必須使用GUI或PowerShell命令Set-SmtpServer來指定SMTP伺服器詳細資料。

+
如需EMS、請參閱 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["管理EMS資料收集"]

. 檢閱摘要、然後按一下「*完成*」。


您應該使用「*監控*>*工作*」頁面來監控複製程序。
