---
permalink: protect-scsql/task_import_archived_backups.html 
sidebar: sidebar 
keywords: SnapVault 
summary: 您只能從SnapVault 命令列介面、將使用支援Microsoft SnapManager SQL Server的支援技術歸檔的備份、匯入SnapCenter 到支援的支援區。 
---
= 匯入歸檔備份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您只能從SnapVault 命令列介面、將使用支援Microsoft SnapManager SQL Server的支援技術歸檔的備份、匯入SnapCenter 到支援的支援區。

*您需要的是什麼*

* Microsoft SQL Server的支援功能和Microsoft SQL Server 7.x的支援功能都SnapCenter 必須安裝在同一部主機上。SnapManager
* 若要支援叢集、叢集中的每個節點都必須安裝外掛程式和7.x產品。
* 您必須將主機或叢集新增SnapCenter 至支援資源、並在主機或叢集上探索可供備份的資源。
* 您必須已備份SnapManager 適用於Microsoft SQL Server SnapInfo資料夾的功能。
+
如果匯入作業失敗、您可以從SnapInfo目錄擷取備份中繼資料。



|===


 a| 
*最佳實務做法：*最佳實務做法是設定SnapCenter 適用於Microsoft SQL Server的《支援Microsoft SQL Server的更新檔》（英文）的記錄備份資料夾。

|===
如需SnapCenter 有關安裝與組態工作的資訊、請參閱SnapCenter 《安裝資訊：如需SnapManager 有關Microsoft SQL Server安裝與組態工作的資訊、請參閱SnapManager 《安裝資訊：

將歸檔備份從SnapCenter Microsoft SQL Server的支援庫匯入到支援功能庫之後SnapManager 、您可以從SnapCenter 支援庫執行這些備份的還原與複製作業。同時、您也可以使用SnapManager Microsoft SQL Server的支援功能、繼續執行備份、還原及複製作業。

*步驟*

. 請執行下列步驟、建立類似SnapManager 於以人工SnapCenter 方式在支援的Microsoft SQL Server排程的排程：
+
.. 使用「Get-Smschedule」Cmdlet從SnapManager Microsoft SQL Server的支援資訊中擷取排程資訊。
.. 儲存排程資訊。
+
您可以使用此排程資訊、同時在SnapCenter 功能表中建立原則。

.. 使用SnapManager 「Get-SmSchedule -Hostname <hostname>-PluginCode SMSQL -disableCurrentGenschedule' Cmdlet來停用Microsoft SQL Server排程的支援功能。


. 使用「Invoke-SmupMigration」指令程式匯入歸檔備份。
+
例如、若要移轉獨立式SQL主機：「Invoke-SmBackup移轉-Hostname <hostname>'」、「-PluginCode SMSQL」

+
例如、若要移轉叢集主機：「Invoke-SmBackup移轉-主機名稱<叢集名稱>「-PluginCode SMSQL」


