---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords: migrate resources 
summary: 在您使用SnapCenter 適用於Microsoft Windows的支援功能更新NetApp儲存系統後、您可以使用SnapCenter 「支援功能」圖形化使用者介面（GUI）或PowerShell Cmdlet、將資源移轉至NetApp儲存系統、或從一個NetApp LUN移轉至另一個NetApp LUN。 
---
= 將資源移轉至NetApp儲存系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用SnapCenter 適用於Microsoft Windows的支援功能、配置NetApp儲存系統之後、您可以使用SnapCenter 支援功能、圖形化使用者介面（GUI）或PowerShell Cmdlet、將資源移轉至NetApp儲存系統、或從一個NetApp LUN移轉至另一個NetApp LUN。

.開始之前
* 您必須已將儲存系統新增SnapCenter 至該伺服器。
* 您必須重新整理（探索到）SQL Server資源。


這些精靈頁面上的大部分欄位都是不言自明的。下列資訊說明您可能需要指引的部分欄位。

.步驟
. 在左導覽窗格中、按一下*資源*、然後從清單中選取適當的外掛程式。
. 在「資源」頁面中、從「*檢視*」下拉式清單中選取「*資料庫*」或「*執行個體*」。
. 從清單中選取資料庫或執行個體、然後按一下*移轉*。
. 在「資源」頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
*資料庫名稱*（選用）
 a| 
如果您已選取要移轉的執行個體、則必須從*資料庫*下拉式清單中選取該執行個體的資料庫。



 a| 
*選擇目的地*
 a| 
選取資料和記錄檔的目標位置。

資料和記錄檔會分別移至所選NetApp磁碟機下的「Data（資料）」和「Log（記錄）」資料夾。如果資料夾結構中沒有任何資料夾、則會建立資料夾、並移轉資源。



 a| 
*顯示資料庫檔案詳細資料*（選用）
 a| 
若要移轉單一資料庫的多個檔案、請選取此選項。


NOTE: 當您選取* Instanced*資源時、不會顯示此選項。



 a| 
*選項*
 a| 
選擇*刪除原始位置的移轉資料庫複本*、即可從來源刪除資料庫複本。

選用項目：*在中斷資料庫之前、先執行表格的更新統計資料*。

|===
. 在「Verify（驗證）」頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
*資料庫一致性檢查選項*
 a| 
選取*執行於*可在移轉之前檢查資料庫的完整性。選取*執行時間*以在移轉後檢查資料庫的完整性。



 a| 
* DBCC CHECKDB選項*
 a| 
** 選取*實體_only *選項、將完整性檢查限制在資料庫的實體結構上、並偵測毀損的頁面、Checksum故障、以及影響資料庫的常見硬體故障。
** 選取「* no_INFOMSGS*」選項可隱藏所有資訊訊息。
** 選取「* all_ERRORMSG*」選項以顯示每個物件所報告的所有錯誤。
** 如果您不想檢查非叢集索引、請選取* NOINDEX*選項。
+
SQL Server資料庫使用Microsoft SQL Server資料庫一致性檢查程式（DBCC）來檢查資料庫中物件的邏輯和實體完整性。

+

NOTE: 您可能想要選取此選項以縮短執行時間。

** 選取「 **TABLOCK** 」選項以限制檢查並取得鎖定、而非使用內部資料庫 Snapshot 。


|===
. 檢閱摘要、然後按一下「*完成*」。

