---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: 您可以先為資源或資源群組建立備份原則、再使用SnapCenter 支援功能來備份SQL Server資源、也可以在建立資源群組或備份單一資源時建立備份原則。 
---
= 建立SQL Server資料庫的備份原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以先為資源或資源群組建立備份原則、再使用SnapCenter 支援功能來備份SQL Server資源、也可以在建立資源群組或備份單一資源時建立備份原則。

.開始之前
* 您必須已定義資料保護策略。
* 您必須完成安裝SnapCenter 、新增主機、識別資源及建立儲存系統連線等工作、以準備好保護資料。
* 您必須已設定主機記錄目錄以進行記錄備份。
* 您必須重新整理（探索到）SQL Server資源。
* 如果您要將快照複製到鏡像或資料保險箱、 SnapCenter 管理員必須將來源磁碟區和目的地磁碟區的儲存虛擬機器（ SVM ）指派給您。
+
如需系統管理員如何指派資源給使用者的詳細資訊、請參閱SnapCenter 《關於安裝的資訊：

* 如果您想以預先編寫和後指令碼執行PowerShell指令碼、則應在web.config檔案中將usePowerShellProcessforScripts參數的值設為true。
+
預設值為假。

* 查看 SnapMirror 主動同步的特定先決條件和限制。如需相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror 主動同步的物件限制"]。


.關於這項工作
* 備份原則是一組規則、可控制您管理及保留備份的方式、以及資源或資源群組的備份頻率。此外、您也可以指定複寫和指令碼設定。在原則中指定選項可節省您想要重複使用其他資源群組原則的時間。
+
可使用外掛主機SMCoreServiceHost.exe.Config檔案中的PredefinedWindows指令碼目錄金鑰來定義指令碼路徑。

+
如有需要、您可以變更此路徑並重新啟動SMcore服務。建議您使用預設的安全路徑。

+
金鑰的值可透過API：API /4.7/configsettings從交換器顯示

+
您可以使用Get API來顯示金鑰的值。不支援Set API。

* SnapLock
+
** 如果選取「保留特定天數的備份複本」選項、則 SnapLock 保留期間必須小於或等於所述保留天數。
+
指定 Snapshot 鎖定期間可防止在保留期間到期之前刪除 Snapshot 。  這可能會導致保留的快照數量超過原則中指定的數量。

+
對於 ONTAP 9.12.1 及更低版本、從 SnapLock 資料保險箱快照建立的複本作為還原的一部分、將會繼承 SnapLock 資料保險箱到期時間。儲存管理員應在 SnapLock 到期後手動清理複本。







== 步驟 1 ：建立原則名稱

. 在左導覽窗格中、選取 * 設定 * 。
. 在「設定」頁面中、選取 * 原則 * 。
. 選取 * 新 * 。
. 在「 * 名稱 * 」頁面中，輸入原則名稱和詳細資料。




== 步驟 2 ：設定原則選項

. 在「原則類型」頁面中，執行下列步驟：
+
.. 選擇您的儲存類型。
.. 選取您的原則範圍。
+
[role="tabbed-block"]
====
.完整備份與記錄備份
--
備份資料庫檔案和交易記錄、並截斷交易記錄。

... 選擇*完整備份與記錄備份*。
... 輸入應為每個 Snapshot 備份的資料庫數目上限。
+

NOTE: 如果您想要同時執行多個備份作業、則必須增加此值。



--
.完整備份
--
備份資料庫檔案。

... 選擇*完整備份*。
... 輸入應為每個 Snapshot 備份的資料庫數目上限。
預設值為 100
+

NOTE: 如果您想要同時執行多個備份作業、則必須增加此值。



--
.記錄備份
--
... 備份交易記錄。
... 選擇*記錄備份*。


--
.僅複製備份
--
... 如果您使用其他備份應用程式來備份資源、請選取*僅複製備份*。


保持交易記錄不變、可讓任何備份應用程式還原資料庫。在任何其他情況下、您通常都不應使用「僅複本」選項。


NOTE: Microsoft SQL不支援*僅複製備份*選項、以及*完整備份與記錄備份*選項、用於次要儲存設備。

--
====






== 步驟 3 ：設定可用性群組設定

. 在「可用度群組設定」區段中、執行下列動作：
+
.. 僅在偏好的備份複本上備份。
+
選取此選項、僅在偏好的備份複本上進行備份。偏好的備份複本是由為SQL Server中的AG設定的備份喜好設定所決定。

.. 選取要備份的複本。
+
選擇主要AG複本或次要AG複本進行備份。

.. 選取備份優先順序（最小和最大備份優先順序）
+
指定最小備份優先順序編號、以及決定AG複本進行備份的最大備份優先順序編號。例如、您的最低優先順序為10、最高優先順序為50。在這種情況下、所有優先順序超過10且低於50的AG複本都會納入備份考量。

+
根據預設、最低優先順序為1、最高優先順序為100。



+

NOTE: 在叢集組態中、備份會根據原則中設定的保留設定保留在叢集的每個節點上。如果AG的擁有者節點變更、則會根據保留設定進行備份、並保留先前擁有者節點的備份。AG保留僅適用於節點層級。





== 步驟 4 ：設定 Snapshot 和 Replication 設定

. 在「 Snapshot and Replication 」（快照與複寫）頁面中，執行下列步驟：
+
.. 選取*隨選*、*每小時*、*每日*、*每週*或*每月*、以指定排程類型。
+
您只能為原則選取一種排程類型。

+

NOTE: 您可以在建立資源群組時、指定備份作業的排程（開始日期、結束日期和頻率）。這可讓您建立共用相同原則和備份頻率的資源群組、但可讓您為每個原則指派不同的備份排程。

+

NOTE: 如果您排定在上午2：00、則在夏令時間（Dst）期間不會觸發排程。







== 步驟 5 ：設定直到分鐘的保留設定

. 根據備份類型頁面中選取的備份類型，在「直到分鐘保留設定」區段中，執行下列一或多項動作：


[role="tabbed-block"]
====
.特定份數
--
僅保留特定數量的快照。

. 選取*保留記錄備份適用於最後的<number>天*選項、然後指定保留天數。如果您接近此限制、可能會想要刪除舊版複本。


--
.特定天數
--
將備份複本保留一段特定天數。

. 選取*保留記錄備份適用於上次的完整備份天數*選項、並指定保留記錄備份複本的天數。


--
====


== 步驟 6 ：設定 Snapshot 設定

. 如需完整備份保留設定，請執行下列動作：
+
.. 指定要保留的快照總數
+
... 若要指定要保留的快照數目，請選取 * 要保留的複本 * 。
... 如果快照數量超過指定數量、則會先刪除最舊的複本、然後刪除快照。







IMPORTANT: 根據預設、保留計數的值設為2。如果將保留計數設為 1 、則保留作業可能會失敗、因為第一個快照是 SnapVault 關係的參考快照、直到較新的快照複寫到目標為止。


NOTE: 對於使用率為1018的ONTAP 資源、如使用率為0、9.4或更新版本、ONTAP 而使用率為254的資源、如使用率為0、9.3或更新版本。如果保留設定的值高於基礎ONTAP 版支援的值、則備份將會失敗。

. 保留快照的時間長度
+
.. 如果您想要指定在刪除快照之前保留快照的天數，請選取 * 保留複本 * 。


. 如果您要指定主要快照複本鎖定期間，請選取 * 主要快照複本鎖定期間 * ，然後選取天，月或年。
+
SnapLock 保留期應少於 100 年。

. 如果您要指定次要快照複本鎖定期間，請選取 * 次要快照複本鎖定期間 * ，然後選取天，月或年。
+
若要使此選項生效，您必須執行下列工作：

+
** 選取 * 主要快照複本鎖定期間 * 。
** 選取其中一個或兩個次要複寫選項。
+
此範例將記錄 Snapshot 保留設定為 2 ：

+
.範例
[]
====
Set-SmPolicy -PolicyName 'newpol' -PolicyType 'Backup' -PluginPolicyType 'SSQL' -sqlbackuptype 'FullBackupAndLogBackup' -RetentionSettings @{BackupType='Data';ScheduleType='Hour';RetentionschedulerCount=2}@{BackupType='Log_ScheduleType=Retenthoure2;RetenteType='Type='LogOnClinthouring@'

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_retains_Snapshot_copies_of_the_database["可保留資料庫的Snapshot複本SnapCenter"]



. 選取 Snapshot 標籤
+
根據您選取的 Snapshot 標籤、 ONTAP 會套用符合標籤的次要 Snapshot 保留原則。

+

NOTE: 如果您在建立本機Snapshot複本之後選擇*更新SnapMirror、您可以選擇性地指定次要原則標籤。不過、如果SnapVault 您在建立本機Snapshot複本*之後選擇*更新SUpdate、則應指定次要原則標籤。





== 步驟 7 ：設定次要複寫選項

. 在 [ 選取次要複寫選項 ] 區段中，選取下列其中一個或兩個次要複寫選項：
+

NOTE: 您必須為 * 次快照複本鎖定期間 * 選取次要複寫選項，才能生效。



[role="tabbed-block"]
====
.更新 SnapMirror
--
在建立本機 Snapshot 複本之後更新 SnapMirror 。

. 選取此選項可在另一個磁碟區（SnapMirror）上建立備份集的鏡射複本。
+
應啟用此選項以進行 SnapMirror 主動同步。

+
在次要複寫期間、 SnapLock 到期時間會載入主要 SnapLock 到期時間。按一下「拓撲」頁面中的 * 重新整理 * 按鈕、即可重新整理從 ONTAP 擷取的次要和主要 SnapLock 到期時間。

+
請參閱。 link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在「拓撲」頁面中檢視SQL Server備份與複製"]



--
.更新 SnapVault
--
建立 Snapshot 複本後更新 SnapVault 。

. 選取此選項以執行磁碟對磁碟備份複寫。
+
在次要複寫期間、 SnapLock 到期時間會載入主要 SnapLock 到期時間。按一下「拓撲」頁面中的 * 重新整理 * 按鈕、即可重新整理從 ONTAP 擷取的次要和主要 SnapLock 到期時間。

+
當 SnapLock 僅在「 SnapLock 資料保險箱」的次要 ONTAP 上設定時、按一下「拓撲」頁面中的「 * 重新整理 * 」按鈕、即可重新整理從 ONTAP 擷取的次要裝置上的鎖定期間。

+
如需 SnapLock Vault 的詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["將Snapshot複本提交至保存目的地上的WORM"]

+
請參閱。 link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在「拓撲」頁面中檢視SQL Server備份與複製"]



--
.錯誤重試計數
--
. 輸入在程序停止之前應進行的複寫嘗試次數。


--
====


== 步驟 8 ：設定指令碼設定

. 在「指令碼」頁面中、分別輸入備份作業之前或之後應執行的指令碼或指令碼路徑和引數。
+
例如、您可以執行指令碼來更新SNMP設陷、自動化警示及傳送記錄。

+

NOTE: 預先編寫或後製指令碼路徑不應包含磁碟機或共用區。路徑應相對於指令碼路徑。

+

NOTE: 您必須在 ONTAP 中設定 SnapMirror 保留原則、使次要儲存設備不會達到快照的最大限制。





== 步驟 9 ：設定驗證設定

在「驗證」頁面中、執行下列步驟：

. 在「執行下列備份排程驗證」區段中、選取排程頻率。
. 在Database Consistency Check options（資料庫一致性檢查選項）區段中、執行下列動作：
+
.. 將完整性結構限制為資料庫的實體結構（僅限實體）
+
... 選取*將完整性結構限制為資料庫的實體結構（僅限實體）*、將完整性檢查限制在資料庫的實體結構上、並偵測毀損的頁面、Checksum故障及影響資料庫的常見硬體故障。


.. 隱藏所有資訊訊息（無 INFOMSGS ）
+
... 選擇*抑制所有資訊訊息（no_INFOMSGS）*以隱藏所有資訊訊息。預設為選取。


.. 顯示每個物件所有回報的錯誤訊息（all_ERRORMSGS）
+
... 選取*顯示每個物件所有報告的錯誤訊息（all_ERRORMSGS）*、以顯示每個物件所有報告的錯誤。


.. 請勿檢查非叢集式索引（NOINEX）
+
... 如果不想檢查非叢集索引、請選取*不要檢查非叢集索引（NOINEX）*。SQL Server資料庫使用Microsoft SQL Server資料庫一致性檢查程式（DBCC）來檢查資料庫中物件的邏輯和實體完整性。


.. 限制檢查並取得鎖定、而非使用內部資料庫 Snapshot （ TABLOCK ）
+
... 選取 * 限制檢查並取得鎖定、而非使用內部資料庫 Snapshot 複本（ TABLOCK ） * 來限制檢查並取得鎖定、而非使用內部資料庫 Snapshot 。




. 在「*記錄備份*」區段中、選取*完成時驗證記錄備份*、以在完成時驗證記錄備份。
. 在「*驗證指令碼設定*」區段中、分別輸入驗證作業之前或之後應執行的預先記錄或PostScript路徑和引數。
+

NOTE: 預先編寫或後製指令碼路徑不應包含磁碟機或共用區。路徑應相對於指令碼路徑。





== 步驟 10 ：檢視摘要

. 檢閱摘要、然後選取 * 完成 * 。

