---
permalink: protect-sco/concept_prepare_for_protecting_oracle_databases.html 
sidebar: sidebar 
keywords: oracle, preparation for protection, prerequisites 
summary: 在執行任何資料保護作業（例如備份、複製或還原作業）之前、您必須先定義策略並設定環境。您也可以設定SnapCenter 使用SnapMirror和SnapVault SnapMirror技術的「支援伺服器」。 
---
= 準備保護Oracle資料庫
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在執行任何資料保護作業（例如備份、複製或還原作業）之前、您必須先定義策略並設定環境。您也可以設定SnapCenter 使用SnapMirror和SnapVault SnapMirror技術的「支援伺服器」。

若要善用SnapVault SnapMirror和SnapMirror技術、您必須在儲存設備的來源與目的地磁碟區之間設定及初始化資料保護關係。您可以使用NetAppSystem Manager、也可以使用儲存主控台命令列來執行這些工作。

在您使用Oracle資料庫外掛程式之前、SnapCenter 管理員應先安裝及設定SnapCenter 支援服務器、並執行必要的工作。

* 安裝及設定SnapCenter 靜態伺服器。 link:../install/task_install_the_snapcenter_server_using_the_install_wizard.html["深入瞭解"^]
* 透過新增儲存系統連線來設定SnapCenter 靜態環境。 link:../install/task_add_storage_systems.html["深入瞭解"^]
+

NOTE: 不支援在不同叢集上使用相同名稱的多個SVM。SnapCenter每個以SnapCenter SVM登錄或叢集登錄登錄登錄的SVM都必須是唯一的。

* 以驗證模式建立認證、做為安裝使用者的Linux或AIX。 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#set-up-credentials["深入瞭解"^]
* 新增主機、安裝外掛程式、以及探索資源。
* 如果您使用SnapCenter VMware Server來保護位於VMware RDM LUN或VMDK上的Oracle資料庫、則必須部署SnapCenter 適用於VMware vSphere的「支援VMware vSphere的支援中心」外掛程式、並以SnapCenter 「支援中心」登錄外掛程式。
* 在Linux或AIX主機上安裝Java。
+
請參閱 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#linux-host-requirements["Linux 主機需求"^] 或 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#aix-host-requirements["AIX主機需求"^] 以取得更多資訊。

* 您應該將應用程式防火牆的逾時值設定為3小時以上。
* 如果NFS環境中有Oracle資料庫、則必須至少設定一個NFS資料LIF用於一線或二線儲存設備、才能執行掛載、複製、驗證及還原作業。
* 如果您有多個資料路徑（lifs）或一個DNFS組態、您可以使用SnapCenter 資料庫主機上的CLI執行下列動作：
+
** 根據預設、資料庫主機的所有IP位址都會新增至複製磁碟區的儲存虛擬機器（SVM）中的NFS儲存匯出原則。如果您想要擁有特定的IP位址、或是限制為IP位址的子集、請執行Set-PreferredHostIPsInStorageExpportPolicy CLI。
** 如果SVM中有多個資料路徑（LIF）、SnapCenter 則選擇適當的資料路徑（LIF）來掛載NFS複製的Volume。不過、如果您要指定特定的資料路徑（LIF）、則必須執行Set-SvmPreferredDataPath CLI。命令參考指南有更多資訊。


* 如果SAN環境中有Oracle資料庫、請務必依照下列指南所述的建議來設定SAN環境：
+
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547957["Linux Unified Host Utilities的建議主機設定"^]
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["使用Linux主機搭配ONTAP 不含資源的儲存設備"^]
** https://library.netapp.com/ecm/ecm_download_file/ECMP1119218["受AIX主機公用程式影響的主機設定"^]


* 如果您在Oracle Linux或RHEL作業系統的LVM上有Oracle資料庫、請安裝最新版的邏輯Volume Management（LVM）。
* 如果您使用SnapManager 的是適用於Oracle的支援功能、而且想要移轉至SnapCenter 適用於Oracle資料庫的支援功能、您可以SnapCenter 使用sccli命令sc-migrate、將設定檔移轉至適用於Oracle資料庫的原則和資源群組。
* 如果SnapVault 您想要備份複寫、請設定ONTAP SnapMirror和支援功能


針對VMware vSphere 4.1.1版的《VMware vSphere 4.1.1版》（《VMware vSphere 4.1.1版》）文件提供有關保護虛擬化資料庫和檔案系統的資訊。SnapCenter SnapCenter對於NetApp Data Broker 1.0和1.0.1、NetApp Data Broker 4.2.x使用者而言、文件中包含使用以Linux為基礎的NetApp Data Broker虛擬應用裝置（開放式虛擬應用裝置格式）所提供的VMware vSphere版《支援VMware vSphere的VMware外掛程式》來保護虛擬化資料庫和檔案系統的相關資訊。SnapCenter SnapCenter針對VMware vSphere 4.3的《VMware vSphere 4.3的VMware vCenter外掛程式》文件、提供SnapCenter 使用VMware vSphere虛擬應用裝置的Linux版《VMware vSphere的VMware vSphere虛擬應用程式》（開放式虛擬應用裝置格式）來保護虛擬化資料庫和檔案系統的相關資訊。SnapCenter SnapCenter

*瞭解更多資訊*

* https://imt.netapp.com/matrix/imt.jsp?components=112391;&solution=1259&isHWU&src=IMT["互通性對照表工具"^]
* https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/index.html["VMware vSphere文件的VMware外掛程式SnapCenter"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Data_protection_operation_fails_in_a_non-multipath_environment_in_RHEL_7_and_later["在RHEL 7及更新版本的非多重路徑環境中、資料保護作業會失敗"^]

