---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter 如何探索 Oracle 資料庫。 
---
= RAC設定中的慣用節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 Oracle Real Application Clusters （ RAC ）設定中、您可以指定 SnapCenter 用來執行備份作業的偏好節點。如果您未指定偏好的節點、SnapCenter 則會自動將節點指派為偏好的節點、並在該節點上建立備份。

偏好的節點可能是存在RAC資料庫執行個體的一個或所有叢集節點。只有在這些偏好的節點上、才會依偏好順序觸發備份作業。

.範例
RAC 資料庫 cdrac 有三個執行個體： node1 上的 cdrcbra1 、 node2 上的 cdrbcbra2 、 node3 上的 cdrbcbra3 。

節點1和節點2執行個體已設定為慣用節點、節點2為第一個偏好選項、節點1為第二個偏好選項。當您執行備份作業時、會先在節點2上嘗試此作業、因為節點2是第一個慣用節點。

如果節點2未處於備份狀態、這可能是因為主機上未執行外掛程式代理程式等多種原因、則主機上的資料庫執行個體不會處於指定備份類型所需的狀態、 或是FlexASM組態中節點2上的資料庫執行個體未由本機ASM執行個體提供服務、則會在節點1上嘗試執行該作業。

節點3不會用於備份、因為它不在偏好的節點清單中。



== Flex ASM 設定

在Flex ASM設定中、如果基數小於RAC叢集中的節點數、則不會將葉節點列為偏好的節點。如果Flex ASM叢集節點角色有任何變更、您應該手動探索、以便重新整理偏好的節點。



== 必要的資料庫狀態

偏好的節點上的RAC資料庫執行個體必須處於必要狀態、備份才能成功完成：

* 設定的慣用節點中的其中一個RAC資料庫執行個體必須處於開啟狀態、才能建立線上備份。
* 設定的慣用節點中的其中一個RAC資料庫執行個體必須處於掛載狀態、而所有其他執行個體（包括其他慣用節點）必須處於掛載狀態或更低狀態、才能建立離線掛載備份。
* RAC資料庫執行個體可以處於任何狀態、但您必須指定偏好的節點、才能建立離線關機備份。

