---
permalink: protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: storage types, iSCSI, NFS, RDM, VMDK, NFS, LVM, ASM, SAN filesystem 
summary: 支援實體與虛擬機器上的各種儲存類型。SnapCenter您必須先確認儲存類型的支援、才能安裝SnapCenter 適用於Linux的支援功能套件或SnapCenter 適用於AIX的支援功能。 
---
= Oracle資料庫外掛程式支援的儲存類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援實體與虛擬機器上的各種儲存類型。SnapCenter您必須先確認儲存類型的支援、才能安裝SnapCenter 適用於Linux的支援功能套件或SnapCenter 適用於AIX的支援功能。

不支援Linux和AIX的儲存資源配置。SnapCenter



== Linux支援的儲存類型

下表列出Linux支援的儲存類型。

|===
| 機器 | 儲存類型 


 a| 
實體伺服器
 a| 
* 連接FC的LUN
* 連接iSCSI的LUN
* NFS連線的磁碟區




 a| 
VMware ESXi
 a| 
* RDM LUN連接FC或iSCSI ESXi主機匯流排介面卡（HBA）的HBASCanning可能需要很長時間才能完成、因為SnapCenter VMware會掃描主機中所有的主機匯流排介面卡。
+
您可以編輯位於_/opt/netapp/snapcenter/spl/plugins/scue/scucore /模組/scu/Config_的* Linux Config.pm*檔案、將* scsi_hosts_optimized_resc*參數的值設為1、以便僅重新掃描HBA驅動程式名稱中列出的HBA。

* iSCSI啟動器直接連接至來賓系統的iSCSI LUN
* VMFS或NFS資料存放區上的VMDK
* NFS磁碟區直接連線至客體系統


|===


== AIX上支援的儲存類型

下表列出AIX上支援的儲存類型。

|===
| 機器 | 儲存類型 


 a| 
實體伺服器
 a| 
* 連接FC與iSCSI的LUN。
+
在SAN環境中、支援ASM、LVM和SAN檔案系統。

+

NOTE: 不支援AIX和檔案系統上的NFS。

* 強化日誌檔案系統（JFS2）
+
支援SAN檔案系統和LVM配置的即時記錄。



|===
。 https://imt.netapp.com/matrix/imt.jsp?components=112391;&solution=1259&isHWU&src=IMT["NetApp 互通性對照表工具"] 包含支援版本的最新資訊。
