---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: 您必須先定義策略、才能還原及還原資料庫、以便順利執行還原及還原作業。 
---
= 定義Oracle資料庫的還原與還原策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先定義策略、才能還原及還原資料庫、以便順利執行還原及還原作業。



== 支援還原與還原作業的備份類型

支援還原及還原不同類型的Oracle資料庫備份。SnapCenter

* 線上資料備份
* 離線關機資料備份
* 離線掛載資料備份
+

NOTE: 如果您要還原離線關機或離線掛載資料備份、SnapCenter 則會使資料庫處於離線狀態。您應該手動還原資料庫並重設記錄。

* 完整備份
* 資料保護待命資料庫的離線掛載備份
* Active Data Guard待命資料庫的純資料線上備份
+

NOTE: 您無法執行Active Data Guard待命資料庫的還原。

* 線上資料備份、線上完整備份、離線掛載備份、以及實際應用程式叢集（RAC）組態中的離線關機備份
* 在自動儲存管理（ASM）組態中進行線上資料備份、線上完整備份、離線掛載備份及離線關機備份




== Oracle資料庫支援的還原方法類型

支援Oracle資料庫的連線與複製或就地還原。SnapCenter在還原作業期間、SnapCenter 還原決定適合用於還原檔案系統的還原方法、而不會遺失任何資料。


NOTE: 不支援Volume型的功能。SnapCenter SnapRestore



=== 連線與複製還原

如果資料庫配置與備份不同、或在建立備份之後有任何新檔案、則會執行連線與複製還原。在連線與複製還原方法中、會執行下列工作：

*步驟*

. 磁碟區會從Snapshot複本複製、檔案系統堆疊會使用複製的LUN或磁碟區建立在主機上。
. 檔案會從複製的檔案系統複製到原始檔案系統。
. 然後從主機卸載複製的檔案系統、並從ONTAP 停止執行複製的磁碟區。



NOTE: 若為Flex ASM設定（其中基數小於RAC叢集中的節點數）或VMDK或RDM上的ASM RAC資料庫、則僅支援連線與複製還原方法。

即使您已強制啟用就地還原、SnapCenter 在下列情況下、也會執行連線與複製還原：

* 從二線儲存系統還原、Data ONTAP 如果不能在8.3之前還原
* 在未設定資料庫執行個體的Oracle RAC設定節點上、會出現ASM磁碟群組還原
* 在Oracle RAC設定中、如果ASM執行個體或叢集執行個體未執行、或對等節點當機、則會在任何對等節點上執行
* 僅還原控制檔
* 還原位於ASM磁碟群組中的資料表空間子集
* 磁碟群組會在資料檔案、sp檔案和密碼檔案之間共用
* 在RAC環境中、未在遠端節點上安裝或未執行「更新載入程式」（SPL）SnapCenter 服務
* 新節點會新增至Oracle RAC、SnapCenter 而不知悉最近新增的節點




=== 原地還原

如果資料庫配置與備份類似、而且尚未對儲存設備和資料庫堆疊進行任何組態變更、則會執行就地還原、在ONTAP 其中還原檔案或LUN。作爲就地還原方法的一部分、支援僅單一檔案還原（SFSR）SnapCenter SnapRestore 。


NOTE: 支援從次要位置進行就地還原的支援（8.3或更新版本）Data ONTAP 。

如果您要在資料庫上執行就地還原、請確定ASM磁碟群組上只有資料檔案。您必須在ASM磁碟群組或資料庫實體結構進行任何變更之後建立備份。執行就地還原之後、磁碟群組將包含與備份時相同的資料檔案數目。

當磁碟群組或掛載點符合下列條件時、系統會自動套用就地還原：

* 備份後不會新增任何資料檔（外部檔案檢查）
* 備份後、不新增、刪除或重新娛樂ASM磁碟或LUN（ASM磁碟群組結構變更檢查）
* 不新增、刪除或重新建立LUN至LVM磁碟群組（LVM磁碟群組結構變更檢查）



NOTE: 您也可以使用GUI、SnapCenter S還原CLI或PowerShell Cmdlet強制啟用就地還原、以覆寫外部檔案檢查和LVM磁碟群組結構變更檢查。



==== 在ASM RAC上執行就地還原

在還原中SnapCenter 、您執行還原的節點稱為主要節點、而ASM磁碟群組所在RAC的所有其他節點稱為對等節點。執行儲存還原作業之前、將ASM磁碟群組的狀態變更為在ASM磁碟群組處於掛載狀態的所有節點上卸載。SnapCenter儲存還原完成後、SnapCenter 即可變更ASM磁碟群組在還原作業之前的狀態。

在SAN環境中SnapCenter 、ENetApp會從所有對等節點移除裝置、並在儲存還原作業之前執行LUN取消對應作業。儲存還原作業完成後SnapCenter 、將執行LUN對應作業、並在所有對等節點上建構裝置。如果Oracle RAC ASM配置位於LUN上、則在SAN環境中、還原SnapCenter 時、會在ASM磁碟群組所在的RAC叢集的所有節點上執行LUN取消對應、LUN還原及LUN對應作業。還原SnapCenter 之前、即使RAC節點的所有啟動器都未用於LUN、還原後仍會建立一個新的iGroup、其中包含所有RAC節點的所有啟動器。

* 如果對等節點上的預先儲存活動期間發生任何故障、SnapCenter 則在成功執行預先儲存作業的對等節點上執行還原之前、會自動復原ASM磁碟群組狀態。作業失敗的主要節點和對等節點不支援復原。在嘗試其他還原之前、您必須手動修正對等節點上的問題、並將主節點上的ASM磁碟群組恢復為掛載狀態。
* 如果還原活動期間發生任何故障、則還原作業會失敗、而且不會執行回復。在嘗試其他還原之前、您必須手動修正儲存還原問題、並將主節點上的ASM磁碟群組恢復至掛載狀態。
* 如果在任何對等節點上進行還原後活動時發生任何故障、SnapCenter 則會繼續在其他對等節點上執行還原作業。您必須手動修正對等節點上的POST還原問題。




== Oracle資料庫支援的還原作業類型

利用此功能、您可以針對Oracle資料庫執行不同類型的還原作業。SnapCenter

在還原資料庫之前、系統會驗證備份、以識別與實際資料庫檔案相比、是否有任何檔案遺失。



=== 完整還原

* 僅還原資料檔案
* 僅還原控制檔
* 還原資料檔案和控制檔
* 在Data Guard待命和Active Data Guard待命資料庫中還原資料檔案、控制檔和重作記錄檔




=== 部分還原

* 僅還原選取的資料表空間
* 僅還原選取的可插拔資料庫（PDF）
* 僅還原選定的pdb表格空間




== Oracle資料庫支援的恢復作業類型

利用此功能、您可以為Oracle資料庫執行不同類型的恢復作業。SnapCenter

* 資料庫直到最後一筆交易（所有記錄）
* 資料庫、直到特定的系統變更編號（SCN）
* 資料庫、直到特定日期和時間為止
+
您必須根據資料庫主機的時區、指定恢復的日期和時間。

+
此外、Oracle資料庫也提供「無法恢復」選項。SnapCenter




NOTE: 如果您使用以資料庫角色為待命狀態所建立的備份來還原、則Oracle資料庫的外掛程式不支援還原。您必須永遠為實體待命資料庫執行手動還原。



== 與Oracle資料庫的還原與還原有關的限制

在執行還原與還原作業之前、您必須瞭解這些限制。

如果您使用的Oracle版本從11.2.0.4到12.1.0.1、則當您執行_renamedg_命令時、還原作業將會處於掛起狀態。您可以套用Oracle修補程式19544733來修正此問題。

不支援下列還原與還原作業：

* 還原及還原根容器資料庫（CDB）的資料表空間
* 還原與PDF相關的暫用資料表空間和暫用資料表空間
* 同時從多個PDF還原及還原資料表空間
* 還原記錄備份
* 將備份還原至不同位置
* 還原Data Guard待命或Active Data Guard待命資料庫以外的任何組態中的重作記錄檔
* 還原SPILE和密碼檔案
* 當您在使用同一主機上預先存在的資料庫名稱重新建立的資料庫上執行還原作業時、該資料庫是SnapCenter 由DB2管理、並具有有效的備份、即使資料庫ID不同、還原作業仍會覆寫新建立的資料庫檔案。
+
您可以執行下列任一動作來避免這種情況：

+
** 重新建立資料庫後、探索SnapCenter 各種功能
** 建立重新建立之資料庫的備份






== 與表空間時間點還原有關的限制

* 不支援系統、SYSAUX和復原表格空間的時間點還原（PIDR）
* 表空間的PITR無法與其他類型的還原一起執行
* 如果表空間已重新命名、而您想要將其還原至重新命名前的某個點、則應指定表空間的較早名稱
* 如果某個表空間中的表的約束包含在另一個表空間中，則應恢復這兩個表空間
* 如果某個資料表及其索引儲存在不同的資料表空間中、則在執行PIGR之前、索引應先捨棄
* PIGR無法用於恢復目前的預設表格空間
* PIGR無法用來還原包含下列任何物件的資料表空間：
+
** 具有基礎物件（例如實際視圖）或包含物件（例如分割資料表）的物件、除非所有基礎或包含的物件都在還原集中
+
此外、如果分割資料表的分割區儲存在不同的資料表空間中、則在執行PIGR之前、您應該先刪除該資料表、或是在執行PIGR之前、將所有分割區移至相同的資料表空間。

** 復原或復原區段
** Oracle 8相容進階佇列、可容納多位收件者
** 由SYS使用者擁有的物件
+
這些物件類型的範例包括：PL/SQL、Java類別、呼叫程式、檢視、同義字、 使用者、權限、維度、目錄和順序。







== 用於還原Oracle資料庫的來源和目的地

您可以從主要儲存設備或次要儲存設備上的備份複本還原Oracle資料庫。您只能將資料庫還原至同一個資料庫執行個體上的相同位置。不過、在Real Application Cluster（RAC）設定中、您可以將資料庫還原至其他節點。



=== 還原作業來源

您可以從主要儲存設備或次要儲存設備上的備份還原資料庫。如果您想要從多重鏡射組態中的次要儲存設備備份還原、可以選取次要儲存鏡射作為來源。



=== 還原作業的目的地

您只能將資料庫還原至同一個資料庫執行個體上的相同位置。

在RAC設定中、您可以從叢集中的任何節點還原RAC資料庫。
