---
permalink: protect-sce/concept_snapcenter_plug_in_for_exchange_server_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Exchange Server 
summary: 適用於Microsoft Exchange Server的功能區外掛程式是NetAppSnapCenter軟體的主機端元件、可讓您對Exchange資料庫進行應用程式感知資料保護管理。SnapCenterExchange外掛程式可在SnapCenter 您的支援環境中自動備份及還原Exchange資料庫。 
---
= 適用於Microsoft Exchange Server的插件概述SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於Microsoft Exchange Server的《支援功能》外掛程式是NetApp支援應用程式感知的Exchange資料庫資料保護管理功能的NetApp支援軟體主機端元件。SnapCenter SnapCenterExchange外掛程式可在SnapCenter 您的支援環境中自動備份及還原Exchange資料庫。

安裝Exchange外掛程式時、您可以使用SnapCenter 搭配NetApp SnapMirror技術的功能來建立另一個磁碟區上備份集的鏡射複本、並使用NetApp SnapVault 支援技術來執行磁碟對磁碟備份複寫、以符合標準或用於歸檔。

如果您想要還原及還原郵件或信箱、而非完整的Exchange資料庫、可以使用單一信箱恢復（SMBR）軟體。
NetApp ® 單一信箱恢復已於 2023 年 5 月 12 日結束可用度（ EOA ）。NetApp 將持續支援已於 2020 年 6 月 24 日推出的行銷零件編號、以支援購買信箱容量、維護和支援的客戶。

NetApp 單一信箱恢復是 Ontrack 提供的合作夥伴產品。Ontrack PowerControl 提供的功能與 NetApp 單一信箱恢復功能類似。客戶可從 Ontrack 購買全新 Ontrack PowerControl 軟體授權、以及 Ontrack PowerControl 的維護與支援續約（透過 licensingteam@ontrack.com ）、以進行精細的信箱恢復。

Exchange 外掛程式支援 SnapMirror 主動式同步（最初以 SnapMirror Business Continuity [SM-BC] 發行）、即使整個站台發生故障、商業服務也能繼續運作、支援應用程式使用次要複本進行透明容錯移轉。使用 SnapMirror 主動式同步觸發容錯移轉時、不需要手動介入或額外的指令碼處理。

它支援 SnapMirror Active Sync 的非對稱、容錯移轉或非雙工模式。這是指最佳化路徑僅來自主側 LUN 擁有節點的解決方案。任何進入次要叢集路徑的 I/O 都是透過將其代理至主要叢集來提供服務。同步複寫是單向的、方向是從一級到二級。

* 在SnapCenter 您的支援環境中、自動化Microsoft Exchange Server資料庫和資料庫可用度群組（DAG）的應用程式感知備份與還原作業
* 當您部署適用於 VMware vSphere 的 SnapCenter 外掛程式，並向 SnapCenter 註冊外掛程式時，可在 RDM LUN 上支援虛擬化 Exchange Server 。

