---
permalink: protect-sce/reference_prerequisites_to_add_hosts_and_install_snapcenter_plug_in_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server 
summary: 新增主機並安裝外掛程式套件之前、您必須先完成所有需求。 
---
= 新增主機及安裝SnapCenter Microsoft Exchange Server的功能的先決條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增主機並安裝外掛程式套件之前、您必須先完成所有需求。

* 如果您使用iSCSI、則必須執行iSCSI服務。
* 您必須擁有具有本機系統管理員權限的網域使用者、並在遠端主機上具有本機登入權限。
* 您必須使用 Microsoft Exchange Server 進行獨立設定和資料庫可用性群組配置。請參閱 link:https://imt.netapp.com/imt/#search["互通性矩陣工具（IMT）"^] 以了解支援的 Microsoft Exchange Server 版本。
* 在Windows主機上安裝外掛程式時、如果您指定的認證不是內建的、或是使用者屬於本機工作群組使用者、則必須停用主機上的UAC.
* 如果您管理SnapCenter 的是叢集節點、則必須有擁有叢集中所有節點管理權限的使用者。
* 您的使用者必須具有Exchange Server的管理權限。
* 如果SnapManager 已SnapDrive 安裝適用於Microsoft Exchange Server和Windows的Sfor、則必須先取消登錄SnapDrive 適用於Windows的VSS硬體供應商、才能在同一部Exchange Server上安裝Exchange外掛程式、以確保使用SnapCenter WALL成功保護資料。
* 如果SnapManager 同一部伺服器上安裝了適用於Microsoft Exchange Server和Exchange外掛程式、則您必須暫停或刪除Windows排程器SnapManager 中所有由Microsoft Exchange Server的更新排程。
* 主機必須可解析為伺服器的完整網域名稱（FQDN）。如果已修改hosts檔案以使其可解析、且在hosts檔案中同時指定了簡短名稱和FQDN、請在SnapCenter 下列格式的Sesfhosts檔案中建立項目：_<ip_address><host_fqd><host_name>_。
* 請確保防火牆未封鎖以下連接埠，否則新增主機操作將失敗。若要解決此問題，您必須設定動態連接埠範圍。如需詳細資訊，請參閱 https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-rpc-dynamic-port-allocation-with-firewalls["Microsoft文件"^]。有關支援的 Microsoft Exchange Server 版本，請參閱link:https://imt.netapp.com/imt/#search["互通性矩陣工具（IMT）"^]。
+
** 適用於Windows 2019的連接埠範圍為49152 - 65536
** 適用於Windows 2016和Exchange 2016的連接埠範圍為50000 - 51000
** Windows 2012 R2 和 Exchange 2013 的連接埠範圍 6000 - 6500




[NOTE]
====
若要識別連接埠範圍、請執行下列命令：

* Netsh int ipv4顯示為Dynamicport tcp
* Netsh int ipv4顯示Dynamicport udp
* Netsh int IPv6顯示為Dynamicport TCP
* Netsh int IPv6顯示Dynamicport udp


====


== 安裝SnapCenter 適用於Windows的功能性外掛程式套件的主機需求

在安裝SnapCenter 適用於Windows的整套解決方案之前、您應該先熟悉一些基本的主機系統空間需求和規模調整需求。

|===
| 項目 | 需求 


 a| 
作業系統
 a| 
Microsoft Windows

有關受支援版本的最新信息，請參閱 https://imt.netapp.com/imt/imt.jsp?components=180321;180339;&solution=1257&isHWU&src=IMT["NetApp 互通性對照表工具"^]。



 a| 
主機上安裝的不需使用的RAM SnapCenter
 a| 
1 GB



 a| 
主機上安裝及記錄SnapCenter 插件的最低空間
 a| 
5 GB


NOTE: 您應該配置足夠的磁碟空間、並監控logs資料夾的儲存使用量。所需的記錄空間會因受保護的實體數量和資料保護作業的頻率而有所不同。如果沒有足夠的磁碟空間、將不會針對最近執行的作業建立記錄。



 a| 
必要的軟體套件
 a| 
* ASP.NET Core Runtime 10.0.7 Hosting Bundle （或更高版本）
* PowerShell 7.6.1（或更高版本）
* Java 17（Oracle Java、OpenJDK 或 SAP JDK）或 Java 11（適用於 SnapCenter 6.2 或更早版本）


請參閱 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP3359467["SnapCenter 軟體發行說明"^]，以取得適用於您特定 SnapCenter 版本的最新合格 ASP.NET Core 與 PowerShell 版本。

如需 .NET 特定疑難排解資訊、請參閱 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["無法升級或安裝不適用於沒有網際網路連線的舊系統。SnapCenter"]

|===


== 需要Exchange Server權限

若要啟用SnapCenter 支援功能以新增Exchange Server或DAG、並在SnapCenter 主機或DAG上安裝適用於Microsoft Exchange Server的支援功能外掛程式、您必須為SnapCenter 擁有最低權限和權限的使用者設定認證功能。

您必須擁有具有本機系統管理員權限的網域使用者、並擁有遠端Exchange主機的本機登入權限、以及DAG中所有節點的系統管理權限。網域使用者需要下列最低權限：

* add-MailboxDatabaseCopy
* 卸載資料庫
* Get-AdServerSettings
* Get-DatabaseAvailable Group
* Get-ExchangeServer
* Get-mailboxDatabase
* Get-MailboxDatabaseCopyStatus
* Get-MailboxServer
* Get-MailboxStatistics
* Get-PublicFolderDatabase
* move-ActiveMailboxDatabase
* move-DatabasePath -Configuration Only：$true
* 掛載資料庫
* 全新的mailboxDatabase
* 新出版資料庫
* 去除mailboxDatabase
* 去除MailboxDatabaseCopy
* 移除-出版資料庫
* RESUME：MailboxDatabaseCopy
* Set-AdServerSettings
* Set-mailboxdatabase-allowfilerestore：$true
* Set-MailboxDatabaseCopy
* Set-PublicFolderDatabase
* suspend-MailboxDatabaseCopy
* update-MailboxDatabaseCopy

