---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords:  
summary: 您可以先為Exchange資源或資源群組建立備份原則、再使用SnapCenter 支援功能來備份Microsoft Exchange Server資源、也可以在建立資源群組或備份單一資源時建立備份原則。 
---
= 為Exchange Server資料庫建立備份原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以先為Exchange資源或資源群組建立備份原則、再使用SnapCenter 支援功能來備份Microsoft Exchange Server資源、也可以在建立資源群組或備份單一資源時建立備份原則。

*您需要的是什麼*

* 您必須已定義資料保護策略。
+
如需詳細資訊、請參閱定義Exchange資料庫資料保護策略的相關資訊。

* 您必須完成安裝SnapCenter 、新增主機、識別資源及建立儲存系統連線等工作、以準備好保護資料。
* 您必須重新整理（探索到）Exchange Server資源。
* 如果您要將Snapshot複本複製到鏡射或保存庫、SnapCenter 則該管理員必須已將來源磁碟區和目的地磁碟區的儲存虛擬機器（SVM）指派給您。
* 如果您想以預先編寫和後指令碼執行PowerShell指令碼、您應該在「web.config」檔案中將「usePowerShellProcessforScripts」參數的值設為true。
+
預設值為假



*關於此工作*

* 備份原則是一組規則、可控制您管理及保留備份的方式、以及資源或資源群組的備份頻率。此外、您也可以指定指令碼設定。在原則中指定選項可節省您想要重複使用其他資源群組原則的時間。
* 完整備份保留僅適用於特定原則。使用原則A且完整備份保留4的資料庫或資源會保留4個完整備份、且不會影響相同資料庫或資源的原則B、因為該原則B可能保留3個完整備份。
* 記錄備份保留在不同原則之間都有效、適用於資料庫或資源的所有記錄備份。因此、使用原則B執行完整備份時、記錄保留設定會影響原則A在同一個資料庫或資源上建立的記錄備份。同樣地、原則A的記錄保留設定也會影響原則B在同一個資料庫上建立的記錄備份。
* 可使用外掛主機SMCoreServiceHost.exe.Config檔案中的PredefinedWindows指令碼目錄金鑰來定義指令碼路徑。
+
如有需要、您可以變更此路徑並重新啟動SMcore服務。建議您使用預設的安全路徑。

+
金鑰的值可透過API：API /4.7/configsettings從交換器顯示

+
您可以使用Get API來顯示金鑰的值。不支援Set API。



|===


| *最佳實務做法：*您最好根據您想保留的完整備份數和記錄備份總數來設定次要保留原則。當您設定次要保留原則時、請記住、當資料庫和記錄位於不同的磁碟區時、每個備份都可以有三個Snapshot複本、而且當資料庫和記錄位於同一個磁碟區時、每個備份都可以有兩個Snapshot複本。 
|===
*步驟*

. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下*原則*。
. 按一下「*新增*」。
. 在「名稱」頁面中、輸入原則名稱和說明。
. 在「備份類型」頁面中、執行下列步驟：
+
.. 選擇備份類型：
+
|===
| 如果您想要... | 執行此動作... 


 a| 
備份資料庫檔案和必要的交易記錄
 a| 
選擇*完整備份與記錄備份*。

資料庫會以記錄截短功能備份、並備份所有記錄、包括遭截的記錄。


NOTE: 這是建議的備份類型。



 a| 
備份資料庫檔案和未提交的交易記錄
 a| 
選擇*完整備份*。

資料庫備份時會使用記錄截短功能、而且不會備份遭截的記錄。



 a| 
備份所有交易記錄
 a| 
選擇*記錄備份*。

使用中檔案系統上的所有交易記錄都會備份、而且不會有記錄檔被刪減。

在與即時記錄相同的磁碟上建立_scebackupinfo_目錄。此目錄包含Exchange資料庫遞增變更的指標、並不等同於完整的記錄檔。



 a| 
備份所有資料庫檔案和交易記錄、而不需刪減交易記錄檔
 a| 
選擇*複製備份*。

所有資料庫和所有記錄都會備份、而且不會有記錄檔被刪減。您通常會使用此備份類型來重新建立複本、或用於測試或診斷問題。

|===
+

NOTE: 您應該根據完整備份保留、而非根據最新（UTM）保留來定義記錄備份所需的空間。

.. 在Database Availability Group Settings（資料庫可用度群組設定）區段中、選取一個動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
備份使用中的複本
 a| 
選取此選項可僅備份所選資料庫的使用中複本。

對於資料庫可用度群組（DAG）、此選項只會備份DAG中所有資料庫的作用中複本。

被動複本不會備份。



 a| 
備份伺服器上的複本、以便在建立備份工作時選取
 a| 
選取此選項可備份所選伺服器上的任何資料庫複本、包括主動式和被動式。

對於DAG、此選項會備份所選伺服器上所有資料庫的主動和被動複本。

|===
+

NOTE: 在叢集組態中、備份會根據原則中設定的保留設定保留在叢集的每個節點上。如果叢集的擁有者節點變更、則會保留先前擁有者節點的備份。保留僅適用於節點層級。

.. 在「排程頻率」區段中、選取一或多個頻率類型：*隨選*、*每小時*、*每日*、*每週*和*每月*。
+

NOTE: 您可以在建立資源群組時、指定備份作業的排程（開始日期、結束日期）。這可讓您建立共用相同原則和備份頻率的資源群組、但可讓您為每個原則指派不同的備份排程。

+

NOTE: 如果您排定在上午2：00、則在夏令時間（Dst）期間不會觸發排程。



. 在「保留」頁面中、設定保留設定。
+
顯示的選項取決於您先前選取的備份類型和頻率類型。

+

NOTE: 對於使用率為1018的ONTAP 資源、如使用率為0、9.4或更新版本、ONTAP 而使用率為254的資源、如使用率為0、9.3或更新版本。如果保留設定的值高於基礎ONTAP 版支援的值、則備份將會失敗。

+

IMPORTANT: 如果您打算啟用SnapVault 此功能、則必須將保留數設為2或更高。如果您將保留數設為1、則保留作業可能會失敗、因為第一個Snapshot複本是SnapVault 參考Snapshot複本、用於進行此關係、直到將較新的Snapshot複本複寫到目標為止。

+
.. 在記錄備份保留設定區段中、選取下列其中一項：
+
|===
| 如果您想要... | 執行此動作... 


 a| 
只保留特定數量的記錄備份
 a| 
選取*保留記錄的完整備份數目*、然後指定您要達到最新還原的完整備份數目。

最新（UTM）保留適用於透過完整備份或記錄備份建立的記錄備份。例如、如果UTM保留設定為保留最後5個完整備份的記錄備份、則會保留最後5個完整備份的記錄備份。

在UTM中、系統會自動刪除作為完整備份和記錄備份一部分所建立的記錄資料夾。您無法手動刪除記錄資料夾。例如、如果完整或完整備份和記錄備份的保留設定設為1個月、且UTM保留設為10天、則依照UTM所建立的記錄資料夾、將會刪除這些備份的一部分。因此、只會有10天的記錄資料夾、所有其他備份都會標示為時間點還原。

如果不想執行最新還原、您可以將UTM保留值設為0。這將啟用時間點還原作業。

*最佳實務做法：*最佳做法是、此設定必須等於「完整備份保留設定」區段中的「Snapshot複本總數（完整備份）」設定值。如此可確保每個完整備份都保留記錄檔。



 a| 
保留備份複本的特定天數
 a| 
選取*保留記錄備份做為最後一個*選項、並指定保留記錄備份複本的天數。

記錄備份會保留到完整備份的天數。

|===
+
如果您選擇*記錄備份*做為備份類型、則記錄備份會保留為完整備份的最新保留設定之一。

.. 在完整備份保留設定區段中、針對隨需備份選取下列其中一項、然後選取一項以進行完整備份：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
僅保留特定數量的Snapshot複本
 a| 
如果您要指定要保留的完整備份數、請選取*要保留的Snapshot複本總數*選項、然後指定要保留的Snapshot複本數（完整備份）。

如果完整備份數超過指定數目、則會刪除超過指定數目的完整備份、並先刪除最舊的複本。



 a| 
保留完整備份的特定天數
 a| 
選取*「將Snapshot複本保留為*」選項、並指定保留Snapshot複本（完整備份）的天數。

|===
+

NOTE: 如果您的資料庫只有記錄備份、而且主機上的DAG組態沒有完整備份、則記錄備份會以下列方式保留：

+
*** 根據預設、SnapCenter 在DAG中的所有其他主機上、均會尋找此資料庫最舊的完整備份、並刪除此主機上在完整備份之前所進行的所有記錄備份。
*** 您可以在_C:\Program Files\NetApp\SnapCenter webapp\web.config_檔案中新增* MaxLogBackupOnlyCountWithoutFullBackup *金鑰、以取代DAG主機上的上述預設保留行為。
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
在範例中、值10表示您最多可在主機上保留10個記錄備份。





. 在「複寫」頁面中、選取下列其中一個或兩個次要複寫選項：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
建立本機Snapshot複本之後、請更新SnapMirror
 a| 
選取此選項可將備份集的鏡射複本保留在另一個磁碟區（SnapMirror）上。



 a| 
建立本機Snapshot複本後再更新SnapVault
 a| 
選取此選項以執行磁碟對磁碟備份複寫。



 a| 
次要原則標籤
 a| 
選取Snapshot標籤。

根據您選取的Snapshot複本標籤、ONTAP 將套用符合標籤的次要Snapshot複本保留原則。


NOTE: 如果您在建立本機Snapshot複本之後選擇*更新SnapMirror、您可以選擇性地指定次要原則標籤。不過、如果SnapVault 您在建立本機Snapshot複本*之後選擇*更新SUpdate、則應指定次要原則標籤。



 a| 
重試次數錯誤
 a| 
輸入在程序停止之前應進行的複寫嘗試次數。

|===
+

NOTE: 您應該在ONTAP 適用於二線儲存設備的SnapMirror保留原則中進行設定、以避免達到二線儲存設備上Snapshot複本的上限。

. 在「指令碼」頁面中、分別輸入備份作業之前或之後應執行的指令碼或指令碼路徑和引數。
+
** Presc文稿 備份引數包括「$Database」和「$ServerInstance」。
** 附有「$Database」、「$ServerInstance」、「$Backup Name」、「$LogDirectory」及「$LogSnapshot」等備份引數。
+
您可以執行指令碼來更新SNMP設陷、自動化警示、傳送記錄等等。

+

NOTE: 預先編寫或後製指令碼路徑不應包含磁碟機或共用區。路徑應相對於指令碼路徑。



. 檢閱摘要、然後按一下「*完成*」。

