---
permalink: protect-sce/task_install_the_snapcenter_plug_in_for_exchange_silently_from_the_command_line.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 您應該從SnapCenter 「版本資訊」使用者介面中安裝Exchange外掛程式。不過、如果您因為某些原因無法執行、您可以從Windows命令列以無訊息模式執行外掛程式的Exchange安裝程式。 
---
= 從命令列以無訊息方式安裝SnapCenter Exchange的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該從SnapCenter 「版本資訊」使用者介面中安裝Exchange外掛程式。不過、如果您因為某些原因無法執行、您可以從Windows命令列以無訊息模式執行外掛程式的Exchange安裝程式。

.開始之前
* 您必須備份Microsoft Exchange Server資源。
* 您必須已安裝SnapCenter 完整套的不更新程式。
* 安裝之前、您必須先刪除SnapCenter 舊版的Microsoft SQL Server適用的更新版本。
+
如需詳細資訊、請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["如何SnapCenter 手動直接從外掛主機安裝功能不全的外掛程式"^]。



.步驟
. 驗證外掛程式主機上是否存在_C：\temp_資料夾、且登入的使用者是否擁有該資料夾的完整存取權。
. 從SnapCenter _C：\ProgramData \NetApp\SnapCenter\Package_儲存庫下載適用於Microsoft Windows的支援功能外掛程式。
+
此路徑可從SnapCenter 安裝了此伺服器的主機存取。

. 將安裝檔案複製到您要安裝外掛程式的主機。
. 從本機主機上的Windows命令提示字元、瀏覽至您儲存外掛程式安裝檔案的目錄。
. 輸入下列命令以安裝外掛程式。
+
_snapcenter_windows_host_plugin.exe"/silent /debuglog"<debug_Log_Path>"/log"<Log_Path>" BI_SNAPCENTER_port=<Num>套件_Install_Directory路徑>" BI_ServiceAccount=<domain\manager> BI_SERVER_SERVERICEPW=<FSCW_<SCPW_<SCPW>

+
例如：

+
_C：\ProgramData\NetApp\SnapCenter\Package儲存庫\snapcenter_windows_host_plugin.exe"/無聲/debuglog" C：\HPPW_SCSQL_Install.log"/log" C：\臨時" BI_SNAPCENTR_port=8145套件_INSTALLDIR="C：\Program Files\NetApp_Snap_SCWA_SCW=W_SCWAITY="ICW_SCWAITY="_SERVER_SCWAITY=_SCWAITY="/sec_SCWAITY="/sec_SCWAITY="/sec_SARITY=

+

NOTE: 安裝Exchange外掛程式時所傳遞的所有參數都區分大小寫。

+
輸入下列變數值：

+
|===
| 變動 | 價值 


 a| 
_/debuglog"<debug_Log_Path>_
 a| 
指定套件安裝程式記錄檔的名稱和位置、如下列範例所示：

_Setup.exe /debuglog" C：\PathToLog\setupexe.log_



 a| 
BI_SNAPCENTIER_port
 a| 
指定SnapCenter 用來與SMCore進行通訊的連接埠。



 a| 
套件_INSTALLDIR
 a| 
指定主機外掛程式套件安裝目錄。



 a| 
BI_ServiceAccount
 a| 
指定SnapCenter Microsoft Windows Web服務帳戶的功能外掛程式。



 a| 
BI_SERVERICEPWD
 a| 
指定SnapCenter Microsoft Windows Web服務帳戶的密碼。



 a| 
ISfeatureInstall
 a| 
指定SnapCenter 要在遠端主機上部署的解決方案。

|===
. 監控Windows工作排程器、主要安裝記錄檔_C：\Installdebug.log_、以及_C：\Temp _中的其他安裝檔案。
. 監控_%temp%_目錄、檢查_MSIexe.exe_安裝程式是否在安裝軟體時沒有錯誤。
+

NOTE: Exchange外掛程式的安裝會在主機上登錄外掛程式、而非SnapCenter 在支援伺服器上登錄外掛程式。您可以SnapCenter 透過SnapCenter 使用支援程式介面或PowerShell Cmdlet新增主機、在支援服務器上登錄外掛程式。新增主機之後、即會自動探索外掛程式。


