---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords:  
summary: 在建立備份工作之前定義備份策略、有助於確保您擁有成功還原資料庫所需的備份。您的服務層級協議（SLA）、恢復時間目標（RTO）和恢復點目標（RPO）、主要決定您的備份策略。 
---
= 定義Exchange Server資源的備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在建立備份工作之前定義備份策略、有助於確保您擁有成功還原資料庫所需的備份。您的服務層級協議（SLA）、恢復時間目標（RTO）和恢復點目標（RPO）、主要決定您的備份策略。

SLA定義預期的服務層級、並解決許多與服務相關的問題、包括服務的可用度和效能。RTO是指在服務中斷後必須還原業務程序的時間。RPO定義了檔案的存留期策略、這些檔案必須從備份儲存設備中恢復、以便在故障後恢復正常作業。SLA、RTO及RPO有助於備份策略。



== Exchange資料庫支援的備份類型

使用SnapCenter 支援功能來備份Exchange信箱時、您必須選擇資源類型、例如資料庫和資料庫可用度群組（DAG）。利用Snapshot複製技術來建立資源所在磁碟區的線上唯讀複本。

|===
| 備份類型 | 說明 


 a| 
完整備份與記錄備份
 a| 
備份資料庫和所有交易記錄、包括遭截的記錄。

完整備份完成後、Exchange Server會將已提交至資料庫的交易記錄檔刪減。

一般而言、您應該選擇此選項。不過、如果您的備份時間短、您可以選擇不使用完整備份來執行交易記錄備份。



 a| 
完整備份
 a| 
備份資料庫和交易記錄。

系統不會備份遭截的交易記錄。



 a| 
記錄備份
 a| 
備份所有交易記錄。

尚未備份已提交至資料庫的遭截取記錄。如果您在完整資料庫備份之間排程頻繁的交易記錄備份、您可以選擇精細的還原點。

|===


== 資料庫外掛程式的備份排程

備份頻率（排程類型）是在原則中指定、備份排程則是在資源群組組態中指定。決定備份頻率或排程的最關鍵因素是資源的變更率和資料的重要性。您可以每小時備份大量使用的資源、而每天備份一次極少使用的資源。其他因素包括資源對貴組織的重要性、服務層級協議（SLA）、以及您的恢復點目標（RPO）。

SLA定義預期的服務層級、並解決許多與服務相關的問題、包括服務的可用度和效能。RPO定義了檔案的存留期策略、這些檔案必須從備份儲存設備中恢復、以便在故障後恢復正常作業。SLA和RPO有助於資料保護策略。

即使是使用頻繁的資源、也不需要一天執行一次或兩次以上的完整備份。例如、定期交易記錄備份可能足以確保您擁有所需的備份。備份資料庫的頻率越高、SnapCenter 還原時所需使用的交易記錄就越少、還原作業的速度就越快。

備份排程分為兩部分、如下所示：

* 備份頻率
+
備份頻率（執行備份的頻率）、對於某些外掛程式稱為_schedule類型_、是原則組態的一部分。您可以選取每小時、每日、每週或每月作為原則的備份頻率。如果您未選取任何頻率、則所建立的原則為「隨需」原則。您可以按一下*設定*>*原則*來存取原則。

* 備份排程
+
備份排程（準確是在何時執行備份）是資源群組組態的一部分。例如、如果您的資源群組已設定每週備份的原則、您可以設定每週四下午10：00進行備份的排程。您可以按一下*資源*>*資源群組*來存取資源群組排程。





== 資料庫所需的備份工作數

決定所需備份工作數目的因素包括資源大小、使用的磁碟區數目、資源變更率、以及服務層級協議（SLA）。



== 備份命名慣例

您可以使用預設的Snapshot複本命名慣例、也可以使用自訂的命名慣例。預設的備份命名慣例會在Snapshot複本名稱中新增時間戳記、協助您識別複本的建立時間。

Snapshot複本使用下列預設命名慣例：

"resourceGroupname_hostname_timestamp"

您應該以邏輯方式命名備份資源群組、如下列範例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在此範例中、語法元素具有下列意義：

* _dbs1_是資源群組名稱。
* _mach1x88_是主機名稱。
* _03-12-2015_23.17.26_是日期和時間戳記。


或者、您也可以選取*使用Snapshot COPY*的自訂名稱格式、以指定Snapshot複本名稱格式、同時保護資源或資源群組。例如、customtext資源群組原則主機名稱或資源群組主機名稱。根據預設、時間戳記尾碼會新增至Snapshot複本名稱。



== 備份保留選項

您可以選擇保留備份複本的天數、或指定您要保留的備份複本數量、最多ONTAP 255份。例如、貴組織可能需要保留10天的備份複本或130個備份複本。

建立原則時、您可以指定備份類型和排程類型的保留選項。

如果您設定SnapMirror複寫、保留原則就會鏡射到目的地磁碟區。

還原刪除保留的備份、這些備份的保留標籤與排程類型相符。SnapCenter如果變更了資源或資源群組的排程類型、則使用舊排程類型標籤的備份仍可能保留在系統上。


NOTE: 若要長期保留備份複本、您應該使用SnapVault 此功能進行備份。



== 在Exchange Server的來源儲存磁碟區上保留交易記錄備份的時間

適用於Microsoft Exchange Server的還原外掛程式需要交易記錄備份、才能執行最新的還原作業、將資料庫還原至兩次完整備份之間的一段時間。SnapCenter

例如、如果Exchange外掛程式在上午8：00進行完整的交易記錄備份另一個完整加上交易記錄備份則可在下午5：00、使用最新的交易記錄備份、將資料庫還原至上午8：00之間的任何時間下午5：00如果交易記錄無法使用、則Exchange外掛程式只能執行時間點還原作業、將資料庫還原至Exchange外掛程式完成完整備份的時間。

一般而言、您只需要一兩天的最新還原作業。根據預設SnapCenter 、不超過兩天的情況下、將會保留不超過2天的時間。
