---
permalink: protect-sce/task_add_hosts_and_install_plug_in_for_exchange.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用SnapCenterAdd Host頁面來新增Windows主機。Exchange外掛程式會自動安裝在指定的主機上。這是安裝外掛程式的建議方法。您可以為個別主機或叢集新增主機並安裝外掛程式。 
---
= 新增主機並安裝Exchange外掛程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SnapCenter 「更新主機」頁面來新增Windows主機。Exchange外掛程式會自動安裝在指定的主機上。這是安裝外掛程式的建議方法。您可以為個別主機或叢集新增主機並安裝外掛程式。

*您需要的是什麼*

* 您必須是指派給角色的使用者、且該角色具有外掛程式安裝和解除安裝權限、例如SnapCenter 「支援支援支援中心」
* 在Windows主機上安裝外掛程式時、如果您指定的認證不是內建的、或是使用者屬於本機工作群組使用者、則必須停用主機上的UAC.
* 訊息佇列服務必須執行中。
* 如果您使用群組託管服務帳戶（GMSA）、則應該使用管理權限來設定GMSA。如需相關資訊、請參閱link:task_configure_gMSA_on_windows_server_2012_or_later.html["在適用於Microsoft Exchange Server的Windows Server 2012或更新版本上設定群組託管服務帳戶"^]。


*關於此工作*

* 您無法將SnapCenter 某個支援服務器作為外掛主機新增至另SnapCenter 一個支援服務器。
* 您可以為個別主機或叢集新增主機並安裝外掛程式套件。
* 如果Exchange節點是DAG的一部分、您就無法將一個節點只新增至SnapCenter 該伺服器。
* 如果您要在叢集（Exchange DAG）上安裝外掛程式、即使部分節點在NetApp LUN上沒有資料庫、也會將外掛程式安裝在叢集的所有節點上。


從支援多租戶的支援功能支援到支援功能的支援功能、您可以使用下列方法來新增主機：SnapCenter

|===
| 新增主機作業 | 4.5及更早版本 | 4.6及更新版本 


| 在跨網域或不同網域中新增無IP DAG | 不支援 | 支援 


| 新增多個IP DAG、其名稱為唯一名稱、位於相同或跨網域中 | 支援 | 支援 


| 在跨網域中新增多個具有相同主機名稱和/或DB名稱的IP或無IP DAG | 不支援 | 支援 


| 新增多個名稱相同且跨網域的無IP DAG | 不支援 | 支援 


| 新增多個具有相同名稱和跨網域的獨立主機 | 不支援 | 支援 
|===
Exchange的外掛程式取決SnapCenter 於適用於Windows的包裹、且版本必須相同。在Exchange外掛程式安裝期間、SnapCenter 依預設會選取適用於Windows的功能不全的外掛程式套件、並與VSS硬體供應商一起安裝。

如果SnapManager 已經SnapDrive 安裝適用於Microsoft Exchange Server和適用於Windows的功能、 而且您想要在同一個Exchange Server上安裝外掛程式、必須取消登錄SnapDrive 由Windows版的VSS硬體供應商、因為它與隨Windows版Exchange和SnapCenter 更新外掛程式套件一起安裝的VSS硬體供應商不相容。如需詳細資訊、請參閱 https://["如何手動登錄Data ONTAP 《SolidvVSS Hardware Provider》"]。

*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 驗證頂端是否已選取*受管理的主機*。
. 按一下「 * 新增 * 」。
. 在「hosts」頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
主機類型
 a| 
選擇* Windows *作為主機類型。

如果尚未安裝外掛程式、則支援使用者可在主機上新增主機、然後安裝外掛程式for Windows和外掛程式for Exchange。SnapCenter

適用於Windows的外掛程式和適用於Exchange的外掛程式必須是相同版本。如果先前安裝的是不同版本的Windows外掛程式、SnapCenter 則會在安裝過程中更新版本。



 a| 
主機名稱
 a| 
輸入主機的完整網域名稱（FQDN）或IP位址。

取決於DNS的正確組態。SnapCenter因此、最佳做法是輸入完整網域名稱（FQDN）。

只有當不受信任的網域主機解析為FQDN時、才支援IP位址。

如果您要使用SnapCenter 支援功能來新增主機、而且主機是子網域的一部分、則必須提供FQDN。

您可以輸入下列其中一項的IP位址或FQDN：

** 獨立式主機
** Exchange DAG
+
對於Exchange DAG、您可以：

+
*** 提供DAG名稱、DAG IP位址、節點名稱或節點IP位址、以新增DAG。
*** 提供其中一個DAG叢集節點的IP位址或FQDN、即可新增無IP DAG叢集。
*** 新增位於同一個網域或不同網域的IP less DAG。您也可以新增多個名稱相同但網域不同的不含IP的DAG。





NOTE: 對於獨立主機或Exchange DAG（跨網域或相同網域）、建議提供主機或DAG的FQDN或IP位址。



 a| 
認證資料
 a| 
選取您建立的認證名稱、或建立新認證資料。

認證資料必須具有遠端主機的管理權限。如需詳細資訊、請參閱建立認證的相關資訊。

您可以將游標放在指定的認證名稱上、以檢視認證資料的詳細資料。


NOTE: 認證驗證模式取決於您在「新增主機」精靈中指定的主機類型。

|===
. 在選取要安裝的外掛程式區段中、選取要安裝的外掛程式。
+
當您選取Exchange的外掛程式時、SnapCenter 會自動取消選取適用於Microsoft SQL Server的支援功能。Microsoft建議不要將SQL Server和Exchange伺服器安裝在同一個系統上、因為Exchange所使用的記憶體容量和其他資源使用量。

. （可選）單擊*更多選項*。
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
連接埠
 a| 
保留預設連接埠號碼或指定連接埠號碼。

預設連接埠號碼為8145。如果SnapCenter 將該伺服器安裝在自訂連接埠上、該連接埠編號將會顯示為預設連接埠。


NOTE: 如果您手動安裝外掛程式並指定自訂連接埠、則必須指定相同的連接埠。否則、作業將會失敗。



 a| 
安裝路徑
 a| 
預設路徑為「C:\Program Files\NetApp\SnapCenter」。

您可以選擇性地自訂路徑。



 a| 
新增DAG中的所有主機
 a| 
當您新增DAG時、請選取此核取方塊。



 a| 
跳過預先安裝檢查
 a| 
如果您已手動安裝外掛程式、但不想驗證主機是否符合安裝外掛程式的需求、請選取此核取方塊。



 a| 
使用群組託管服務帳戶（GMSA）來執行外掛程式服務
 a| 
如果您要使用群組託管服務帳戶（GMSA）來執行外掛程式服務、請選取此核取方塊。

請以下列格式提供GMSA名稱：_domainName\accountName$_。


NOTE: GMSA僅會做為SnapCenter Windows版的更新外掛程式服務的登入服務帳戶。

|===
. 按一下*提交*。
+
如果您尚未選取「跳過預先檢查」核取方塊、系統會驗證主機是否符合安裝外掛程式的需求。如果不符合最低要求、則會顯示適當的錯誤或警告訊息。

+
如果錯誤與磁碟空間或RAM有關、您可以更新位於「C:\Program Files\NetApp\SnapCenter' webapp」的Web.config檔案、以修改預設值。如果錯誤與其他參數有關、您必須修正問題。

+

NOTE: 在HA設定中、如果您要更新web.config檔案、則必須更新兩個節點上的檔案。

. 監控安裝進度。

