---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 使用認證資料驗證使用者執行的不中斷作業。SnapCenter SnapCenter您應該建立認證、以安裝外掛程式套件和其他認證資料、以便在資料庫上執行資料保護作業。 
---
= 設定SnapCenter 適用於Windows的驗證外掛程式認證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用認證資料驗證使用者執行的不中斷作業。SnapCenter SnapCenter您應該建立認證、以安裝外掛程式套件和其他認證資料、以便在資料庫上執行資料保護作業。

.關於這項工作
您必須設定認證、才能在Windows主機上安裝外掛程式。雖然您可以在部署主機和安裝外掛程式之後建立Windows認證、但最佳做法是在新增SVM之後建立認證、然後再部署主機和安裝外掛程式。

以系統管理員權限設定認證、包括遠端主機的系統管理員權限。

如果您為個別資源群組設定認證、但使用者名稱沒有完整的管理權限、則必須至少將資源群組和備份權限指派給使用者名稱。

.步驟
. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下「*認證*」。
. 按一下「*新增*」。
+
隨即顯示認證視窗。

. 在「認證」頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
認證名稱
 a| 
輸入認證的名稱。



 a| 
使用者名稱
 a| 
輸入用於驗證的使用者名稱。

** 網域管理員或系統管理員群組的任何成員
+
在您要安裝SnapCenter 此插件的系統上、指定網域管理員或任何系統管理員群組成員。「使用者名稱」欄位的有效格式為：

+
*** 「netbios\使用者名稱」
*** 「主FQDN \使用者名稱」


** 本機管理員（僅適用於工作群組）
+
對於屬於工作群組的系統、請在安裝SnapCenter 此插件的系統上指定內建的本機管理員。如果使用者帳戶擁有較高的權限、或主機系統上的使用者存取控制功能已停用、您可以指定屬於本機系統管理員群組的本機使用者帳戶。「使用者名稱」欄位的有效格式為：「UserName」（使用者名稱）





 a| 
密碼
 a| 
輸入用於驗證的密碼。



 a| 
驗證
 a| 
選取Windows作為驗證模式。

|===
. 按一下「*確定*」。

