---
settings:
  name: SnapCenter Software 4.9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '4.9'
    url: "/snapcenter"
  - version-number: '4.8'
    url: "/snapcenter-48"
  - version-number: '4.7'
    url: "/snapcenter-47"
  - version-number: '4.6'
    url: "/snapcenter-46"
  - version-number: '4.5'
    url: "/snapcenter-45"
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: SnapCenter 軟體 4.9 文件
    url: "/index.html"
  - title: 版本資訊
    url: "/release-notes.html"
  - section: concept
  - section: install
  - section: protect-scsql
  - section: protect-hana
  - section: protect-sco
  - section: protect-scw
  - section: protect-sce
  - section: protect-scc
  - section: admin
  - section: upgrade
  - section: uninstall
  - section: sc-automation
  - title: 法律聲明
    url: "/legal-notices.html"
