---
permalink: protect-scw/concept_snapcenter_plug_in_for_windows_features.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Windows外掛程式與儲存系統上的NetApp Snapshot複本技術整合。若要使用Windows外掛程式、您可以使用SnapCenter 這個介面。 
---
= 適用於Windows功能的插件SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows外掛程式與儲存系統上的NetApp Snapshot複本技術整合。若要使用Windows外掛程式、您可以使用SnapCenter 這個介面。

適用於Windows的外掛程式包含下列主要功能：

* *統一化圖形化使用者介面、採用SnapCenter S基 準*技術
+
透過這個支援介面、您可以在外掛程式和環境之間實現標準化和一致性。SnapCenter利用此支援介面、您可以跨外掛程式完成一致的備份與還原程序、使用集中式報告、使用概覽儀表板檢視、設定角色型存取控制（RBAC）、以及監控所有外掛程式的工作。SnapCenter此外、還提供集中化的排程與原則管理功能、以支援備份與複製作業。SnapCenter

* *自動化中央管理*
+
您可以排程例行檔案系統備份、設定原則型備份保留、以及設定還原作業。您也可以透過設定SnapCenter 以傳送電子郵件警示的功能、主動監控檔案系統環境。

* *不中斷營運的NetApp Snapshot複製技術*
+
Windows外掛程式使用NetApp Snapshot複製技術。這可讓您在數秒內備份檔案系統、並快速還原檔案、而無需讓主機離線。Snapshot複本所耗用的儲存空間最小。



除了這些主要功能之外、適用於Windows的外掛程式還提供下列優點：

* 備份、還原及複製工作流程支援
* RBAC支援的安全性與集中式角色委派
* 使用NetApp FlexClone技術建立生產檔案系統的空間效率複本、以供測試或資料擷取之用
+
如需FlexClone授權資訊、請參閱 link:../install/concept_snapcenter_licenses.html["不需要授權SnapCenter"^]。

* 能夠在多個伺服器上同時執行多個備份
* PowerShell Cmdlet可執行備份、還原及複製作業的指令碼
* 支援檔案系統與虛擬機器磁碟（VMDK）的備份
* 支援實體與虛擬化基礎架構
* 支援iSCSI、Fibre Channel、FCoE、原始裝置對應（RDM）、非對稱LUN對應（ALM）、VMDK over NFS和VMFS、以及虛擬FC

