---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: 在安裝Windows外掛程式之前、您應該瞭解某些安裝需求。 
---
= 適用於Microsoft Windows的安裝需求SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安裝Windows外掛程式之前、您應該瞭解某些安裝需求。

開始使用Windows外掛程式之前SnapCenter 、管理員必須先安裝及設定SnapCenter VMware Server、並執行必要的工作。

* 您必須擁有SnapCenter for Windows外掛程式的管理員權限才能安裝。
+
這個職務必須具有管理員權限。SnapCenter

* 您必須已安裝並設定SnapCenter 了此伺服器。
* 在Windows主機上安裝外掛程式時、如果您指定的認證不是內建的、或是使用者屬於本機工作群組使用者、則必須停用主機上的UAC.
* 如果您想要備份複寫、則必須設定SnapMirror和SnapVault SnapMirror。




== 安裝SnapCenter 適用於Windows的功能性外掛程式套件的主機需求

在安裝SnapCenter 適用於Windows的整套解決方案之前、您應該先熟悉一些基本的主機系統空間需求和規模調整需求。

|===
| 項目 | 需求 


 a| 
作業系統
 a| 
Microsoft Windows

如需支援版本的最新資訊，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 互通性對照表工具"^]。

如果您使用的是 Windows 叢集設置，您還應該安裝和設定 Windows 遠端管理 (WinRM)。



 a| 
主機上安裝的不需使用的RAM SnapCenter
 a| 
1 GB



 a| 
主機上安裝及記錄SnapCenter 插件的最低空間
 a| 
5 GB


NOTE: 您應該配置足夠的磁碟空間、並監控logs資料夾的儲存使用量。所需的記錄空間會因受保護的實體數量和資料保護作業的頻率而有所不同。如果沒有足夠的磁碟空間、將不會針對最近執行的作業建立記錄。



 a| 
必要的軟體套件
 a| 
* ASP.NET Core Runtime 8.0.12 （以及所有後續 8.0.x 修補程式）代管產品組合
* PowerShell Core 7.4.2


如需支援版本的最新資訊，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 互通性對照表工具"^]。

如需 .NET 特定疑難排解資訊、請參閱 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["無法升級或安裝不適用於沒有網際網路連線的舊系統。SnapCenter"]

|===


== 設定適用於Windows的外掛程式認證

使用認證資料驗證使用者執行的不中斷作業。SnapCenter SnapCenter您應該建立認證、以安裝SnapCenter 更新程式、以及在Windows檔案系統上執行資料保護作業的其他認證資料。

*您需要的是什麼*

* 您必須先設定Windows認證、才能安裝外掛程式。
* 您必須在遠端主機上設定具有系統管理員權限（包括系統管理員權限）的認證。
* 如果您為個別資源群組設定認證、但使用者沒有完整的管理權限、則必須至少將資源群組和備份權限指派給使用者。


*步驟*

. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下「*認證*」。
. 按一下「*新增*」。
. 在「認證」頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
認證名稱
 a| 
輸入認證的名稱。



 a| 
使用者名稱/密碼
 a| 
輸入用於驗證的使用者名稱和密碼。

** 網域管理員或系統管理員群組的任何成員
+
在您要安裝SnapCenter 此插件的系統上、指定網域管理員或任何系統管理員群組成員。「使用者名稱」欄位的有效格式如下：

+
*** 「netbios\使用者名稱」
*** 「主FQDN \使用者名稱」
*** 《username@UPN》


** 本機管理員（僅適用於工作群組）
+
對於屬於工作群組的系統、請在安裝SnapCenter 此插件的系統上指定內建的本機管理員。如果使用者帳戶擁有較高的權限、或主機系統上的使用者存取控制功能已停用、您可以指定屬於本機系統管理員群組的本機使用者帳戶。使用者名稱欄位的有效格式如下：「UserName」（使用者名稱）

+
請勿在密碼中使用雙引號（"）或反引號（"）。請勿使用小於（<）和驚嘆號（！） 密碼中的符號。例如、lessthan<!10、lessthan10<!、backtick'12。





 a| 
密碼
 a| 
輸入用於驗證的密碼。

|===
. 按一下「*確定*」。
+
完成認證設定之後、您可能會想要在「使用者與存取」頁面上、將認證維護指派給使用者或使用者群組。





== 在Windows Server 2016或更新版本上設定GMSA

Windows Server 2016或更新版本可讓您建立群組託管服務帳戶（GMSA）、以便從託管網域帳戶提供自動化服務帳戶密碼管理。

.開始之前
* 您應該擁有Windows Server 2016或更新版本的網域控制器。
* 您應該擁有Windows Server 2016或更新版本的主機、該主機是網域的成員。


.步驟
. 建立KDS根金鑰、為GMSA中的每個物件產生唯一的密碼。
. 對於每個網域、請從Windows網域控制器執行下列命令：add-KDSRootKey -EffectiveImmedia
. 建立及設定GMSA：
+
.. 以下列格式建立使用者群組帳戶：
+
 domainName\accountName$
.. 新增電腦物件至群組。
.. 使用您剛建立的使用者群組來建立GMSA。
+
例如、

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. 執行「Get-ADServiceAccount」命令來驗證服務帳戶。


. 在主機上設定GMSA：
+
.. 在您要使用GMSA帳戶的主機上啟用Windows PowerShell的Active Directory模組。
+
若要這麼做、請從PowerShell執行下列命令：

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. 重新啟動主機。
.. 從PowerShell命令提示字元執行下列命令、在主機上安裝GMSA：「Install-AdServiceAccount <GMSA >」
.. 執行下列命令驗證您的GMSA帳戶：「Test-AdServiceAccount <GMSA >」


. 將管理權限指派給主機上已設定的GMSA。
. 在SnapCenter 支援服務器中指定已設定的GMSA帳戶、以新增Windows主機。
+
在安裝外掛程式的過程中、將會在主機上安裝所選的外掛程式、並使用指定的GMSA作為服務登入帳戶。SnapCenter


