---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: 您可以使用SnapCenter 支援功能來複製Windows檔案系統備份。如果您想要刪除或變更錯誤的單一檔案複本、可以複製備份、並在複本中存取該檔案。 
---
= 從Windows檔案系統備份複製
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SnapCenter 支援功能來複製Windows檔案系統備份。如果您想要刪除或變更錯誤的單一檔案複本、可以複製備份、並在複本中存取該檔案。

.開始之前
* 您應該已完成新增主機、識別資源及建立儲存虛擬機器（SVM）連線等工作、準備好保護資料。
* 您應該備份檔案系統。
* 您應確保託管磁碟區的集合體應位於儲存虛擬機器（SVM）的指派集合體清單中。
* 您無法複製資源群組。您只能複製個別的檔案系統備份。
* 如果備份位於具有VMDK磁碟的虛SnapCenter 擬機器上、則無法將備份複製到實體伺服器。
* 如果您複製Windows叢集（例如、共享LUN或叢集共享Volume（CSV）LUN）、則該複本會儲存為指定主機上的專屬LUN。
* 對於複製作業、磁碟區掛載點的根目錄不能是共享目錄。
* 您無法在非集合體主節點的節點上建立實體複本。
* 您無法排程Windows檔案系統的循環複製（複製生命週期）作業、只能隨需複製備份。
* 如果您將包含複製的LUN移至新的Volume、SnapCenter 則無法再支援該複製。例如SnapCenter 、您無法使用不禁用功能刪除該實體複本。
* 您無法跨環境複製。例如、從實體磁碟複製到虛擬磁碟、反之亦然。


.關於這項工作
* 可使用外掛主機SMCoreServiceHost.exe.Config檔案中的PredefinedWindows指令碼目錄金鑰來定義指令碼路徑。
+
如有需要、您可以變更此路徑並重新啟動SMcore服務。建議您使用預設的安全路徑。

+
金鑰的值可透過API：API /4.7/configsettings從交換器顯示

+
您可以使用Get API來顯示金鑰的值。不支援Set API。

* 對於 ONTAP 9.12.1 及更低版本、從 SnapLock 資料保險箱 Snapshot 複本建立的複本作為還原的一部分、將會繼承 SnapLock 資料保險箱到期時間。儲存管理員應在 SnapLock 到期後手動清理複本。


.步驟
. 在左導覽窗格中、按一下*資源*、然後從清單中選取適當的外掛程式。
. 在「資源」頁面中、從清單中選取*檔案系統*。
. 選取主機。
+
如果資源受到保護、則會自動顯示拓撲檢視。

. 從資源清單中選取您要複製的備份、然後按一下複製圖示。
. 在「選項」頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
Clone伺服器
 a| 
選擇應在其上建立複本的主機。



 a| 
「自動指派掛載點」或「自動指派路徑下的磁碟區掛載點」
 a| 
選擇是否要在路徑下自動指派掛載點或磁碟區掛載點。

在路徑下自動指派磁碟區掛載點：路徑下的掛載點可讓您提供要在其中建立掛載點的特定目錄。在選擇此選項之前、您必須先確認目錄是空的。如果目錄中有備份、則在掛載作業之後、備份將處於無效狀態。



 a| 
歸檔位置
 a| 
如果您要複製次要備份、請選擇歸檔位置。

|===
. 在「指令碼」頁面中、指定您要執行的任何預先編寫或後製指令碼。
+

NOTE: 預先編寫或後製指令碼路徑不應包含磁碟機或共用區。路徑應相對於指令碼路徑。

. 檢閱摘要、然後按一下「*完成*」。
. 按一下*監控*>*工作*來監控作業進度。

