---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: 在建立備份之前定義備份策略、可提供您成功還原或複製檔案系統所需的備份。您的服務層級協議（SLA）、恢復時間目標（RTO）和恢復點目標（RPO）、都是您備份策略的主要決定因素。 
---
= 定義Windows檔案系統的備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在建立備份之前定義備份策略、可提供您成功還原或複製檔案系統所需的備份。您的服務層級協議（SLA）、恢復時間目標（RTO）和恢復點目標（RPO）、都是您備份策略的主要決定因素。

SLA定義預期的服務層級、並解決許多與服務相關的問題、包括服務的可用度和效能。RTO是指在服務中斷後、必須還原業務程序的時間。RPO定義了檔案的存留期策略、這些檔案必須從備份儲存設備中恢復、以便在故障後恢復正常作業。SLA、RTO及RPO有助於資料保護策略。



== Windows檔案系統的備份排程

備份頻率是在原則中指定；備份排程是在資源群組組態中指定。決定備份頻率或排程的最關鍵因素是資源的變更率和資料的重要性。您可以每小時備份大量使用的資源、而每天備份一次極少使用的資源。其他因素包括資源對貴組織的重要性、服務層級協議（SLA）、以及您的恢復點目標（RPO）。

SLA定義預期的服務層級、並解決許多與服務相關的問題、包括服務的可用度和效能。RPO定義了檔案的存留期策略、這些檔案必須從備份儲存設備中恢復、以便在故障後恢復正常作業。SLA和RPO有助於資料保護策略。

即使是使用頻繁的資源、也不需要一天執行一次或兩次以上的完整備份。

備份排程分為兩部分、如下所示：

* 備份頻率
+
備份頻率（執行備份的頻率）、對於某些外掛程式稱為_schedule類型_、是原則組態的一部分。例如、您可以將備份頻率設定為每小時、每日、每週或每月、或是指定*無*、讓原則成為隨需原則。您可以按一下*設定*>*原則*來存取原則。

* 備份排程
+
備份排程（準確是在何時執行備份）是資源群組組態的一部分。例如、如果您的資源群組已設定每週備份的原則、您可以設定每週四下午10：00進行備份的排程。您可以按一下*資源*>*資源群組*來存取資源群組排程。





== Windows檔案系統所需的備份數量

決定所需備份數量的因素包括Windows檔案系統的大小、使用的磁碟區數目、檔案系統變更率、以及您的服務層級協議（SLA）。



== Windows檔案系統的備份命名慣例

Windows 檔案系統備份使用預設的 Snapshot 命名慣例。預設備份命名慣例會在 Snapshot 名稱中新增時間戳記、協助您識別複本建立的時間。

Snapshot 使用下列預設命名慣例： resourcegroupname_hostname_timestamp

您應該以邏輯方式命名備份資源群組、如下列範例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在此範例中、語法元素具有下列意義：

* 「DTS1」是資源群組名稱。
* 主機名稱為「每個1個88」。
* 「2016年3月12日至23月17日」是日期和時間戳記。


建立備份時、您也可以新增描述性標記來協助識別備份。相反地、如果您想要使用自訂的備份命名慣例、則必須在備份作業完成後重新命名備份。



== 備份保留選項

您可以選擇保留備份複本的天數、或指定您要保留的備份複本數量、最多ONTAP 255份。例如、貴組織可能需要保留10天的備份複本或130個備份複本。

建立原則時、您可以指定備份類型和排程類型的保留選項。

如果您設定SnapMirror複寫、保留原則就會鏡射到目的地磁碟區。

還原刪除保留的備份、這些備份的保留標籤與排程類型相符。SnapCenter如果變更了資源或資源群組的排程類型、則使用舊排程類型標籤的備份仍可能保留在系統上。


NOTE: 若要長期保留備份複本、您應該使用SnapVault 此功能進行備份。
