---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: 您可以先建立新的資源備份原則、再使用SnapCenter 支援功能來備份Windows檔案系統、也可以在建立資源群組時或備份資源時建立新的備份原則。 
---
= 為Windows檔案系統建立備份原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以先建立新的資源備份原則、再使用SnapCenter 支援功能來備份Windows檔案系統、也可以在建立資源群組時或備份資源時建立新的備份原則。

.開始之前
* 您必須已定義備份策略。 link:task_define_a_backup_strategy_for_windows_file_systems.html["深入瞭解"^]
* 您必須做好資料保護準備。
+
若要準備資料保護、您必須完成安裝SnapCenter 、新增主機、探索資源、以及建立儲存虛擬機器（SVM）連線等工作。

* 如果您要將Snapshot複本複製到鏡射或保存庫二線儲存設備、SnapCenter 則該管理員必須已將來源和目的地磁碟區的SVM指派給您。
* 如果您想以預先編寫和後指令碼執行PowerShell指令碼、則應在web.config檔案中將usePowerShellProcessforScripts參數的值設為true。
+
預設值為假

* 對於 SnapMirror Business Continuity （ SM-BC ）、如需先決條件和限制的詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror 業務持續運作的物件限制"]。


.關於這項工作
* 可使用外掛主機SMCoreServiceHost.exe.Config檔案中的PredefinedWindows指令碼目錄金鑰來定義指令碼路徑。
+
如有需要、您可以變更此路徑並重新啟動SMcore服務。建議您使用預設的安全路徑。

+
金鑰的值可透過API：API /4.7/configsettings從交換器顯示

+
您可以使用Get API來顯示金鑰的值。不支援Set API。

* SnapLock
+
** 如果選取「保留特定天數的備份複本」選項、則 SnapLock 保留期間必須小於或等於所述保留天數。
** 指定 Snapshot 複本鎖定期間可防止在保留期間到期之前刪除 Snapshot 複本。這可能會導致保留的 Snapshot 複本數量超過原則中指定的數量。
** 對於 ONTAP 9.12.1 及更低版本、從 SnapLock 資料保險箱 Snapshot 複本建立的複本作為還原的一部分、將會繼承 SnapLock 資料保險箱到期時間。儲存管理員應在 SnapLock 到期後手動清理複本。





NOTE: 主要 SnapLock 設定是在 SnapCenter 備份原則中管理、次要 SnapLock 設定則是由 ONTAP 管理。

.步驟
. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下*原則*。
. 若要判斷您是否可以使用現有原則、請選取原則名稱、然後按一下*詳細資料*。
+
檢閱現有原則之後、您可以執行下列其中一項：

+
** 使用現有原則。
** 複製現有原則並修改原則組態。
** 建立新原則。


. 若要建立新原則、請按一下「*新增*」。
. 在「名稱」頁面中、輸入原則名稱和說明。
. 在「備份選項」頁面中、執行下列工作：
+
.. 選取備份設定。
+
|===
| 選項 | 說明 


 a| 
檔案系統一致的備份
 a| 
如果您想SnapCenter 要在備份作業開始之前、先停止檔案系統所在的磁碟機、然後在備份作業結束後繼續執行磁碟機作業、請選擇此選項。



 a| 
檔案系統損毀一致的備份
 a| 
如果您不想SnapCenter 讓檔案系統所在的磁碟機靜止、請選擇此選項。

|===
.. 選取排程頻率（也稱為原則類型）。
+
原則僅指定備份頻率。備份的特定保護排程是在資源群組中定義。因此、兩個或多個資源群組可以共用相同的原則和備份頻率、但備份排程不同。

+

NOTE: 如果您排定在上午2：00、則在夏令時間（Dst）期間不會觸發排程。



. 在「保留」頁面上、針對您所選的每個排程頻率、指定隨需備份的保留設定。
+
|===
| 選項 | 說明 


 a| 
要保留的Snapshot複本總數
 a| 
如果您想在SnapCenter 自動刪除Snapshot複本之前、先指定Snapshot複本的數量、請選擇此選項。



 a| 
刪除舊於的Snapshot複本
 a| 
如果您要指定SnapCenter 刪除備份複本之前保留備份複本的天數、請選擇此選項。



 a| 
Snapshot 複本鎖定期間
 a| 
選取 Snapshot 複本鎖定期間、然後選取天、月或年。

SnapLock 保留期應少於 100 年。

|===
+

IMPORTANT: 您應將保留計數設為2或更高。保留計數的最小值為2。

+

NOTE: 對於使用率為1018的ONTAP 資源、如使用率為0、9.4或更新版本、ONTAP 而使用率為254的資源、如使用率為0、9.3或更新版本。如果保留設定的值高於基礎ONTAP 版支援的值、則備份將會失敗。

. 在「複寫」頁面中、指定複寫至次要儲存系統：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
*在建立本機Snapshot複本之後更新SnapMirror *
 a| 
選取此選項可在另一個磁碟區（SnapMirror）上建立備份集的鏡射複本。

應啟用此選項以實現 SnapMirror Business Continuity （ SM-BC ）。

在次要複寫期間、 SnapLock 到期時間會載入主要 SnapLock 到期時間。按一下「拓撲」頁面中的 * 重新整理 * 按鈕、即可重新整理從 ONTAP 擷取的次要和主要 SnapLock 到期時間。

請參閱 link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["在「拓撲」頁面中檢視相關的備份與複本"]。



 a| 
建立Snapshot複本後再更新SnapVault
 a| 
選取此選項以執行磁碟對磁碟備份複寫。

在次要複寫期間、 SnapLock 到期時間會載入主要 SnapLock 到期時間。按一下「拓撲」頁面中的「重新整理」按鈕、即可重新整理從 ONTAP 擷取的次要和主要 SnapLock 到期時間。

當 SnapLock 僅在 SnapLock 資料保險箱的次要 ONTAP 上設定時、按一下「拓撲」頁面中的「重新整理」按鈕、即可重新整理從 ONTAP 擷取的次要鎖定期間。

如需 SnapLock Vault 的詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["將Snapshot複本提交至保存目的地上的WORM"]



 a| 
次要原則標籤
 a| 
選取Snapshot標籤。

根據您選取的Snapshot複本標籤、ONTAP 將套用符合標籤的次要Snapshot複本保留原則。


NOTE: 如果您在建立本機Snapshot複本之後選擇*更新SnapMirror、您可以選擇性地指定次要原則標籤。不過、如果SnapVault 您在建立本機Snapshot複本*之後選擇*更新SUpdate、則應指定次要原則標籤。



 a| 
重試次數錯誤
 a| 
輸入在程序停止之前應進行的複寫嘗試次數。

|===
+

NOTE: 您應該在ONTAP 適用於二線儲存設備的SnapMirror保留原則中進行設定、以避免達到二線儲存設備上Snapshot複本的上限。

. 在「指令碼」頁面中、分別輸入您希望SnapCenter 在備份作業之前或之後執行的指令碼或指令碼路徑、以及SnapCenter 在逾時之前等候指令碼執行的時間限制。
+
例如、您可以執行指令碼來更新SNMP設陷、自動化警示及傳送記錄。

+

NOTE: 預先編寫或後製指令碼路徑不應包含磁碟機或共用區。路徑應相對於指令碼路徑。

. 檢閱摘要、然後按一下「*完成*」。

