---
permalink: concept/concept_disaster_recovery.html 
sidebar: sidebar 
keywords: Disaster Recovery 
summary: 如果發生資源毀損或伺服器當機等災難、您可以SnapCenter 使用SnapCenter 「還原災難恢復」功能來還原此伺服器。 
---
= SnapCenter 災難恢復
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SnapCenter 災難恢復（ DR ）功能、在發生資源毀損或伺服器損毀等災難時恢復 SnapCenter 伺服器。您可以恢復SnapCenter 不中斷的儲存庫、伺服器排程和伺服器組態元件。您也可以恢復SnapCenter 適用於SQL Server的支援功能、SnapCenter 以及適用於SQL Server儲存設備的支援功能。

本節說明 SnapCenter 中的兩種災難恢復（ DR ）類型：

.SnapCenter 伺服器災難恢復
* SnapCenter 伺服器資料已備份、可在不新增任何外掛程式或由 SnapCenter 伺服器管理的情況下進行還原。
* 次要SnapCenter 版的伺服器應安裝在相同的安裝目錄中、並與主SnapCenter 版的SURL伺服器安裝在同一個連接埠上。
* 針對多因素驗證（ MFA ）、請在 SnapCenter 伺服器 DR 期間、關閉所有瀏覽器索引標籤、然後重新開啟瀏覽器、再次登入。這會清除現有或作用中的工作階段 Cookie 、並更新正確的組態資料。
* 支援災難恢復功能、使用REST API來備份功能。SnapCenter SnapCenter請參閱 link:../sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html["REST API工作流程、可用於SnapCenter 支援還原至支援的伺服器災難恢復"]。
* 與稽核設定相關的組態檔不會備份在DR備份中、也不會在還原作業之後備份在DR伺服器上。您應該手動重複稽核記錄設定。


.SnapCenter 外掛程式與儲存災難恢復
DR僅支援SnapCenter SQL Server的不支援的程式。當適用於SQL Server的解決方案不正常時、請切換至其他SQL主機、然後執行幾個步驟來恢復資料。SnapCenter請參閱 link:../protect-scsql/task_disaster_recovery_scsql.html["SQL Server適用的支援功能SnapCenter"]。

使用支援支援的SnapMirror技術來複寫資料。SnapCenter ONTAP它可用於將資料複寫至次要站台以進行災難恢復、並保持同步。故障切換可透過中斷SnapMirror中的複寫關係來啟動。在容錯回復期間、可以反轉同步處理、並將DR站台的資料複寫回主要位置。
