---
permalink: concept/reference_data_security.html 
sidebar: sidebar 
keywords: security,authentication, CA certificates 
summary: 利用嚴苛的安全性與驗證功能、確保資料安全無虞。SnapCenter 
---
= 安全功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用嚴苛的安全性與驗證功能、確保資料安全無虞。SnapCenter

包含下列安全功能：SnapCenter

* 所有與SnapCenter 之通訊均使用HTTP over SSL（HTTPS）。
* 支援使用進階加密標準（AES）加密來保護所有的認證資料SnapCenter 。
* 使用符合聯邦資訊處理標準（FIPS）的安全演算法。SnapCenter
* 支援使用客戶提供的授權CA憑證。SnapCenter
* SnapCenter 4.1.1 或更新版本支援傳輸層安全性（ TLS ） 1.2 以與 ONTAP 通訊。您也可以使用 TLS 1.2 在用戶端和伺服器之間進行通訊。
+
從 5.0 開始、 SnapCenter 支援（ TLS ） 1.3 與 ONTAP 通訊。

* 支援一組SSL密碼套件、以提供跨網路通訊的安全性。SnapCenter
+
如需詳細資訊、請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["如何設定支援的SSL加密套件"]。

* 系統會在貴公司的防火牆內安裝支援功能、以便存取該伺服器、並可在該伺服器與外掛程式之間進行通訊。SnapCenter SnapCenter SnapCenter
* 支援使用AES加密的Token、24小時後即過期。SnapCenter
* 利用Windows Active Directory整合的功能、可控制存取權限的登入和角色型存取控制（RBAC）SnapCenter 。
* Windows SnapCenter 和Linux主機機器的支援以支援使用支援VMware的功能ONTAP 。 https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["深入瞭解"]。
* 可保護工作階段安全的指令程式。SnapCenter
* 預設的閒置時間為15分鐘後SnapCenter 、此功能會警告您5分鐘內就會登出。若無活動20分鐘、SnapCenter 則會將您登出、您必須重新登入。您可以修改登出期間。
* 登入嘗試不正確5次以上後、登入功能會暫時停用。
* 支援SnapCenter 在伺服器和ONTAP 功能區之間進行CA認證驗證。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["深入瞭解"]。
* 完整性驗證器會新增至SnapCenter 支援服務器和外掛程式、並在全新安裝和升級作業期間驗證所有隨附的二進位檔案。




== CA憑證總覽

安裝過程中、支援集中式SSL憑證。SnapCenter為了加強伺服器與外掛程式之間的安全通訊、SnapCenter 支援使用客戶提供的授權CA憑證。

您應該在安裝SnapCenter 完Sing Server和個別外掛程式之後、再部署CA憑證。如需詳細資訊、請參閱 link:../install/reference_generate_CA_certificate_CSR_file.html["產生CA認證CSR檔案"]。

您也可以部署適用於SnapCenter VMware vSphere的VMware vSphere的VMware認證外掛程式。如需更多資訊、請參閱 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["建立及匯入憑證"^]。



== 雙向 SSL 通訊

雙向 SSL 通訊可保護 SnapCenter 伺服器與外掛程式之間的相互通訊。



== 憑證型驗證概觀

憑證型驗證可驗證嘗試存取 SnapCenter 外掛主機之個別使用者的真實性。使用者應匯出不含私密金鑰的 SnapCenter 伺服器憑證、並將其匯入外掛程式主機信任存放區。只有啟用雙向 SSL 功能時、憑證型驗證才會生效。



== 多因素驗證（MFA）

MFA使用第三方身分識別供應商（IDP）透過安全聲明標記語言（SAML）來管理使用者工作階段。此功能可選擇使用多種因素、例如TOTP、生物辨識、推入通知等、以及現有的使用者名稱和密碼、藉此強化驗證安全性。此外、它也能讓客戶使用自己的使用者身分識別供應商、在整個產品組合中取得統一化的使用者登入（SSO）。

MFA僅適用於SnapCenter 驗證伺服器UI登入。登入會透過IDP Active Directory Federation Services（AD FS）進行驗證。您可以在AD FS設定各種驗證因素。供應服務的供應商應該將效能分析設定為AD FS中的依賴方。SnapCenter SnapCenter若要啟用MFA的SnapCenter 功能、您需要AD FS中繼資料。

如需啟用MFA的資訊、請參閱 link:../install/enable_multifactor_authentication.html["啟用多因素驗證"]。
