---
permalink: concept/reference_data_security.html 
sidebar: sidebar 
keywords: security,authentication, CA certificates 
summary: 利用嚴苛的安全性與驗證功能、確保資料安全無虞。SnapCenter 
---
= 安全功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用嚴苛的安全性與驗證功能、確保資料安全無虞。SnapCenter

包含下列安全功能：SnapCenter

* 所有與SnapCenter 之通訊均使用HTTP over SSL（HTTPS）。
* 支援使用進階加密標準（AES）加密來保護所有的認證資料SnapCenter 。
* 使用符合聯邦資訊處理標準（FIPS）的安全演算法。SnapCenter
* 支援使用客戶提供的授權CA憑證。SnapCenter
* 支援傳輸層安全性（TLS）1.2與支援的通訊範圍包括：SnapCenter ONTAP您也可以在用戶端和伺服器之間使用TLS 1.2通訊。
* 系統會在貴公司的防火牆內安裝支援功能、以便存取該伺服器、並可在該伺服器與外掛程式之間進行通訊。SnapCenter SnapCenter SnapCenter
* 支援使用AES加密的Token、24小時後即過期。SnapCenter
* 利用Windows Active Directory整合的功能、可控制存取權限的登入和角色型存取控制（RBAC）SnapCenter 。
* 可保護工作階段安全的指令程式。SnapCenter
* 預設的閒置時間為15分鐘後SnapCenter 、此功能會警告您5分鐘內就會登出。若無活動20分鐘、SnapCenter 則會將您登出、您必須重新登入。您可以修改登出期間。
* 登入嘗試不正確5次以上後、登入功能會暫時停用。




== CA憑證總覽

安裝過程中、支援集中式SSL憑證。SnapCenter為了加強伺服器與外掛程式之間的安全通訊、SnapCenter 支援使用客戶提供的授權CA憑證。

您應該在安裝SnapCenter 完Sing Server和個別外掛程式之後、再部署CA憑證。如需詳細資訊、請參閱 link:../install/reference_generate_CA_certificate_CSR_file.html["產生CA認證CSR檔案"^]。

您也可以部署適用於SnapCenter VMware vSphere的VMware vSphere的VMware認證外掛程式。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#create-and-import-certificates["建立及匯入憑證"^]。
