---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 新增主機並安裝外掛程式套件之前、您必須先完成所有需求。SAP HANA資料庫的支援套件可在Windows和Linux環境中使用。SnapCenter 
---
= 新增主機及安裝SnapCenter 適用於SAP HANA資料庫的功能性外掛程式的先決條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增主機並安裝外掛程式套件之前、您必須先完成所有需求。SAP HANA資料庫的支援套件可在Windows和Linux環境中使用。SnapCenter

* 您必須在主機上安裝Java 1.8 64位元。
+

NOTE: 不支援IBM Java。

* 您必須在主機上安裝SAP HANA資料庫互動終端機（HDBSQL用戶端）。
* 對於Windows、外掛程式Creator Service應使用「'LocalSystem'」Windows使用者執行、這是以網域管理員身分安裝SAP HANA資料庫外掛程式時的預設行為。
* 對於Windows、應以系統使用者身分建立使用者儲存金鑰。
* 在Windows主機上安裝外掛程式時、如果您指定的認證不是內建的、或是使用者屬於本機工作群組使用者、則必須停用主機上的UAC.適用於Microsoft Windows的SAP外掛程式預設會與SAP HANA外掛程式一起部署於Windows主機上。SnapCenter
* 對於Linux主機、HDB Secure User Store金鑰會以HDBSQL OS使用者的身分存取。
* 支援SAP HANA資料庫主機的支援應可存取8145或外掛程式的自訂連接埠。SnapCenter




== Windows主機

* 您必須擁有具有本機系統管理員權限的網域使用者、並在遠端主機上具有本機登入權限。
* 在Windows主機上安裝SAP HANA資料庫外掛程式時SnapCenter 、會自動安裝適用於Microsoft Windows的整套外掛程式。
* 您必須為root或非root使用者啟用密碼型SSH連線。
* 您必須在Windows主機上安裝Java 1.8 64位元。
+
http://www.java.com/en/download/manual.jsp["適用於所有作業系統的Java下載"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["NetApp 互通性對照表工具"]





== Linux主機

* 您必須為root或非root使用者啟用密碼型SSH連線。
* 您必須在Linux主機上安裝Java 1.8 64位元。
+
http://www.java.com/en/download/manual.jsp["適用於所有作業系統的Java下載"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["NetApp 互通性對照表工具"]

* 對於在Linux主機上執行的SAP HANA資料庫、在安裝SAP HANA資料庫外掛程式時SnapCenter 、會自動安裝適用於UNIX的整套外掛程式。
* 您應該將 * bash* 作為外掛程式安裝的預設 Shell 。




== 補充命令

若要在 SnapCenter Plug-in for SAP HANA 上執行補充命令、您必須將其包含在中 `allowed_commands.config` 檔案：

`allowed_commands.config` 檔案位於 SnapCenter Plug-in for SAP HANA 目錄的「 etc 」子目錄中。

.Windows主機
預設： `C:\Program Files\NetApp\SnapCenter\HANA\etc\allowed_commands.config`

自訂路徑： `<Custome_Directory>\NetApp\SnapCenter\HANA\etc\allowed_commands.config`
Windows 主機：

.Linux主機
預設： `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

自訂路徑： `<Custome_Directory>/NetApp/snapcenter/scc/etc/allowed_commands.config`

若要允許在外掛主機上執行補充命令、請開啟 `allowed_commands.config` 編輯器中的檔案。在單獨的行中輸入每個命令。它不區分大小寫。
例如、

命令： mount

命令： umount

請務必指定完整路徑名稱。如果路徑名稱包含空格、請以引號（ " ）括住路徑名稱。
例如、

命令： "C:\Program Files\NetApp\SnapCreator commands\sdcli.exe"

命令： myscript.bat

如果是 `allowed_commands.config` 檔案不存在、命令或指令碼執行將遭到封鎖、工作流程將失敗並顯示下列錯誤：

"[/mnt/mount -a] 不允許執行。在外掛程式主機上的檔案 %s 中新增命令以進行授權。 "

如果命令或指令碼未出現在中 `allowed_commands.config`、命令或指令碼執行將會遭到封鎖、工作流程將會失敗、並顯示下列錯誤：

"[/mnt/mount -a] 不允許執行。在外掛程式主機上的檔案 %s 中新增命令以進行授權。 "


NOTE: 您不應使用萬用字元項目（ * ）來允許所有命令。
