---
permalink: protect-scc/create_policies_for_custom_plug_in_resources.html 
sidebar: sidebar 
keywords: create policies, custom plug-in 
summary: 在使用SnapCenter 支援功能來備份自訂外掛程式特定資源之前、您必須先為要備份的資源或資源群組建立備份原則。 
---
= 建立自訂外掛程式資源的原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter 支援功能來備份自訂外掛程式特定資源之前、您必須先為要備份的資源或資源群組建立備份原則。

.開始之前
* 您應該已經定義備份策略。
+
如需詳細資訊、請參閱定義自訂外掛程式資料保護策略的相關資訊。

* 您應該已做好資料保護準備。
+
資料保護的準備工作包括安裝SnapCenter 功能、新增主機、建立儲存系統連線、以及新增資源等工作。

* 儲存虛擬機器（SVM）應指派給您進行鏡射或保存庫作業。
+
如果您要將快照複製到鏡射或資料保險箱、 SnapCenter 管理員必須將來源和目的地磁碟區的 SVM 指派給您。

* 您應該已經手動新增要保護的資源。


.關於這項工作
* 備份原則是一組規則、可管理您管理、排程及保留備份的方式。此外、您也可以指定複寫、指令碼及應用程式設定。
* 在原則中指定選項可節省您想要重複使用其他資源群組原則的時間。
* SnapLock
+
** 如果選取「保留特定天數的備份複本」選項、則 SnapLock 保留期間必須小於或等於所述保留天數。
** 指定 Snapshot 鎖定期間可防止在保留期間到期之前刪除 Snapshot 。這可能會導致保留的快照數量超過原則中指定的數量。
** 對於 ONTAP 9.12.1 及更低版本、從 SnapLock 資料保險箱快照建立的複本作為還原的一部分、將會繼承 SnapLock 資料保險箱到期時間。儲存管理員應在 SnapLock 到期後手動清理複本。




.步驟
. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下*原則*。
. 按一下「*新增*」。
. 在「名稱」頁面中，輸入原則名稱和詳細資料。
. 在「原則類型」頁面中、執行下列步驟：
+
.. 選擇儲存類型。
.. 在「自訂備份設定」區段中，提供必須以金鑰值格式傳遞至外掛程式的任何特定備份設定。
+
您可以提供多個金鑰值來傳遞給外掛程式。



. 在「 Snapshot and Replication 」（快照與複寫）頁面中，執行下列步驟：
+
.. 選取*隨選*、*每小時*、*每日*、*每週*或*每月*、以指定排程類型。
+

NOTE: 您可以在建立資源群組時、指定備份作業的排程（開始日期、結束日期和頻率）。這可讓您建立共用相同原則和備份頻率的資源群組、但可讓您為每個原則指派不同的備份排程。

+

NOTE: 如果您排定在上午2：00、則在夏令時間（Dst）期間不會觸發排程。

.. 在 Snapshot settings （快照設定）區段中，指定備份類型的保留設定，以及在 * Backup Type* （備份類型 * ）頁面中選取的排程類型：
+
|===
| 如果您想要... | 然後... 


 a| 
保留一定數量的快照
 a| 
選取 * 要保留的複本 * ，然後指定要保留的快照數。

如果快照數量超過指定數量、則會先刪除最舊的複本、然後刪除快照。


NOTE: 如果您打算啟用SnapVault 此功能、則必須將保留數設為2或更高。如果將保留計數設為 1 、則保留作業可能會失敗、因為第一個 Snapshot 是 SnapVault 關係的參考 Snapshot 、直到較新的 Snapshot 複寫到目標為止。


NOTE: 最大保留值為 1018 。如果保留設定的值高於基礎ONTAP 版支援的值、則備份將會失敗。



 a| 
將快照保留一定天數
 a| 
選取 * 保留複本 * ，然後指定您要保留快照的天數，再將其刪除。



 a| 
主要快照複本鎖定期間
 a| 
選取 Snapshot 鎖定期間、然後選取天、月或年。

SnapLock 保留期應少於 100 年。



 a| 
次 Snapshot 複本鎖定期間
 a| 
選取 * 次快照複本鎖定期間 * ，然後選取天，月或年。

|===
.. 選取Snapshot標籤。
+
根據您選取的 Snapshot 標籤、 ONTAP 會套用符合標籤的次要 Snapshot 保留原則。

+

NOTE: 如果您在建立本機Snapshot複本之後選擇*更新SnapMirror、您可以選擇性地指定次要原則標籤。不過、如果SnapVault 您在建立本機Snapshot複本*之後選擇*更新SUpdate、則應指定次要原則標籤。



. 在 [ 選取次要複寫選項 ] 區段中，選取下列其中一個或兩個次要複寫選項：
+

NOTE: 您必須為 * 次快照複本鎖定期間 * 選取次要複寫選項，才能生效。

+
|===
| 針對此欄位... | 執行此動作... 


 a| 
*在建立本機Snapshot複本之後更新SnapMirror *
 a| 
選取此欄位可在另一個磁碟區（SnapMirror複寫）上建立備份集的鏡射複本。

如果 ONTAP 中的保護關係類型為鏡射和資料保險箱、且您只選取此選項、則在主要節點上建立的 Snapshot 不會傳輸至目的地、但會列在目的地中。如果從目的地選取此 Snapshot 以執行還原作業、則會顯示下列錯誤訊息：次要位置無法用於所選的保存 / 鏡射備份。

在次要複寫期間、 SnapLock 到期時間會載入主要 SnapLock 到期時間。

按一下「拓撲」頁面中的 * 重新整理 * 按鈕、即可重新整理從 ONTAP 擷取的次要和主要 SnapLock 到期時間。

請參閱。 link:view_custom_plug_in_resource_backups_and_clones_in_the_topology_page.html["在「拓撲」頁面中檢視自訂外掛程式資源相關備份與複製"]



 a| 
* SnapVault 在建立本機Snapshot複本之後更新此功能*
 a| 
選取此選項以執行磁碟對磁碟備份複寫（SnapVault 還原備份）。

在次要複寫期間、 SnapLock 到期時間會載入主要 SnapLock 到期時間。按一下「拓撲」頁面中的 * 重新整理 * 按鈕、即可重新整理從 ONTAP 擷取的次要和主要 SnapLock 到期時間。

當 SnapLock 僅在「 SnapLock 資料保險箱」的次要 ONTAP 上設定時、按一下「拓撲」頁面中的「 * 重新整理 * 」按鈕、即可重新整理從 ONTAP 擷取的次要裝置上的鎖定期間。

如需 SnapLock 資料保險箱的詳細資訊、請參閱在資料保險箱上將快照提交至 WORM
目的地

請參閱。 link:view_custom_plug_in_resource_backups_and_clones_in_the_topology_page.html["在「拓撲」頁面中檢視自訂外掛程式資源相關備份與複製"]



 a| 
*錯誤重試次數*
 a| 
輸入作業停止前可允許的最大複寫嘗試次數。

|===
+

NOTE: 您應該在 ONTAP 中為次要儲存設備設定 SnapMirror 保留原則、以避免達到次要儲存設備快照的上限。

. 檢閱摘要、然後按一下「*完成*」。

