---
permalink: protect-scc/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html 
sidebar: sidebar 
keywords: add hosts 
summary: 您必須使用SnapCenterAdd Host頁面來新增主機、然後安裝外掛程式套件。外掛程式會自動安裝在遠端主機上。您可以為個別主機或叢集新增主機並安裝外掛程式套件。 
---
= 新增主機並在遠端主機上安裝外掛程式套件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須使用SnapCenterAdd Host頁面來新增主機、然後安裝外掛程式套件。外掛程式會自動安裝在遠端主機上。您可以為個別主機或叢集新增主機並安裝外掛程式套件。

.開始之前
* 您應該是指派給角色的使用者、該角色具有外掛程式安裝和解除安裝權限、例如SnapCenter 「支援管理員」角色。
* 您應確保訊息佇列服務正在執行中。
* 如果您使用群組託管服務帳戶（GMSA）、則應該使用管理權限來設定GMSA。
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["在Windows Server 2012或更新版本上為自訂應用程式設定群組託管服務帳戶"]



.關於這項工作
您無法將SnapCenter 某個支援服務器作為外掛主機新增至另SnapCenter 一個支援服務器。

如果您在叢集（WSFC）上安裝外掛程式、則外掛程式會安裝在叢集的所有節點上。

.步驟
. 在左側導覽窗格中、選取*主機*。
. 驗證頂端是否已選取*託管主機*索引標籤。
. 選取*「Add*」。
. 在「hosts」（主機）頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
主機類型
 a| 
選取主機類型：

** Windows
** Linux



NOTE: 自訂外掛程式可在Windows和Linux環境中使用。



 a| 
主機名稱
 a| 
輸入主機的完整網域名稱（FQDN）或IP位址。

取決於DNS的正確組態。SnapCenter因此、最佳做法是輸入FQDN。

在Windows環境中、只有當不受信任的網域主機解析為FQDN時、才支援IP位址。

您可以輸入獨立主機的IP位址或FQDN。

如果您使用SnapCenter 支援功能來新增主機、而且主機是子網域的一部分、則必須提供FQDN。



 a| 
認證資料
 a| 
選取您建立的認證名稱、或建立新認證。

認證資料必須具有遠端主機的管理權限。如需詳細資訊、請參閱建立認證的相關資訊。

您可以將游標放在指定的認證名稱上、以檢視認證資料的詳細資料。


NOTE: 認證驗證模式取決於您在「新增主機」精靈中指定的主機類型。

|===
. 在*選取要安裝的外掛程式*區段中、選取要安裝的外掛程式。
. （可選）選擇 * 更多選項 * 。
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
連接埠
 a| 
保留預設連接埠號碼、或指定連接埠號碼。

預設連接埠號碼為8145。如果SnapCenter 將該伺服器安裝在自訂連接埠上、該連接埠編號將會顯示為預設連接埠。


NOTE: 如果您手動安裝外掛程式並指定自訂連接埠、則必須指定相同的連接埠。否則、作業將會失敗。



 a| 
安裝路徑
 a| 
自訂外掛程式可安裝在Windows系統或Linux系統上。

** 針對適用於Windows的「更新程式套件」、預設路徑為C:\Program Files\NetApp\SnapCenter。SnapCenter
+
您也可以自訂路徑。

** 對於 SnapCenter Plug-in 套件 for Linux 、預設路徑為 `/opt/NetApp/snapcenter`。
+
您也可以自訂路徑。

** 針對「不需要自訂的外掛程式」SnapCenter ：
+
... 在「自訂外掛程式」區段中、選取 * 瀏覽 * 、然後選取壓縮的自訂外掛程式資料夾。
+
壓縮資料夾包含自訂外掛程式碼和描述元.xml檔案。

+
若為儲存外掛程式、請瀏覽至 `_C:\ProgramData\NetApp\SnapCenter\Package Repository_` 然後選擇 `Storage.zip` 資料夾。

... 選取 * 上傳 * 。
+
壓縮自訂外掛程式資料夾中的描述元.xml檔案會在上傳套件之前驗證。

+
會列出上傳至SnapCenter Sfor the Sfor the Sfor the Server的自訂外掛程式。

+
如果您想要管理MySQL或DB2應用程式、可以使用NetApp提供的MySQL和DB2自訂外掛程式。MySQL和DB2自訂外掛程式可從取得 https://automationstore.netapp.com/home.shtml["NetApp Automation Store"]







 a| 
跳過預先安裝檢查
 a| 
如果您已手動安裝外掛程式、但不想驗證主機是否符合安裝外掛程式的需求、請選取此核取方塊。



 a| 
使用群組託管服務帳戶（GMSA）來執行外掛程式服務
 a| 
如果您想要使用群組託管服務帳戶（GMSA）來執行外掛程式服務、請針對Windows主機選取此核取方塊。


IMPORTANT: 請以下列格式提供GMSA名稱：domainname\accountName$。


NOTE: GMSA僅會做為SnapCenter Windows版的更新外掛程式服務的登入服務帳戶。

|===
. 選擇*提交*。
+
如果您尚未選取「*跳過預先檢查*」核取方塊、系統會驗證主機是否符合安裝外掛程式的需求。磁碟空間、RAM、PowerShell版本、.NET版本、位置（適用於Windows外掛程式）和Java版本（適用於Linux外掛程式）均已根據最低需求進行驗證。如果不符合最低要求、則會顯示適當的錯誤或警告訊息。

+
如果錯誤與磁碟空間或RAM有關、您可以更新位於C:\Program Files\NetApp\SnapCenter Webapp的Web.config檔案、以修改預設值。如果錯誤與其他參數有關、您必須修正問題。

+

NOTE: 在HA設定中、如果您要更新web.config檔案、則必須更新兩個節點上的檔案。

. 如果主機類型為 Linux 、請驗證指紋、然後選取 * 確認並提交 * 。
+

NOTE: 即使先前已將同一部主機新增至SnapCenter 更新版本、而且指紋已確認、指紋驗證也是必要的。

. 監控安裝進度。
+
安裝特定的記錄檔位於 `/custom_location/snapcenter/` 記錄。


