---
permalink: sc-automation/reference_supported_rest_apis.html 
sidebar: sidebar 
keywords: REST API categories 
summary: 透過「靜態API」提供的資源SnapCenter 會依照類別進行組織、如SnapCenter 「靜態API」文件頁所示。 
---
= 其他外掛程式支援REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過「靜態API」提供的資源SnapCenter 會依照類別進行組織、如SnapCenter 「靜態API」文件頁所示。以下是每個資源與基礎資源路徑的簡短說明、以及其他適當的使用考量。



== 驗證

您可以使用此API呼叫來登入SnapCenter 到這個伺服器。此API會傳回用於驗證後續要求的使用者授權權杖。



== 網域

您可以使用這些API呼叫來執行下列作業：

* 擷取所有網域
* 擷取特定網域的詳細資料
* 註冊或取消註冊網域
* 修改網域




== 工作

您可以使用這些API呼叫來執行下列作業：

* 擷取所有工作
* 擷取工作狀態
* 取消或停止工作




== 設定

您可以使用這些API呼叫來執行下列作業：

* 註冊、檢視、修改或移除認證
* 設定通知設定




== 主機

您可以使用這些API呼叫來執行下列作業：

* 擷取主機詳細資料
* 擷取已安裝的外掛程式及其資源詳細資料
* 新增、移除或修改外掛程式主機
* 安裝或升級外掛程式




== 資源

您可以使用這些API呼叫來執行下列作業：

* 擷取資源
* 建立、修改或移除資源
* 保護資源
* 備份、還原或複製資源




== 備份

您可以使用這些API呼叫來執行下列作業：

* 擷取備份詳細資料
* 重新命名或刪除備份




== 複製

您可以使用這些API呼叫來執行下列作業：

* 擷取實體複本詳細資料
* 刪除複本




== Clonesplit

您可以使用這些API呼叫來執行下列作業：

* 擷取實體複本分割作業的狀態
* 啟動或停止複本分割作業




== 資源群組

您可以使用這些API呼叫來執行下列作業：

* 擷取資源群組的詳細資料
* 建立、修改或刪除資源群組
* 備份資源群組




== 原則

您可以使用這些API呼叫來執行下列作業：

* 擷取原則詳細資料
* 建立、修改或刪除原則




== 儲存設備

您可以使用這些API呼叫來執行下列作業：

* 擷取儲存詳細資料
* 建立、修改或刪除儲存設備
* 探索儲存設備上的資源
* 在儲存設備上建立或刪除共用區




== 分享

您可以使用這些API呼叫來執行下列作業：

* 擷取共用區的詳細資料
* 在儲存設備上建立或刪除共用區




== 外掛程式

您可以使用這些API呼叫來擷取主機上的所有外掛程式、並執行不同的作業。



== 報告

您可以使用這些API呼叫來執行下列作業：

* 產生備份、還原、複製及外掛程式報告
* 新增、執行、刪除或修改排程




== 警示

您可以使用這些API呼叫來執行下列作業：

* 擷取所有警示
* 刪除警示




== RBAC

您可以使用這些API呼叫來執行下列作業：

* 擷取使用者、群組和角色的詳細資料
* 新增使用者
* 建立、修改或刪除角色
* 指派或取消指派角色和群組




== 組態

您可以使用這些API呼叫來執行下列作業：

* 檢視組態設定
* 修改組態設定




== 認證設定

您可以使用這些API呼叫來執行下列作業：

* 檢視憑證狀態
* 修改憑證設定




== 儲存庫

您可以使用這些API呼叫來執行下列作業：

* 備份及還原NSM儲存庫
* 保護及取消保護NSM儲存庫
* 容錯移轉
* 重新建置NSM儲存庫

