---
permalink: sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html 
sidebar: sidebar 
keywords:  
summary: 支援災難恢復功能、使用REST API來備份功能。SnapCenter SnapCenter 
---
= 災難恢復（DR）REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]


支援災難恢復（DR）功能、使用REST API來備份支援。SnapCenter SnapCenter在使用DR REST API之前、請先執行下列步驟。

*步驟*

. 建立新的伺服器災難恢復備份、SnapCenter 使用DR備份REST API從指定的伺服器災難恢復備份中還原一個R地 靜止伺服器： `/4.5/disasterrecovery/server/backup`
. 啟動次要伺服器機器、但SnapCenter 在次要伺服器上安裝完整套必要條件之前、您應該先完成這些先決條件。
+
** 替代伺服器主機名稱/主機FQDN應與主要伺服器主機名稱相同、但IP位址可能不同。
** 次要伺服器版本應與主要伺服器相同。
** 次要SnapCenter 版應該安裝在與主要版相同的位置和連接埠上。


. 在觸發伺服器DR還原作業之前、您應該先叫出災難恢復備份之後儲存的目標路徑或路徑。
+
** 請務必SnapCenter 使用下列命令、將DR備份檔案複製到新的支援服務器：
`xcopy <Ssource_Path> \\<Destination_Server_IP>\<Folder_Path> /O /X /E /H /K {ex : xcopy C:\DRBackup \\10.225.81.114\c$\DRBackup /O /X /E /H /K}`


. 在SnapCenter 次要機器上安裝此伺服器。
+
** 執行DR還原作業時、您應確保沒有任何與SnapCenter 該伺服器相關的工作正在執行。


. 將次要SnapCenter 的SURL伺服器安裝在與主要伺服器相同的位置和連接埠上。
+
** 使用DR還原API執行伺服器DR還原作業：  `/4.5/disasterrecovery/server/restore`
+
如果外掛程式無法解析伺服器主機名稱、請登入每個外掛程式主機、然後以<New IP> 「更新SC_SERVER_Name」格式新增新IP的etc/host項目。例如、 `10.225.81.35 SCServer1`

+
伺服器etc/host項目將不會還原。您可以從DR備份資料夾手動還原。






NOTE: 如果是使用F5設定、還原作業會以獨立執行、您應該執行一組命令來再次建立F5。請參閱連結： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Migrate_SnapCenter_migrate_to_another_Server["如何將SnapCenter 解決方法移轉至其他伺服器"^]


NOTE: 災難恢復還原之後、將會新增主機、但您應該手動安裝外掛程式。


NOTE: 只有當您安裝SnapCenter 適用於Windows的還原外掛程式、並將NetApp LUN附加至伺服器機器時、儲存庫備份排程才會還原。



== 支援REST API以進行SnapCenter 支援的REST伺服器災難恢復

使用REST API、您可以在REST API Swagger頁面上執行下列作業。如需存取Swagger頁面的資訊、請參閱 link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["如何使用Swagger API網頁存取REST API"]。

*您需要的是什麼*

* 您應該以SnapCenter 「管理員」使用者的身分登入。
* 應啟動並執行此伺服器SnapCenter 以執行DR還原API。


*關於此工作*

支援所有外掛程式的Sfor Server DR。SnapCenter

|===
| 說明 | REST API | HTTP方法 


 a| 
擷取現有SnapCenter 的伺服器DR備份


NOTE: 您應該提供儲存災難恢復備份的目標路徑。
 a| 
「/4.5/disstarrecovery / server/Backup」（伺服器/備份）「TarketPath={path}」（目標路徑=｛path｝）
 a| 
取得



 a| 
建立新的伺服器災難恢復備份。
 a| 
/4.5/dissterrecovery / server / Backup（伺服器/備份）
 a| 
貼文



 a| 
從SnapCenter 指定的伺服器災難恢復備份還原支援服務器。
 a| 
/4.5/dissterrecovery / server /還原
 a| 
貼文



 a| 
根據備份名稱刪除伺服器DR備份。
 a| 
（如：/4.5/dissterrecovery / server / Backup）
 a| 
刪除



 a| 
啟用或停用儲存災難恢復
 a| 
/4.5/dissterrecovery /儲存設備
 a| 
貼文

|===
如需詳細資訊、請參閱 https://www.youtube.com/watch?v=Nbr_wm9Cnd4&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["災難恢復API"^] 影片：
