---
permalink: protect-azure/install-snapcenter-azure-virtual-machine.html 
sidebar: sidebar 
keywords: snapcenter server, azure virtual machine, install 
summary: 在 Azure 虛擬機器上下載並安裝 SnapCenter 。 
---
= 在 Azure 虛擬機器上安裝 SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從 NetApp 支援網站 下載 SnapCenter 軟體、並在 Azure 虛擬機器上安裝軟體。

.開始之前
確保 Azure Windows 虛擬機器符合 SnapCenter 伺服器安裝需求。如需相關資訊、請參閱 link:../install/reference_domain_and_workgroup_requirements.html["準備安裝SnapCenter 完此伺服器"]。

.步驟
. 請SnapCenter 從下載《停止更新》安裝套件 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 支援網站"]。
. 連按兩下下載的.exe檔案、即可啟動SnapCenter 安裝程式。
+
在您開始安裝之後、系統會執行所有預先檢查、如果不符合最低要求、則會顯示適當的錯誤或警告訊息。您可以忽略警告訊息並繼續安裝、但錯誤應予以修正。

. 檢閱SnapCenter 安裝此功能所需的預先填入值、並視需要進行修改。
+
您不需要指定MySQL Server儲存庫資料庫的密碼。在安裝過程中、會自動產生密碼。SnapCenter

+

NOTE: 儲存庫資料庫的自訂路徑不支援特殊字元「 % 」。如果您在路徑中加入「%」、安裝將會失敗。

. 按一下*立即安裝*。
+
如果您已指定任何無效的值、將會顯示適當的錯誤訊息。您應該重新輸入值、然後開始安裝。

+

NOTE: 如果您按一下「*取消*」按鈕、將會完成正在執行的步驟、然後開始復原作業。將從主機中完全移除該伺服器。SnapCenter

+
不過、如果SnapCenter 您在執行「停止伺SnapCenter 服器站台重新啟動」或「等待伺服器啟動」作業時按*「取消」、安裝作業將會繼續進行、而不會取消作業。


