---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords: Manage storage system 
summary: 新增儲存系統之後、您可以修改儲存系統組態和連線、或刪除儲存系統。 
---
= 管理儲存系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增儲存系統之後、您可以修改儲存系統組態和連線、或刪除儲存系統。



== 修改儲存系統組態

如果您想要變更使用者名稱、密碼、平台、連接埠、傳輸協定、SnapCenter 逾時期間、偏好的IP位址或訊息選項。

*關於此工作*

您可以修改個別使用者或群組的儲存連線。如果您屬於具有相同儲存系統權限的一或多個群組、則儲存連線名稱會在儲存連線清單中多次顯示、每個群組都會有一次儲存系統權限。

*步驟*

. 在左導覽窗格中、按一下*儲存系統*。
. 在「儲存系統」頁面的「*類型*」下拉式清單中、執行下列其中一項動作：
+
|===
| 選取... | 步驟... 


 a| 
SVM ONTAP
 a| 
可查看已添加的所有儲存虛擬機（SVM），以及修改所需的SVM組態。

.. 在「Storage Connections（儲存連線）」頁面中、按一下適當的SVM名稱。
.. 執行下列其中一項動作：
+
*** 如果SVM不是任何叢集的一部分、請在「修改儲存系統」頁面中修改使用者名稱、密碼、EMS及AutoSupport 更新設定、平台、傳輸協定、連接埠、逾時、 和偏好的IP。
*** 如果SVM是叢集的一部分、請在「Modify Storage System」（修改儲存系統）頁面中、選取* Manage SVM Independify*（管理SVM獨立）、然後修改使用者名稱、密碼、EMS和AutoSupport S還原 設定、平台、傳輸協定、連接埠、逾時、 和偏好的IP。
+
修改要獨立管理的SVM之後、如果您決定透過叢集管理SVM、您應該刪除SVM、然後按一下*重新探索*。SVM將會新增至ONTAP SVM叢集。

+

NOTE: 在更新儲存系統密碼SnapCenter 時、您應該重新啟動個別外掛程式或伺服器主機的SMCore服務、因為更新的密碼並未反映在SMCore中、而且備份工作將會失敗、並顯示錯誤的認證錯誤。







 a| 
叢集ONTAP
 a| 
可查看所有已添加的羣集並修改所需的羣集配置。

.. 在「Storage Connections（儲存連線）」頁面中、按一下叢集名稱。
.. 在「Modify Storage System（修改儲存系統）」頁面中、按一下「Username（使用者名稱）」旁的編輯圖示、然後修改使用者名稱和密碼。
.. 選取或清除EMS和AutoSupport EISO設定。
.. 按一下*「更多選項」*、然後修改其他組態、例如平台、傳輸協定、連接埠、逾時和偏好的IP。


|===
. 按一下*提交*。




== 刪除儲存系統

您可以使用SnapCenter 功能表來刪除任何未使用的儲存系統。

*關於此工作*

您可以刪除個別使用者或群組的儲存連線。如果您屬於具有相同儲存系統權限的一或多個群組、則儲存系統名稱會在儲存連線清單中多次顯示、每個群組都會有一次儲存系統權限。


IMPORTANT: 刪除儲存系統時、在該儲存系統上執行的所有作業都會失敗。

*步驟*

. 在左導覽窗格中、按一下*儲存系統*。
. 在Storage Systems（儲存系統）頁面的* Type（類型）*下拉式清單中、選取* ONTAP 《SVMS*》（*）或* ONTAP 《叢集*》（*《叢集*》）。
. 在「Storage Connections（儲存連線）」頁面中、選取SVM旁邊的核取方塊、或是您要刪除的叢集。
+

NOTE: 您無法選取屬於叢集一部分的SVM。

. 按一下*刪除*。
. 在「刪除儲存系統連線設定」頁面中、按一下「*確定*」。
+

NOTE: 如果SVM是ONTAP 使用ONTAP 無法修復的GUI從叢集刪除、SnapCenter 請在BIOS GUI中按一下「*重新探索*」以更新SVM清單。





== REST API支援

根據預設，所有與 ONTAP 和 ASA R2 儲存系統的儲存連線都會透過 ZAPI 。REST API 可針對特定 ONTAP 版本啟用。

您可以修改下列組態檔案中的組態金鑰：

* IsRestEnabledForStorageConnection
+
預設值為假。

* MinOntapVersionToUseREST
+
預設值為 9.13.1 。



.透過 REST API 啟用連線
. 將 IsRestEnabledForStorageConnection 設置爲 true 。
. 在伺服器和 Windows 外掛程式主機上，新增 SMCoreServiceHost.dll.config 和 SnapDriveService.dll.config 中的金鑰。
+
<add key="IsRestEnabledForStorageConnection" value="true" />



.將透過 REST API 的連線限制為特定版本的 ONTAP
. 將組態參數 MinOntapVersionToUseREST 設定為 TRUE 。
. 在伺服器和 Windows 外掛程式主機上，新增 SMCoreServiceHost.dll.config 和 SnapDriveService.dll.config 中的金鑰。
+
<add key="MinOntapVersionToUseREST" value="9.13.1" />

. 重新啟動伺服器上的 SmCore 服務，以及外掛程式機器上的外掛程式和 SnapDrive 服務。

