---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords: Manage policies 
summary: 您可以從資源或資源群組分離原則、修改、刪除、檢視及複製。 
---
= 管理原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從資源或資源群組分離原則、修改、刪除、檢視及複製。



== 修改原則

當原則附加至資源或資源群組時、您可以修改複寫選項、Snapshot複本保留設定、錯誤重試次數或指令碼資訊。只有在分離原則之後、才能修改排程類型（頻率）。

*關於此工作*

修改原則中的排程類型需要額外的步驟、因為SnapCenter 只有在原則附加到資源或資源群組時、才能登錄排程類型。

|===
| 如果您想要... | 然後... 


 a| 
新增其他排程類型
 a| 
建立新原則、並將其附加至必要的資源或資源群組。

例如、如果資源群組原則只指定每小時備份、而您也想要新增每日備份、您可以建立具有每日排程類型的原則、並將其新增至資源群組。然後資源群組會有兩個原則：每小時和每天。



 a| 
移除或變更排程類型
 a| 
請執行下列步驟：

. 將原則從使用該原則的每個資源和資源群組中分離出來。
. 修改排程類型。
. 再次將原則附加至所有資源和資源群組。


例如、如果原則指定每小時備份、而您想要將其變更為每日備份、則必須先分離原則。

|===
*步驟*

. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下*原則*。
. 選取原則、然後按一下*修改*。
. 修改資訊、然後按一下「*完成*」。




== 分離原則

您可以隨時將原則從資源或資源群組中分離、而不再想讓這些原則管理資源的資料保護。您必須先中斷原則、才能刪除原則、或是修改排程類型。

*步驟*

. 在左導覽窗格中、按一下*資源*、然後從清單中選取適當的外掛程式。
. 在「資源」頁面中、從*檢視*清單中選取*資源群組*。
. 選取資源群組、然後按一下*修改資源群組*。
. 在「修改資源群組」精靈的「原則」頁面中、從下拉式清單中、清除您要分離的原則旁的核取標記。
. 在精靈的其餘部分中對資源群組進行任何其他修改、然後按一下「*完成*」。




== 刪除原則

如果不再需要原則、您可能會想要刪除這些原則。

.開始之前
如果原則與任何資源或資源群組相關聯、則應將原則從資源或資源群組中分離。

*步驟*

. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下*原則*。
. 選取原則、然後按一下*刪除*。
. 按一下「*是*」。

