---
permalink: admin/concept_manage_the_snapcenter_server_repository.html 
sidebar: sidebar 
keywords: SnapCenter Server 
summary: 有關從功能執行的各種操作的資訊SnapCenter 、會儲存在SnapCenter 功能性伺服器資料庫儲存庫中。您必須建立儲存庫的備份、以防止SnapCenter 資料遺失。 
---
= 管理SnapCenter 伺服器儲存庫
:allow-uri-read: 


[role="lead"]
有關從功能執行的各種操作的資訊SnapCenter 、會儲存在SnapCenter 功能性伺服器資料庫儲存庫中。您必須建立儲存庫的備份、以防止SnapCenter 資料遺失。

SnapCenter Server 儲存庫有時也被稱為 NSM 資料庫。有關所有可用 cmdlet 的詳細資訊，請參閱 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《軟件指令程式參考指南》SnapCenter"^]。



== 保護SnapCenter 知識庫的先決條件

您的環境必須符合保護SnapCenter 該資訊庫的特定先決條件。

* 管理儲存虛擬機器（SVM）連線
+
您應該設定儲存認證資料。

* 資源配置主機
+
至少一個NetApp儲存磁碟應該存在SnapCenter 於該系統資訊庫主機上。如果SnapCenter NetApp磁碟不存在於知識庫主機上、您必須建立一個。

+
如需新增主機、設定SVM連線及資源配置主機的詳細資訊、請參閱安裝指示。

* 配置iSCSI LUN或VMDK
+
對於高可用度（HA）組態、您可以在SnapCenter 任一部「支援服務器」中配置iSCSI LUN或VMDK。





== 備份SnapCenter 這個資訊庫

備份 SnapCenter Server 儲存庫有助於防止資料遺失。您可以透過執行  `Protect-SmRepository` cmdlet 來備份儲存庫。

.關於這項工作
 `Protect-SmRepository` cmdlet 執行下列任務：

* 建立資源群組和原則
* 為SnapCenter 這個資訊儲存庫建立備份排程


.步驟
. 啟動PowerShell。
. 在 SnapCenter Server 主機上，使用  `Open-SmConnection` cmdlet 建立工作階段，並輸入您的認證資料。
. 使用  `Protect-SmRepository` cmdlet 備份儲存庫，該 cmdlet 需要以下參數：
+
.. `-HostName (String)`：指定 SnapCenter 儲存庫所在伺服器的主機名稱。
.. `-Path (String)`：指定 NetApp 儲存系統上儲存儲存庫備份的檔案系統路徑。
.. `-Schedule (Hashtable)`：定義儲存庫備份的排程。它通常定義為雜湊表。
.. `-RetentionCount (Int32)`：指定要保留的儲存庫備份數量。當備份數量超過此值時，將刪除最舊的備份。






== 檢視SnapCenter 還原儲存庫的備份

您可以透過執行  `Get-SmRepositoryBackups` cmdlet 來顯示 SnapCenter Server 資料庫儲存庫備份清單。如需詳細資訊，請參閱 https://docs.netapp.com/us-en/snapcenter-cmdlets/Get-SmRepositoryBackups.html["SnapCenter Software Cmdlet 參考指南 - Get-SmRepositoryBackups"^]。

儲存庫備份是依照  `Protect-SmRepository` cmdlet 中指定的計畫建立的。

.步驟
. 啟動PowerShell。
. 從命令提示字元輸入  `Open-SmConnection` cmdlet、並提供認證資料以連線至 SnapCenter 伺服器。
. 使用  `Get-SmRepositoryBackups` cmdlet 列出所有可用的 SnapCenter 資料庫備份。




== 還原SnapCenter 還原還原資料庫儲存庫

您可以透過執行  `Restore-SmRepositoryBackup` cmdlet 來還原 SnapCenter 儲存庫。

還原 SnapCenter 儲存庫時，SnapCenter 正在執行的其他操作會受到影響，因為在還原作業期間無法存取儲存庫資料庫。

.步驟
. 啟動PowerShell。
. 從命令提示字元輸入  `Open-SmConnection` cmdlet、並提供認證資料以連線至 SnapCenter 伺服器。
. 使用  `Restore-SmRepositoryBackup` cmdlet 還原儲存庫備份。
+
下列Cmdlet可從SnapCenter iSCSI LUN或VMDK上現有的備份還原VMware資料庫儲存庫：

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445
----
+
下列Cmdlet會在SnapCenter iSCSI LUN中意外刪除備份檔案時、還原MySQL的功能。對於 VMDK ，請手動從 ONTAP 快照還原備份。

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445 -RestoreFileSystem
----



NOTE: 執行還原作業之後擷取儲存庫備份時、不會列出用來執行儲存庫還原作業的備份。



== 移轉SnapCenter 此系統資訊庫

您可以將SnapCenter 預設位置的還原伺服器資料庫儲存庫移轉到另一個磁碟。當您想要將儲存庫重新部署到空間較多的磁碟時、可以移轉儲存庫。

.步驟
. 在Windows中停止MySQL57服務。
. 找到MySQL資料目錄。
+
您通常可以在C：\ProgramData\MySQL\MySQL Server 5.7\Data找到資料目錄。

. 將MySQL資料目錄複製到新位置、例如E：\Data\NSM。
. 在新目錄上按一下滑鼠右鍵、然後選取「*內容*>*安全性*」、將「網路服務」本機伺服器帳戶新增至新目錄、然後指派帳戶完整控制權。
. 重新命名原始資料庫目錄、例如NSM_copy。
. 在Windows命令提示字元中、使用_mklink_命令建立符號目錄連結。
+
"mklink /d "C：\ProgramData\MySQL\MySQL Server 5.7\Data\NSM""E：\Data\NSM"""

. 在Windows中啟動MySQL57服務。
. 請登入SnapCenter 到還原並檢查儲存庫項目、或登入MySQL公用程式並連線至新儲存庫、以確認資料庫位置變更是否成功。
. 刪除原始、重新命名的資料庫儲存庫目錄（NSM_copy）。




== 重設SnapCenter 資訊儲存庫密碼

MySQL Server儲存庫資料庫密碼會在SnapCenter 從SnapCenter 還原4.2安裝時自動產生。這個自動產生的密碼在SnapCenter 任何時候都不知道。如果您要存取儲存庫資料庫、應重設密碼。

.開始之前
您應該擁有SnapCenter 管理員權限才能重設密碼。

.步驟
. 啟動PowerShell。
. 從命令提示字元輸入  `Open-SmConnection` cmdlet、並提供認證資料以連線至 SnapCenter 伺服器。
. 使用  `Set-SmRepositoryPassword` cmdlet 重設儲存庫密碼。
+
下列命令會重設儲存庫密碼：

+
[listing]
----

Set-SmRepositoryPassword at command pipeline position 1
Supply values for the following parameters:
NewPassword: ********
ConfirmPassword: ********
Successfully updated the MySQL server password.
----


.相關資訊
您可以透過執行 `Get-Help command_name`命令來取得有關 cmdlet 可用參數及其說明的資訊。或者，您可以參考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《軟件指令程式參考指南》SnapCenter"^]。
