---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords: SnapCenter reports 
summary: 提供各種報告選項、讓您監控及管理系統健全狀況和運作成功。SnapCenter 
---
= 概述功能SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
提供各種報告選項、讓您監控及管理系統健全狀況和運作成功。SnapCenter

|===
| 報告類型 | 說明 


 a| 
備份報告
 a| 
備份報告提供SnapCenter 有關您的支援環境的整體備份趨勢、備份成功率、以及在指定時間內執行的每個備份相關資訊。如果刪除備份、則報告不會顯示刪除備份的任何狀態資訊。備份詳細資料報告提供指定備份工作的詳細資訊、並列出已成功備份的資源和任何已失敗的資源。



 a| 
複製報告
 a| 
Clone Report（Clone報告）提供SnapCenter 有關您的支援環境的完整複製趨勢、複製成功率、以及指定時間內執行的每個複製工作相關資訊。如果刪除了複本、則報告不會顯示刪除複本的任何狀態資訊。Clone Detail Report（完整複製詳細資料報告）提供有關指定的實體複本、實體複製主機及實體複製工作狀態的詳細資料。如果工作失敗、「Clone Detail Report」（完整複製詳細資料報告）會顯示有關故障的資訊。



 a| 
還原報告
 a| 
還原報告提供還原工作的整體資訊。「還原詳細資料報告」提供有關指定還原工作的詳細資料、包括主機名稱、備份名稱、工作開始和持續時間、以及個別工作工作工作的狀態。如果工作失敗、「還原詳細資料報告」會顯示有關故障的資訊。



 a| 
保護報告
 a| 
這些報告提供所有SnapCenter 由所有的支援外掛程式執行個體所管理資源的保護詳細資料。此報告提供所有外掛程式執行個體所管理資源的保護詳細資料。您可以查看總覽、未受保護資源的詳細資料、產生報告時尚未備份的資源、備份作業失敗之資源群組的資源、SnapVault 以及不符合需求的狀態。



 a| 
排程報告
 a| 
這些報告排定定期執行、例如每日、每週或每月。報告會在指定的日期和時間自動產生、並透過電子郵件傳送給相關人員您可以啟用、停用、修改或刪除排程。按一下*立即執行*按鈕、即可隨需執行啟用的排程。系統管理員可以執行任何排程、但所產生的報告會根據建立排程的使用者所提供的權限、包含資料。

除了Administrator以外的任何其他使用者都能根據其權限查看或修改排程。如果在「新增角色」頁面中選取「所有成員都可以看到其他成員的物件」選項、則該角色的其他成員將能夠看到及修改。

|===


== 存取報告

您可以使用SnapCenter 「解決方案資訊儀表板」快速瞭解系統的健全狀況。您可以從儀表板深入瞭解更多詳細資料。或者、您也可以直接存取詳細報告。

您可以使用下列其中一種方法來存取報告：

* 在左側導覽窗格中、按一下*儀表板*、然後按一下*上次保護摘要*圓形圖、即可在「報告」頁面中查看更多詳細資料。
* 在左側導覽窗格中、按一下*報告*。




== 篩選您的報告

您可能會想要根據各種參數來篩選報告資料、視所需資訊的詳細程度和時間範圍而定。

*步驟*

. 在左側導覽窗格中、按一下*報告*。
. 如果未顯示參數檢視、請按一下報告工具列上的*切換參數區域*圖示。
. 指定您要執行報告的時間範圍。+如果您省略結束日期、則會擷取所有可用資訊。
. 根據下列任一條件篩選您的報告資訊：
+
** 資源群組
** 主機
** 原則
** 資源
** 狀態
** 外掛程式名稱


. 按一下「 * 套用 * 」。




== 匯出或列印報告

匯出SnapCenter 功能豐富的報告、讓您能夠以各種不同的替代格式檢視報告。您也可以列印報告。

*步驟*

. 在左側導覽窗格中、按一下*報告*。
. 在報告工具列中、執行下列其中一項：
+
** 按一下*切換預覽列印*圖示以預覽可列印的報告。
** 從*匯出*圖示下拉式清單中選取格式、以將報告匯出為替代格式。


. 若要列印報告、請按一下*列印*圖示。
. 若要檢視特定報告摘要、請捲動至報告的適當區段。




== 設定電子郵件通知的SMTP伺服器

您可以指定要用來傳送資料保護工作報告給自己或其他人的SMTP伺服器。您也可以傳送測試電子郵件來驗證組態。這些設定會全域套用至SnapCenter 您設定電子郵件通知的任何項目。

此選項可設定用於傳送所有資料保護工作報告的SMTP伺服器。不過、如果您想要定期SnapCenter 更新傳送給自己或其他人的特定資源的資料保護工作、以便監控這些更新的狀態、您可以設定選項、以便SnapCenter 在建立資源群組時、以電子郵件傳送該等報告。

*步驟*

. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下「*全域設定*」。
. 輸入SMTP伺服器、然後按一下*「Save*（儲存*）」。
. 若要傳送測試電子郵件、請輸入電子郵件寄件者及寄送對象的電子郵件地址、輸入主旨、然後按一下*傳送*。




== 設定電子郵件報告選項

如果您想要定期SnapCenter 將更新的資料保護工作傳送給自己或其他人、以便監控這些更新的狀態、您可以設定在SnapCenter 建立資源群組時、以電子郵件傳送該報告的選項。

.開始之前
您必須在「設定」下的「全域設定」頁面中設定您的SMTP伺服器。

*步驟*

. 在左導覽窗格中、按一下*資源*、然後從清單中選取適當的外掛程式。
. 選取您要檢視的資源類型、然後按一下「*新增資源群組*」、或選取現有的資源群組、然後按一下「*修改*」來設定現有資源群組的電子郵件報告。
. 在「新資源群組」精靈的「通知」面板中、從下拉式功能表中選取您要永遠接收報告、失敗報告或失敗報告或警告報告。
. 輸入電子郵件寄件者地址、電子郵件寄送地址及電子郵件主旨。

