---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: 從 SnapCenter 左側瀏覽窗格中、儀表板可讓您一覽系統的健全狀況、包括最近的工作活動、警示、保護摘要、儲存效率和使用量、 SnapCenter 工作的狀態（備份、複製、還原）、獨立式和 Windows 叢集主機的組態狀態、 由 SnapCenter 管理的儲存虛擬機器（ SVM ）數量、以及授權容量。 
---
= 儀表板總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儀表板可從SnapCenter 左側導覽窗格、讓您一覽系統的健全狀況、包括最近的工作活動、警示、保護摘要、儲存效率與使用率、SnapCenter 不中斷作業的狀態（備份、複製、還原）、獨立式和Windows叢集主機的組態狀態、 由VMware及授權容量管理的儲存虛擬機器（SVM）數量SnapCenter 。

儀表板檢視畫面中顯示的資訊取決於指派給目前登入SnapCenter 的使用者角色。如果使用者沒有檢視該資訊的權限、則部分內容可能不會顯示。

在許多情況下、您可以將游標停留在* I*上、以檢視更多有關顯示器的資訊。在某些情況下、儀表板顯示器中的資訊會連結SnapCenter 至資源、監控和報告等各個圖形使用者介面頁面中的詳細來源資訊。



== 最近的工作活動

「近期工作活動」方塊會顯示您可以存取之任何備份、還原及複製工作的最新工作活動。此顯示中的工作具有下列其中一種狀態：「已完成」、「警告」、「失敗」、「執行中」、「佇列中」、 和已取消。

將游標移到工作上可提供更多資訊。您可以按一下特定的工作號碼來檢視其他工作資訊、此號碼會將您重新導向至「監控」頁面。您可以從這裡取得工作詳細資料或記錄資訊、並產生該工作的特定報告。

按一下*「全部」*即可檢視所有SnapCenter 的不景工作的歷史記錄。



== 警示

警示區塊會顯示主機和SnapCenter 伺服器的最新未解決的「嚴重」和「警告」警示。

「嚴重」和「警告」類別警示的總數會顯示在畫面頂端。按一下「嚴重」或「警告」總計、會將您重新導向「警示」頁面、並在「警示」頁面中套用特定篩選條件。

按一下特定警示可將您重新導向至警示頁面、以取得該警示的詳細資料。按一下畫面底部的*查看全部*、即可將您重新導向至「警示」頁面、以取得所有警示的清單。



== 最新保護摘要

最新的「Protection Summary」（保護摘要）方塊可為您有權存取的所有實體提供保護狀態。依預設、顯示器會設定為提供所有外掛程式的狀態。狀態資訊是針對以Snapshot複本備份至一線儲存設備的資源、以及使用SnapMirror和SnapVault SnapMirror技術備份至二線儲存設備的資源。次要儲存設備的可用保護狀態資訊取決於所選的外掛程式類型。


NOTE: 如果您使用鏡射保存原則、保護摘要的計數器會顯示在SnapVault 「圖表」中、而非SnapMirror圖表中。

從下拉式功能表中選取外掛程式、即可取得個別外掛程式的保護狀態。環圈圖顯示所選外掛程式的受保護資源百分比。按一下環圈片會將您重新導向至「*報告*>*外掛程式*」頁面、該頁面提供指定外掛程式所有主要和次要儲存活動的詳細報告。


IMPORTANT: 關於二線儲存設備的報告SnapVault 僅適用於不支援SnapMirror報告。


NOTE: SAP HANA為Snapshot複本的主要和次要儲存設備提供保護狀態資訊。只有主要儲存保護狀態可用於檔案型備份。

|===
| 保護狀態 | 主儲存設備 | 二線儲存設備 


 a| 
失敗
 a| 
資源群組執行備份但備份失敗的資源群組實體數。
 a| 
備份無法傳輸至次要目的地的實體數。



 a| 
成功
 a| 
資源群組中已成功備份資源群組的實體數。
 a| 
已成功傳輸至次要目的地的備份實體數。



 a| 
未設定
 a| 
不屬於任何資源群組且尚未備份的實體數。
 a| 
屬於一或多個資源群組一部分、但未設定備份以傳輸至次要目的地的實體數。



 a| 
未初始化
 a| 
屬於資源群組一部分、但尚未執行備份的實體數。
 a| 
不適用。

|===

NOTE: 如果您使用SnapCenter 的是還原伺服器4.2和舊版外掛程式（4.2之前）來建立備份、則*最新的「保護摘要*」方塊不會顯示這些備份的SnapMirror保護狀態。



== 工作

「工作」並排顯示您可以存取的備份、還原及複製工作摘要。您可以使用下拉式功能表自訂任何報告的時間範圍。時間範圍選項固定在過去24小時、過去7天和過去30天。預設報告會顯示過去7天內執行的資料保護工作。

備份、還原及複製工作資訊會顯示在環圈圖中。按一下某個環圈區段、會將您重新導向至「監控」頁面、並將工作篩選器預先套用至選取範圍。

|===
| 工作狀態 | 說明 


 a| 
失敗
 a| 
失敗的工作數。



 a| 
警告
 a| 
發生錯誤的工作數。



 a| 
成功
 a| 
已成功完成的工作數。



 a| 
執行中
 a| 
目前執行中的工作數。

|===


== 儲存設備

Storage（儲存設備）方塊會顯示保護工作在90天內所耗用的主要和次要儲存設備、以圖形方式呈現使用趨勢、並計算主要儲存設備的節約效益。儲存資訊會在上午12點每24小時更新一次

每日使用量總計（包括SnapCenter 可用於各種版本的備份總數、以及這些備份所佔用的大小）將顯示在顯示器頂端。備份可能有多個與其相關聯的Snapshot複本、而且計數也會反映相同的情況。這適用於主要與次要Snapshot複本。例如、您已建立10個備份、其中2個因為原則型備份保留而刪除、1個備份則由您明確刪除。因此、會顯示7個備份數、以及這7個備份所佔用的大小。

一線儲存設備的儲存節約係數是邏輯容量（複製與Snapshot複本節約效益加上儲存設備消耗）與一線儲存設備實體容量的比率。長條圖說明儲存節約效益。

折線圖會在90天的循環期間、以每日為單位分別繪製一線和二線儲存使用量。將游標移到圖表上可提供詳細的每日結果。


NOTE: 如果您使用SnapCenter 還原伺服器4.2和舊版外掛程式（4.2之前）來建立備份、則「*儲存*」方塊不會顯示備份數量、這些備份所耗用的儲存空間、Snapshot節約效益、複本節約效益、以及Snapshot大小。



== 組態

「組態」方塊提供整合式狀態資訊、可讓SnapCenter 所有執行中的獨立主機和Windows叢集主機都能取得這些資訊、而且您可以存取這些資訊。這包括與這些主機相關的外掛程式狀態資訊。

按一下「hosts（主機）」旁邊的數字、會將您重新導向「hosts（主機）」頁面的「Managed hosts（受管理的主機）」區您可以從這裡取得所選主機的詳細資訊。

此外、此顯示幕還會顯示ONTAP 由支援的獨立式SVM和叢集ONTAP 式SVM總和SnapCenter 、以及您可以存取的項目。按一下SVM旁邊的號碼、會將您重新導向至「Storage Systems（儲存系統）」頁面。您可從這裡取得所選SVM的詳細資訊。

主機組態狀態顯示為紅色（嚴重）、黃色（警告）和綠色（作用中）、以及每個狀態的主機數量。會針對每個狀態提供狀態訊息。

|===
| 組態狀態 | 說明 


 a| 
必須升級
 a| 
執行不受支援外掛程式且需要升級的主機數。不支援的外掛程式與此版本SnapCenter 的支援不相容。



 a| 
移轉為必要項目
 a| 
執行不受支援外掛程式且需要移轉的主機數。不支援的外掛程式與此版本SnapCenter 的支援不相容。



 a| 
未安裝外掛程式
 a| 
成功新增但需要安裝外掛程式、或外掛程式安裝失敗的主機數。



 a| 
已暫停
 a| 
排程已暫停且正在維護的主機數。



 a| 
已停止
 a| 
已啟動但外掛程式服務未執行的主機數。



 a| 
主機停機
 a| 
當機或無法連線的主機數。



 a| 
提供升級（選用）
 a| 
可用更新版本外掛程式套件進行升級的主機數。



 a| 
可移轉（選用）
 a| 
可供移轉的新版外掛程式主機數。



 a| 
設定記錄目錄
 a| 
必須設定記錄目錄以供SCSQL進行交易記錄備份的主機數。



 a| 
設定VMware外掛程式
 a| 
需要新增VMware vSphere的VMware vSphere的VMware外掛程式之主機數SnapCenter 。



 a| 
不明
 a| 
已登錄但尚未觸發安裝的主機數。



 a| 
執行中
 a| 
已啟動且正在執行外掛程式的主機數。而且在SCSQL外掛程式的情況下、會設定記錄目錄和Hypervisor。



 a| 
安裝\解除安裝外掛程式
 a| 
正在安裝或解除安裝外掛程式的主機數。

|===


== 授權容量

「已授權容量」方塊會顯示SnapCenter 有關「已授權容量總計」、「已使用容量」、「容量臨界值警示」及「以非標準容量為基礎的授權」授權之授權到期警示的資訊。


NOTE: 只有SnapCenter 在Cloud Volumes ONTAP 使用以功能為基礎的支援時、才會顯示此畫面。ONTAP Select對於 FAS 、 AFF 或所有 SAN 陣列（ ASA ）平台、 SnapCenter 授權是以控制器為基礎、並獲得無限容量授權、不需要容量授權。

|===
| 授權狀態 | 說明 


 a| 
使用中
 a| 
目前使用中的容量量。



 a| 
通知
 a| 
在儀表板上顯示通知的容量臨界值、如果已設定、則會在傳送電子郵件通知時顯示。



 a| 
授權
 a| 
授權容量。



 a| 
超過
 a| 
超過授權容量的容量。

|===