---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords:  
summary: 您可以從「監控」頁面監控工作進度、取得排程工作的相關資訊、以及檢閱事件和記錄。 
---
= 監控工作、排程、事件和記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「監控」頁面監控工作進度、取得排程工作的相關資訊、以及檢閱事件和記錄。



== 監控工作

您可以檢視SnapCenter 有關還原備份、複製、還原及驗證工作的資訊。您可以根據開始和結束日期、工作類型、資源群組、原則或SnapCenter 是這個外掛程式來篩選此檢視。您也可以取得指定工作的其他詳細資料和記錄檔。

您也可以監控與SnapMirror和SnapVault SnapMirror作業有關的工作。


NOTE: 除非指派SnapCenter 「管理員」或其他超級使用者角色、否則您只能監控您所建立及與您相關的工作。

您可以執行下列與監控工作相關的工作：

* 監控備份、複製、還原及驗證作業。
* 檢視工作詳細資料和報告。
* 停止排程的工作。




== 監控排程

您可能想要檢視目前的排程、以判斷作業開始時間、上次執行時間、以及下次執行時間。您也可以決定執行作業的主機、以及作業的資源群組和原則資訊。

*步驟*

. 在左導覽窗格中、按一下*監控*。
. 在「監視器」頁面中、按一下*排程*。
. 選取資源群組和排程類型。
. 檢視排程作業清單。




== 監控事件

您可以檢視SnapCenter 系統中的各種事件清單、例如使用者建立資源群組或系統啟動活動（例如建立排程備份）。您可能想要檢視事件、以判斷備份或還原作業等作業目前是否在進行中。

*關於此工作*

所有工作資訊都會顯示在「事件」頁面中。例如、當備份工作開始時、會出現「備份開始」事件。備份完成後、會出現「Backup complete'（備份完成）」事件。

*步驟*

. 在左導覽窗格中、按一下*監控*。
. 在「監控」頁面中、按一下「*事件*」。
. （選用）在「Filter（篩選器）」方塊中、輸入開始或結束日期、事件類別（例如備份、資源群組或原則）和嚴重性層級、然後按一下「* Apply *（套用*）」。或者、也可以在「搜尋」方塊中輸入字元。
. 檢視事件清單。




== 監控記錄

您可以檢視及下載SnapCenter 《支援服務器的更新記錄》、SnapCenter 《支援主機代理程式的更新記錄》及外掛程式記錄。您可能想要檢視記錄、以協助疑難排解。

*關於此工作*

您可以篩選記錄、只顯示特定的記錄嚴重性層級：

* 偵錯
* 資訊
* 警告
* 錯誤
* 致命的


您也可以取得工作層級記錄、例如有助於疑難排解備份工作失敗原因的記錄。如需工作層級記錄、請使用*監控*>*工作*選項。

*步驟*

. 在左導覽窗格中、按一下*監控*。
. 在「工作」頁面中、選取工作、然後按一下「下載記錄」。
+
下載的壓縮資料夾包含工作記錄和一般記錄。壓縮資料夾名稱包含所選的工作ID和工作類型。

. 在「監控」頁面中、按一下「*記錄*」。
. 選取記錄類型、主機和執行個體。
+
如果您選取* plugin*作為記錄類型、則可以選取主機或SnapCenter 支援程式。如果日誌類型是* server*、則無法執行此動作。

. 若要依特定來源、訊息或記錄層級篩選記錄、請按一下欄標題頂端的篩選圖示。
+
若要顯示所有記錄、請選擇*大於或等於*作為「Debug」層級。

. 按一下*重新整理*。
. 檢視記錄清單。
. 按一下「*下載*」下載記錄。
+
下載的壓縮資料夾包含工作記錄和一般記錄。壓縮資料夾名稱包含所選的工作ID和工作類型。



在大型組態中、若要獲得最佳效能、您應該SnapCenter 使用PowerShell Cmdlet將適用於的記錄設定設為最小層級。

「et-SmLogSettings -LogLevel All -MaxFileSizes 10MB -MaxSizeRollup Backup 10 -JobLogsMaxFileSizes 10MB -Server'


NOTE: 若要在容錯移轉工作完成後存取健全狀況或組態資訊、請執行Cmdlet「Get-SmRegitoryConfig」。



== 移除SnapCenter 不完整的工作和記錄

您可以移除SnapCenter 來自NetApp的備份、還原、複製及驗證工作和記錄。除非您將成功和失敗的工作記錄移除、否則系統會無限期儲存這些記錄。SnapCenter您可能想要移除這些項目以補充儲存空間。

*關於此工作*

目前不得有任何工作在運作中。您可以提供工作ID來移除特定工作、也可以在指定期間內移除工作。

您不需要將主機置於維護模式即可移除工作。

*步驟*

. 啟動PowerShell。
. 在命令提示字元中輸入：「Open-SMConnection」
. 在命令提示字元中、輸入：「移除SmJobs」
. 在左導覽窗格中、按一下*監控*。
. 在「監控」頁面中、按一下「*工作*」。
. 在「工作」頁面中、檢閱工作狀態。


*瞭解更多資訊*

您可以執行_Get-Help命令name_來取得可搭配Cmdlet使用之參數及其說明的相關資訊。或者、您也可以參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["《軟件指令程式參考指南》SnapCenter"^]。
