---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords: Manage resource groups 
summary: 您可以對資源群組執行各種作業。 
---
= 管理資源群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以對資源群組執行各種作業。

您可以執行下列與資源群組相關的工作：

* 若要修改資源群組、請選取資源群組、然後按一下*修改資源群組*、以編輯您在建立資源群組時所提供的資訊。
+

NOTE: 您可以在修改資源群組時變更排程。不過、若要變更排程類型、您必須修改原則。

+

NOTE: 如果您從資源群組移除資源、目前附加至資源群組的原則中定義的備份保留設定將繼續套用至移除的資源。

* 建立資源群組的備份。
* 建立備份的複本。
+
您可以從現有的SQL、Oracle、Windows檔案系統、自訂應用程式及SAP HANA資料庫資源或資源群組備份中複製。

* 建立資源群組的複本。
+
此作業僅支援SQL資源群組（僅包含資料庫）。您可以設定複製資源群組（複製生命週期）的排程。

* 禁止啟動資源群組上的排程作業。
* 刪除資源群組。




== 停止並恢復資源群組上的作業

您可以暫時停用從資源群組啟動的排程作業。稍後您可以視需要啟用這些作業。

*步驟*

. 在左導覽窗格中、按一下*資源*、然後從清單中選取適當的外掛程式。
. 在「資源」頁面中、從*檢視*清單中選取*資源群組*。
. 選取資源群組、然後按一下「*維護*」。
. 按一下「*確定*」。


如果您想要恢復已置於維護模式的資源群組作業、請選取資源群組、然後按一下「*正式作業*」。



== 刪除資源群組

如果不再需要保護資源群組中的資源、您可以刪除資源群組。您必須先確定已刪除資源群組、才能從SnapCenter 功能性資源移除外掛程式。

*關於此工作*

您應該手動刪除資源群組中任何資源所建立的所有複本。您可以選擇性地強制刪除與資源群組相關的所有備份、中繼資料、原則和Snapshot複本。

*步驟*

. 在左導覽窗格中、按一下*資源*、然後從清單中選取適當的外掛程式。
. 在「資源」頁面中、從*檢視*清單中選取*資源群組*。
. 選取資源群組、然後按一下*刪除*。
. 選用：選取「*刪除與此資源群組*相關的備份與分離原則」核取方塊、即可移除與資源群組相關的所有備份、中繼資料、原則及Snapshot複本。
. 按一下「*確定*」。

