---
permalink: install/concept_create_and_manage_smb_shares.html 
sidebar: sidebar 
keywords: SMB shares 
summary: 若要在儲存虛擬機器（SVM）上設定SMb3共用區、您可以使用SnapCenter 物件使用者介面或PowerShell Cmdlet。 
---
= 建立及管理SMB共用區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在儲存虛擬機器（SVM）上設定SMb3共用區、您可以使用SnapCenter 物件使用者介面或PowerShell Cmdlet。

|===


| *最佳實務做法：*建議使用Cmdlet、因為它可讓您利用SnapCenter 隨附的範本來自動化共用組態。 
|===
這些範本會封裝磁碟區和共用組態的最佳實務做法。您可以在安裝資料夾的「範本」資料夾中找到適用於SnapCenter Windows的「版本資訊」套件的範本。


TIP: 如果您覺得這樣做很舒服、可以依照所提供的模型來建立自己的範本。建立自訂範本之前、您應該先檢閱Cmdlet文件中的參數。



== 建立SMB共用區

您可以使用SnapCenter 「不共用」頁面、在儲存虛擬機器（SVM）上建立SMB3共用區。

您無法使用SnapCenter 支援功能來備份SMB共用區上的資料庫。SMB支援僅限於資源配置。

*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*共用*」。
. 從*儲存虛擬機器*下拉式清單中選取SVM。
. 按一下「*新增*」。
+
「新增共用」對話方塊隨即開啟。

. 在「新共用」對話方塊中、定義共用：
+
|===
| 在此欄位中... | 執行此動作... 


 a| 
說明
 a| 
輸入共用的說明文字。



 a| 
共用名稱
 a| 
輸入共用名稱、例如test_Share。

您為共用區輸入的名稱也會用作磁碟區名稱。

共用名稱：

** 必須是utf-8字串。
** 不得包含下列字元：控制字元：從0x00到0x1F（含）、0x22（雙引號）、以及特殊字元「\/[]：（垂直列）<>+=；、？」




 a| 
共用路徑
 a| 
** 按一下欄位以輸入新的檔案系統路徑、例如/。
** 按兩下欄位、從現有檔案系統路徑清單中選取。


|===
. 當您對輸入項目感到滿意時、請按一下*確定*。
+
此功能可在SVM上建立SMB共用區。SnapCenter





== 刪除SMB共用區

您可以在不再需要SMB共用時刪除它。

*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*共用*」。
. 在「共用」頁面中、按一下*儲存虛擬機器*欄位、顯示下拉式清單、其中包含可用的儲存虛擬機器（SVM）、然後選取您要刪除之共用的SVM。
. 從SVM上的共用清單中、選取您要刪除的共用、然後按一下*刪除*。
. 在刪除共用對話方塊中、按一下*確定*。
+
支援從SVM刪除SMB共用區。SnapCenter


