---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: 認證資料會根據應用程式或環境使用不同的驗證方法。認證資料會驗證使用者、讓他們能夠執行SnapCenter 功能不中斷的作業。您應該建立一組認證來安裝外掛程式、並建立另一組用於資料保護作業的認證。 
---
= 認證方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
認證資料會根據應用程式或環境使用不同的驗證方法。認證資料會驗證使用者、讓他們能夠執行SnapCenter 功能不中斷的作業。您應該建立一組認證來安裝外掛程式、並建立另一組用於資料保護作業的認證。



== Windows驗證

Windows驗證方法會根據Active Directory進行驗證。對於Windows驗證、Active Directory是設定在SnapCenter 非功能性的環境中。無需額外組態即可驗證。SnapCenter您需要Windows認證來執行新增主機、安裝外掛程式套件及排程工作等工作。



== 不受信任的網域驗證

支援使用不受信任網域的使用者和群組來建立Windows認證。SnapCenter若要驗證成功、您應該使用SnapCenter NetApp註冊不受信任的網域。



== 本機工作群組驗證

支援與本機工作群組使用者和群組一起建立Windows認證。SnapCenter本機工作群組使用者和群組的Windows驗證不會在Windows認證建立時進行、而是延後至執行主機登錄和其他主機作業為止。



== SQL Server驗證

SQL驗證方法會針對SQL Server執行個體進行驗證。這表示SQL Server執行個體必須在SnapCenter 支援中發現。因此、在新增SQL認證之前、您必須先新增主機、安裝外掛程式套件、以及重新整理資源。您需要SQL Server驗證才能執行作業、例如在SQL Server上排程或探索資源。



== Linux驗證

Linux驗證方法會針對Linux主機進行驗證。您需要在新增Linux主機並從SnapCenter 支援程式介面從遠端安裝適用於Linux的支援程式套件的初始步驟中進行Linux驗證SnapCenter 。



== AIX驗證

AIX驗證方法會針對AIX主機進行驗證。在新增AIX主機並從SnapCenter 支援程式GUI遠端安裝適用於AIX的支援程式套件的初始步驟中、您需要AIX驗證SnapCenter 。



== Oracle資料庫驗證

Oracle資料庫驗證方法會根據Oracle資料庫進行驗證。如果在資料庫主機上停用作業系統（OS）驗證、您需要Oracle資料庫驗證才能在Oracle資料庫上執行作業。因此、在新增Oracle資料庫認證之前、您應該先在Oracle資料庫中建立具有Sysdba權限的Oracle使用者。



== Oracle ASM驗證

Oracle ASM驗證方法會針對Oracle自動儲存管理（ASM）執行個體進行驗證。如果您需要存取Oracle ASM執行個體、而且資料庫主機上的作業系統（OS）驗證已停用、則需要Oracle ASM驗證。因此、在新增Oracle ASM認證之前、您應該先在ASM執行個體中建立具有Sysasm權限的Oracle使用者。



== RMAN目錄驗證

RMAN目錄驗證方法會根據Oracle Recovery Manager（RMAN）目錄資料庫進行驗證。如果您已設定外部目錄機制並將資料庫登錄至目錄資料庫、則需要新增RMAN目錄驗證。
