---
permalink: install/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: 支援資料保護作業需要數個授權。SnapCenter安裝的不完整授權類型SnapCenter 取決於您的儲存環境和您想要使用的功能。 
---
= 不需要授權SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援多個授權、以保護應用程式、資料庫、檔案系統和虛擬機器的資料。SnapCenter安裝的不完整授權類型SnapCenter 取決於您的儲存環境和您想要使用的功能。

|===
| 授權 | 必要時 


 a| 
以標準控制器為基礎SnapCenter
 a| 
FAS 、 AFF 、 All SAN Array （ ASA ）所需的

不含不含控制器型授權的優質套裝組合。SnapCenter如果您擁有SnapManager 此產品的不支援功能、您也可以取得SnapCenter 「不支援即用」的授權。如果您想要試用 FAS 、 AFF 或 ASA 儲存設備來安裝 SnapCenter 、請聯絡銷售代表以取得優質產品組合評估授權。


NOTE: 此外、也提供資料保護套裝組合的一部分。SnapCenter如果您已購買A400或更新版本、則應購買資料保護套裝組合。



 a| 
以容量為基礎的標準SnapCenter
 a| 
需要搭配使用ONTAP Select Cloud Volumes ONTAP

如果Cloud Volumes ONTAP 您是一個不知道或ONTAP Select 不知道的客戶、您必須根據SnapCenter 由支援的資料、購買每TB容量型授權。根據預設SnapCenter 、不含內建90天100 TB SnapCenter 的功能型試用授權。如需其他詳細資料、請聯絡銷售代表。



 a| 
SnapMirror或SnapVault
 a| 
ONTAP

如果在功能區啟用複寫、則需要SnapMirror或SnapVault 不含任何資訊的授權SnapCenter 。



 a| 
SnapRestore
 a| 
還原及驗證備份所需的。

在主要儲存系統上

* 需要在SnapVault 目的地系統上執行遠端驗證、以及從備份還原。
* SnapMirror目的地系統需要執行遠端驗證。




 a| 
FlexClone
 a| 
複製資料庫和驗證作業所需的。

在一線和二線儲存系統上

* 需要在SnapVault 目的地系統上、從次要資料庫備份建立複本。
* SnapMirror目的地系統需要從次要SnapMirror備份建立複本。




 a| 
通訊協定
 a| 
* LUN的iSCSI或FC授權
* 適用於SMB共用的CIFS授權
* NFS類型VMDK的NFS授權
* 適用於VMFS類型VMDK的iSCSI或FC授權


SnapMirror目的地系統需要在來源磁碟區無法使用時提供資料。



 a| 
不含標準授權（選用）SnapCenter
 a| 
次要目的地


NOTE: 我們建議您將SnapCenter 不需要的「不二用」授權新增至次要目的地。如果SnapCenter 在次要目的地上未啟用「支援支援功能」、SnapCenter 則在執行容錯移轉作業之後、您將無法使用「支援功能」在次要目的地上備份資源。不過、次要目的地需要FlexClone授權才能執行複製與驗證作業。

|===

NOTE: 不再提供「進階」和「不適用的NAS檔案服務」授權。SnapCenter SnapCenter

您應該安裝一SnapCenter 或多個版本的不二授權。如需如何新增授權的資訊、請參閱 link:../install/concept_snapcenter_standard_controller_based_licenses.html["新增SnapCenter 以控制器為基礎的功能"] 或 link:../install/concept_snapcenter_standard_capacity_based_licenses.html["新增SnapCenter 以功能為基礎的「功能型標準」授權"]。



== 單一信箱恢復（SMBR）授權

如果您使用SnapCenter Exchange的還原外掛程式來管理Microsoft Exchange Server資料庫和單一信箱恢復（SMBR）、則您需要額外的SMBR授權、而此授權必須根據使用者信箱另行購買。

NetApp ® 單一信箱恢復已於 2023 年 5 月 12 日結束可用度（ EOA ）。如需詳細資訊、請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2885729.html["CPS-00507"]。NetApp 將持續支援已於 2020 年 6 月 24 日推出的行銷零件編號、以支援購買信箱容量、維護和支援的客戶。

NetApp 單一信箱恢復是 Ontrack 提供的合作夥伴產品。Ontrack PowerControl 提供的功能與 NetApp 單一信箱恢復功能類似。客戶可從 Ontrack （透過 licensingteam@ontrack.com ）取得新的 Ontrack PowerControl 軟體授權、以及 Ontrack PowerControl 的維護與支援續約、以便在 2023 年 5 月 12 日結束後進行精細信箱恢復。
