---
permalink: install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html 
sidebar: sidebar 
keywords: F5, netwoek load balancer, NLB, high availability, elastic load balancing, ELB, Azure load balancing, Amazon Web Services, AWS 
summary: 使用 F5 ，網路負載平衡或 Amazon Web Services 在 SnapCenter 中設定高可用度 
---
= 設定 SnapCenter 伺服器的高可用度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在 Windows 或 Linux 上執行的 SnapCenter 中支援高可用度（ HA ），您可以安裝 F5 負載平衡器。在同SnapCenter 一位置的最多兩部主機中、使用F5可支援主動-被動組態。若要在SnapCenter 整個過程中使用F5負載平衡器、您應該設定SnapCenter 「伺服器」並設定「F5負載平衡器」。

您也可以設定網路負載平衡（ NLB ）來設定 SnapCenter 高可用度。您應該在 SnapCenter 安裝之外手動設定 NLB ，以獲得高可用度。

對於雲端環境，您可以使用 Amazon Web Services （ AWS ） Elastic Load Balancing （ Elb ）和 Azure 負載平衡器來設定高可用度。

[role="tabbed-block"]
====
.使用F5設定高可用度
--
有關使用 F5 負載平衡器設定SnapCenter伺服器以實現高可用性的說明，請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_SnapCenter_Servers_for_high_availability_using_F5_Load_Balancer["如何使用SnapCenter F5負載平衡器設定高可用度的功能"^] 。

您必須是SnapCenter 本機「管理員」群組的成員（除了指派給SnapCenterAdmin角色之外）、才能使用下列Cmdlet來新增和移除F5叢集：

* add-SmServerCluster
* add-SmServer
* 移除SmServerCluster
+
如需詳細資訊、請 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《軟件指令程式參考指南》SnapCenter"^]參閱。



其他資訊

* 安裝並設定SnapCenter 好高可用度的功能後、請編輯SnapCenter 「不間斷」桌面捷徑、以指向F5叢集IP。
* 如果SnapCenter 在伺服器之間發生容錯移轉、而且還有現有SnapCenter 的故障恢復工作階段、您必須關閉瀏覽器並SnapCenter 重新登入。
* 在負載平衡器設定（ NLB 或 F5 ）中，如果您新增的主機有部分由 NLB 或 F5 主機解析，而且 SnapCenter 主機無法連線至此主機，則 SnapCenter 主機頁面會經常在主機停機和執行中狀態之間切換。若要解決此問題，您應該確定兩台 SnapCenter 主機都能解決 NLB 或 F5 主機中的主機問題。
* MFA 設定的 SnapCenter 命令應在所有主機上執行。依賴方組態應在Active Directory Federation Services（AD FS）伺服器中使用F5叢集詳細資料進行。啟用 MFA 之後，主機層級的 SnapCenter UI 存取將會遭到封鎖。
* 在容錯移轉期間，稽核記錄設定不會反映在第二部主機上。因此，您應該在 F5 被動式主機變成主動式時，手動重複稽核記錄設定。


--
.使用網路負載平衡（ NLB ）設定高可用度
--
您可以設定網路負載平衡（ NLB ）來設定 SnapCenter 高可用度。您應該在 SnapCenter 安裝之外手動設定 NLB ，以獲得高可用度。

如需如何使用 SnapCenter 設定網路負載平衡（ NLB ）的相關資訊，請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_NLB_and_ARR_with_SnapCenter["如何使用SnapCenter 功能進行NLB設定"^]。

--
.使用 AWS 彈性負載平衡（ Elb ）設定高可用度
--
您可以在 Amazon Web Services （ AWS ）中設定高可用度 SnapCenter 環境，方法是在不同的可用性區域（ AZs ）中設定兩部 SnapCenter 伺服器，並將它們設定為自動容錯移轉。此架構包括虛擬私有 IP 位址，路由表，以及作用中和待命 MySQL 資料庫之間的同步處理。

.步驟
. 在 AWS 中設定虛擬私有重疊 IP 。如需相關資訊、請 https://docs.aws.amazon.com/vpc/latest/userguide/replace-local-route-target.html["設定虛擬私有覆蓋 IP"^]參閱。
. 準備 Windows 主機
+
.. 強制將 IPv4 排定優先順序高於 IPv6 ：
+
*** 位置： HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
*** 金鑰： DisabledComponents
*** 鍵入： reg_dWord
*** 值： 0x20


.. 請確定完整網域名稱可透過 DNS 或本機主機組態解析至 IPv4 位址。
.. 請確定您尚未設定系統 Proxy 。
.. 如果在沒有 Active Directory 的情況下使用安裝程式，且伺服器不在同一個網域中，請確定 Windows Server 上的管理員密碼相同。
.. 在兩部 Windows Server 上新增虛擬 IP 。


. 建立 SnapCenter 叢集。
+
.. 啟動 PowerShell 並連線至 SnapCenter 。
`Open-SmConnection`
.. 建立叢集。
`Add-SmServerCluster -ClusterName <cluster_name> -ClusterIP <cluster_ip> -PrimarySCServerIP <primary_ip> -Verbose -Credential administrator`
.. 新增次要伺服器。
`Add-SmServer -ServerName <server_name> -ServerIP <server_ip> -CleanUpSecondaryServer -Verbose -Credential administrator`
.. 取得高可用度詳細資料。
`Get-SmServerConfig`


. 建立 Leda 功能，以在虛擬私有 IP 端點無法使用時調整路由表，並由 AWS CloudWatch 監控。如需相關資訊、請 https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html#getting-started-create-function["建立 Lambda 函數"^]參閱。
. 在 CloudWatch 中建立監控器，以監控 SnapCenter 端點的可用度。如果端點無法連線，則會設定警示來觸發 Lambda 功能。Lambda 功能可調整路由表，將流量重新導向至作用中的 SnapCenter 伺服器。如需相關資訊、請 https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Create.html["建立合成炮"^]參閱。
. 使用步驟功能來實作工作流程，作為 CloudWatch 監控的替代方案，可縮短容錯移轉時間。此工作流程包含 Lambda 探查功能，可測試 SnapCenter URL ，用於儲存故障計數的 DynamoDB 表格，以及 Step 功能本身。
+
.. 使用 lambda 函數來探查 SnapCenter URL 。如需相關資訊、請 https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html["建立 Lambda 函數"^]參閱。
.. 建立一個 DynamoDB 表格，用於在兩個 Step 函數迭代之間儲存失敗計數。如需相關資訊、請 https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html["從 DynamoDB 表開始"^]參閱。
.. 建立 Step 功能。如需相關資訊、請 https://docs.aws.amazon.com/step-functions/["步驟功能文件"^]參閱。
.. 測試單一步驟。
.. 測試完整功能。
.. 建立 IAM 角色，並調整允許執行 Lambda 功能的權限。
.. 建立觸發步驟功能的排程。如需相關資訊、請 https://docs.aws.amazon.com/step-functions/latest/dg/using-eventbridge-scheduler.html["使用 Amazon EventBridge 排程器啟動「步驟」功能"^]參閱。




--
.使用 Azure 負載平衡器設定高可用度
--
您可以使用 Azure 負載平衡器來設定高可用度 SnapCenter 環境。

.步驟
. 使用 Azure 入口網站，在規模集中建立虛擬機器。Azure 虛擬機器磅秤集可讓您建立及管理一組負載平衡的虛擬機器。虛擬機器執行個體的數量可以自動增加或減少，以因應需求或定義的排程。如需相關資訊、請 https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/flexible-virtual-machine-scale-sets-portal["使用 Azure 入口網站，在規模集中建立虛擬機器"^]參閱。
. 設定虛擬機器之後，請登入 VM Set 中的每個虛擬機器，然後在兩個節點中安裝 SnapCenter Server 。
. 在主機 1 中建立叢集。
`Add-SmServerCluster -ClusterName <cluster_name> -ClusterIP <specify the load balancer front end virtual ip> -PrimarySCServerIP <ip address> -Verbose -Credential <credentials>`
. 新增次要伺服器。
`Add-SmServer -ServerName <name of node2> -ServerIP <ip address of node2> -Verbose -Credential <credentials>`
. 取得高可用度詳細資料。
`Get-SmServerConfig`
. 如有需要，請重新建置次要主機。
`Set-SmRepositoryConfig -RebuildSlave -Verbose`
. 容錯移轉至第二個主機。
`Set-SmRepositoryConfig ActiveMaster <name of node2> -Verbose`


--
= 從 NLB 切換至 F5 以獲得高可用度

您可以將SnapCenter 您的「叢集HA」組態從「網路負載平衡」（NLB）變更為使用「5負載平衡器」。

*步驟*

. 使用SnapCenter F5設定高可用度的功能。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_SnapCenter_Servers_for_high_availability_using_F5_Load_Balancer["深入瞭解"^]。
. 在支援服務器的支援主機上、啟動PowerShell。SnapCenter
. 使用Open-SmConnection Cmdlet啟動工作階段、然後輸入認證資料。
. 使用SnapCenter update-SmServerCluster Cmdlet更新支援服務器、使其指向F5叢集IP位址。
+
您可以執行_Get-Help命令name_來取得可搭配Cmdlet使用之參數及其說明的相關資訊。或者、您也可以參閱 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《軟件指令程式參考指南》SnapCenter"^]。



====