---
permalink: install/install_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: install, snapcenter software, install, linux host 
summary: 您可以在 Linux 主機上安裝 SnapCenter 伺服器。 
---
= 在 Linux 主機上安裝 SnapCenter 伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行SnapCenter 《伺服器安裝程式執行檔」來安裝SnapCenter 《伺服器版」。

.開始之前
* 如果您想要使用非 root 使用者安裝 SnapCenter 伺服器、但該使用者沒有足夠的權限來安裝 SnapCenter 、請從 NetApp 支援網站取得 sudoers checksum 檔案。您應該根據 Linux 版本使用適當的 Checksum 檔案。
* 安裝期間。 NET 執行階段時、如果安裝無法解決 _libicu_ 程式庫的相依性、請執行下列命令來安裝 _libicu_ ： `yum install -y libicu`
* 如果由於 _Perl_ 不可用而導致 SnapCenter 伺服器安裝失敗、請執行下列命令來安裝 _Perl_ ： `yum install -y perl`
* 如果 Sudo 套件在 SUSE Linux 中無法使用、請安裝 Sudo 套件以避免驗證失敗。
* 對於 SUSE Linux 、請設定主機名稱以避免安裝失敗。
* 運行命令檢查安全的 Linux 狀態 `sestatus`。如果 _SELinux 狀態 _ 為「已啟用」、且 _current-mode_ 為「強制」、請執行下列步驟：
+
** 執行命令： `sudo semanage port -a -t http_port_t -p tcp <WEBAPP_EXTERNAL_PORT_>`
+
_webapp_extal_port_ 的預設值為 8146

** 如果防火牆封鎖連接埠、請執行 `sudo firewall-cmd --add-port <WEBAPP_EXTERNAL_PORT_>/tcp`
+
_webapp_extal_port_ 的預設值為 8146

** 從具有讀寫權限的目錄執行下列命令：
+
*** `sudo ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
+
如果命令傳回「無待辦事項」、請在安裝 SnapCenter Server 之後重新執行命令。

*** 如果命令會建立 _my-Nginx.pp_ 、請執行命令以啟用原則套件： `sudo semodule -i my-nginx.pp`


** 用於 MySQL PID 目錄的路徑是 /var/opt/mysqld_ 。執行下列命令以設定 MySQL 安裝的權限。
+
*** `mkdir /var/opt/mysqld`
*** `sudo semanage fcontext -a -t mysqld_var_run_t "/var/opt/mysqld(/.*)?"`
*** `sudo restorecon -Rv /var/opt/mysqld`


** 用於 MySQL Data 目錄的路徑為： //INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository / MySQL/_ 。執行下列命令以設定 MySQL 資料目錄的權限。
+
*** `mkdir -p /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`
*** `sudo semanage fcontext -a -t mysqld_db_t "/INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL(/.*)?"`
*** `sudo restorecon -Rv /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`






.關於這項工作
* 當 SnapCenter 伺服器安裝在 Linux 主機上時、會安裝第三方服務、例如 MySQL 、 RabbitMQ 、 Errlang 。您不應將其解除安裝。
* 安裝在 Linux 主機上的 SnapCenter 伺服器不支援：
+
** 高可用度
** Windows外掛程式
** Active Directory （僅支援本機使用者、包括具有 creds 的 root 和非 root 使用者）
** 登入 SnapCenter 的金鑰型驗證




.步驟
. 從下載下列項目 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 支援網站"^] 至 / 主目錄 _ 。
+
** SnapCenter 伺服器安裝套件 - * snapcenter-linux-server-（ el8/el9/sles15 ） .bin*
** 公開金鑰檔案 - *snapcenter_public_key.pub
** 各自的簽名檔 - * snapcenter-linux-server-（ el8/el9/sles15 ） .bin.SIG*


. 驗證簽名檔案。
`$openssl dgst -sha256 -verify snapcenter_public_key.pub -signature <path to signature file> <path to bin file>`
. 若為非 root 使用者安裝、請新增在 *snapcenter_server_checksum _ （ el8/el9/sles15 ）中指定的 visudo 內容。 txt* 與 .bin 安裝程式一起提供。
. 指派 .bin 安裝程式的執行權限。
`chmod +x snapcenter-linux-server-(el8/el9/sles15).bin`
. 執行其中一個動作來安裝 SnapCenter Server 。
+
|===
| 如果您想要執行 ... | 執行此動作... 


 a| 
互動式安裝
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

系統會提示您輸入下列詳細資料：

** 用於存取 Linux 主機外部 SnapCenter 伺服器的 Web 應用程式外部連接埠。預設值為 8146 。
** 將安裝 SnapCenter 伺服器的 SnapCenter 伺服器使用者。
** 安裝套件的安裝目錄。




 a| 
非互動式安裝
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DWEBAPP_EXTERNAL_PORT=<port> -DWEBAPP_INTERNAL_PORT=<port> -DSMCORE_PORT=<port> -DSCHEDULER_PORT=<port>  -DSNAPCENTER_SERVER_USER=<user> -DUSER_INSTALL_DIR=<dir> -DINSTALL_LOG_NAME=<filename>`

範例： Sudo ./snapcenter_linux_server.bin -I silent -DWEBAPP_external_port=8146 -DSNAPCENTER_SERVER_USER=root -DUSER_INSTALL_DIR=/opt -DINSTALL_LOT_NAME=InstallerLog.log

記錄將儲存在 /var/opt/snapcenter/logs_ 。

安裝 SnapCenter 伺服器所需傳遞的參數：

** DWEBAPP_extal_port ： Webapp 外部連接埠、用於存取 Linux 主機外部的 SnapCenter 伺服器。預設值為 8146 。
** DWEBAPP_INTERNal_port ： Webapp 內部連接埠、用於存取 Linux 主機內的 SnapCenter 伺服器。預設值為 8147 。
** DSMCORE 服務執行所在的 SMCore 連接埠。預設值為 8145 。
** DSCHEDULER_port ：排程器服務執行所在的排程器連接埠。預設值為 8154 。
** DSNAPCENTER_SERVER_USER ：將安裝 SnapCenter 伺服器的 SnapCenter 伺服器使用者。對於 _DSNAPCENTER_SERVER_USER_ 、預設值為執行安裝程式的使用者。
** duser_install_DIR ：安裝套件的安裝目錄。對於 _Duser_install_DIR_ 、預設安裝目錄為 _/opt_ 。
** DINSTAL_log_name ：儲存安裝記錄檔的記錄檔名稱。這是選用參數、如果指定、則不會在主控台上顯示任何記錄。 如果您未指定此參數、記錄將會顯示在主控台上、也會儲存在預設記錄檔中。
** DSELINUX ：如果 _SELinux 狀態 _ 為「已啟用」、則 _ 目前模式 _ 為「強制」、且您已執行「開始之前」一節中所述的命令、則應指定此參數並將值指派為 1 。預設值為 0 。
** DUPGRADE ：預設值為 0 。將此參數及其值指定為 0 以外的任何整數、以升級 SnapCenter 伺服器。


|===


.接下來呢？
* 如果 _SELinux 狀態 _ 為「已啟用」、且 _current-mode_ 為「強制」、則 *NginX* 服務無法啟動。您應該執行下列命令：
+
.. 移至主目錄。
.. 執行命令： `journalctl -x|grep nginx`。
.. 如果不允許 Webapp 內部連接埠（ 8147 ）接聽、請執行下列命令：
+
*** `ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
*** `semodule -i my-nginx.pp`


.. 執行 `setsebool -P httpd_can_network_connect on`






== 註冊產品以啟用支援

如果您是 NetApp 新手、而且沒有現有的 NetApp 帳戶、則應註冊產品以啟用支援。

.步驟
. 安裝 SnapCenter 之後、請瀏覽 * 說明 > 關於 * 。
. 在 _ 關於 SnapCenter _ 對話方塊中、記下以 971 開頭的 20 位數 SnapCenter 執行個體。
. 單擊。 https://register.netapp.com[]
. 按一下「 * 我不是註冊的 NetApp 客戶 * 」。
. 請指定您的詳細資料以自行註冊。
. 將 NetApp 參考 SN 欄位保留空白。
. 從產品線下拉式清單中選取 * SnapCenter * 。
. 選擇帳單供應商。
. 輸入 20 位數的 SnapCenter 執行個體 ID 。
. 按一下*提交*。

