---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: SnapCenter 6.1 支援 ASA R2 系統，可針對僅限 SAN 的客戶需求，提供簡化的體驗。 
---
= 瞭解如何在 SnapCenter 中支援 ASA R2 系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 6.1 支援 ASA R2 系統，可針對僅限 SAN 的客戶需求，提供簡化的體驗。

ASA R2 系統可在單一 HA 配對部署上支援所有 SAN 傳輸協定（ iSCSI ， FC 和 NVMe over TCP/IP ）。SCSI （ iSCSI 和 FC ）傳輸協定使用對稱的雙主動式架構來執行多重路徑、因此主機和儲存設備之間的所有路徑都是主動 / 最佳化的。iSCSI 和 NVMe / TCP 傳輸協定支援主機和儲存設備之間的直接路徑。


NOTE: SnapCenter 僅支援 ASA R2 系統上的 VMware 虛擬機器檔案系統（ VMFS ）。

ASA R2 系統採用一致性群組的儲存單元：

* 儲存單元可讓 SAN 主機有可用的儲存空間來執行資料作業。儲存單元是指 SCSI 主機的 LUN 或 NVMe 主機的 NVMe 命名空間。
* 一致性群組是以單一單元管理的儲存單元集合。


ASA R2 系統使用儲存單元和一致性群組來簡化儲存管理和資料保護。例如，假設您的資料庫由一致性群組中的 10 個儲存單元組成，而您需要備份整個資料庫。您可以備份一致性群組來保護整個資料庫、而無需個別備份每個儲存單元。

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["深入瞭解 ASA R2 系統"]。



== 適用於 ASA R2 系統的 SnapCenter 6.1 支援的項目

如果您使用的是 ASA R2 儲存系統， SnapCenter 可讓您在 SnapCenter 支援的所有應用程式上執行下列作業：

* 透過 VMDK 建立應用程式的主要備份
* 將一致性群組快照傳輸至次要儲存系統
* 從其他位置還原備份和還原
+
** 使用 VMware VMotion 從主要與次要儲存設備進行原位還原
** 從主要與次要儲存設備連接並複製還原


* 複製備份，並將複製複製到其他位置




== 適用於 ASA R2 系統的 SnapCenter 6.1 不支援的項目

* 原始裝置對應（ RDM ）
* 適用於 Oracle 的應用程式磁碟區
* SAP HANA NDV
* LockVault
* 防竄改快照
* Flex Group
* 階層式一致性群組
* 從 ONTAP 9.x 移轉至 ASA R2 系統
* 重新命名快照
* SnapCenter 不支援 SQL 外掛主機的記錄目錄次要資源配置。您應該使用 ONTAP CLI 或系統管理員手動設定。

