---
permalink: install/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: 您應該知道支援的儲存系統、應用程式和資料庫。 
---
= 支援的儲存系統與應用程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該知道支援的儲存系統、應用程式和資料庫。

* SnapCenter 支援 ONTAP 9.12.1 及更新版本、可保護您的資料。
+
對於 ONTAP 9.12.1 及更低版本、從 SnapLock 資料保險箱快照建立的複本作為還原的一部分、將會繼承 SnapLock 資料保險箱到期時間。儲存管理員應在 SnapLock 到期後手動清理複本。

* SnapCenter 6.1 支援執行 ONTAP 9.16.1 的 NetApp ASA R2 系統。
+
ASA R2 系統為所有 Flash 平台上建置的僅 SAN 環境提供統一化的硬體與軟體解決方案。

+
如需 ASA R2 系統的相關資訊，請參閱 https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2 說明文件"^]。

* SnapCenter 支援 Amazon FSX for NetApp ONTAP 來保護您的資料。
+
如果您使用Amazon FSX for NetApp ONTAP Sfor NetApp的話、請確保SnapCenter 將支援此功能的支援伺服器主機外掛程式升級至4.5 P1或更新版本、以執行資料保護作業。

+
支援非揮發性記憶體高速（ NVMe ） over Transport Control Protocol （ TCP ）。

+
如需Amazon FSX for NetApp ONTAP 功能的相關資訊、請參閱 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 的支援文件"^]。

* 支援不同應用程式和資料庫的保護。SnapCenter
+
如需支援應用程式和資料庫的詳細資訊，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 互通性對照表工具"^]。

* SnapCenter 4.9 P1 及更新版本支援在 VMware Cloud on Amazon Web Services （ AWS ）軟體定義資料中心（ SDDC ）環境中保護 Oracle 和 Microsoft SQL 工作負載。
+
如需詳細資訊、請參閱 https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["在 AWS SDDC 環境中使用 VMware Cloud 中的 NetApp SnapCenter 來保護 Oracle 、 MS SQL 工作負載"]。


