---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: 在安裝SnapCenter 完還原伺服器和應用程式或資料庫外掛程式之前、您應確保符合連線和連接埠的要求。 
---
= 連線與連接埠需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安裝SnapCenter 完還原伺服器和應用程式或資料庫外掛程式之前、您應確保符合連線和連接埠的要求。

* 應用程式無法共用連接埠。
+
每個連接埠都必須專供適當的應用程式使用。

* 對於可自訂的連接埠、如果您不想使用預設連接埠、可以在安裝期間選取自訂連接埠。
+
您可以使用「修改主機」精靈、在安裝後變更外掛程式連接埠。

* 對於固定連接埠、您應該接受預設的連接埠號碼。
* 防火牆
+
** 防火牆、Proxy或其他網路裝置不應干擾連線。
** 如果您在安裝SnapCenter 時指定自訂連接埠、則應在外掛主機上新增防火牆規則、以供SnapCenter 該連接埠用於「支援程式載入器」。




下表列出不同的連接埠及其預設值。

|===
| 連接埠名稱 | 連接埠編號 | 傳輸協定 | 方向 | 說明 


 a| 
連接埠SnapCenter
 a| 
8146
 a| 
HTTPS
 a| 
雙向
 a| 
此連接埠用於 SnapCenter 用戶端（ SnapCenter 使用者）與 SnapCenter 伺服器之間的通訊，也用於從外掛主機與 SnapCenter 伺服器之間的通訊。

您可以自訂連接埠號碼。



 a| 
WSSMCore通訊連接埠SnapCenter
 a| 
8145
 a| 
HTTPS
 a| 
雙向
 a| 
此連接埠可用於SnapCenter 在Sfor the Sfor Server和SnapCenter 安裝了該插件的主機之間進行通訊。

您可以自訂連接埠號碼。



 a| 
排程器服務連接埠
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
此連接埠用於 SnapCenter 集中化伺服器主機內所有受管理外掛程式的 SnapCenter 排程器工作流程。

您可以自訂連接埠號碼。



 a| 
RabbitMQ 連接埠
 a| 
5672
 a| 
TCP
 a| 
 a| 
這是 RabbitMQ 接聽的預設連接埠、用於排程器服務與 SnapCenter 之間的發行者訂購者模式通訊。



 a| 
MySQL連接埠
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
連接埠用於與 SnapCenter 儲存庫資料庫通訊。您可以建立從 SnapCenter 伺服器到 MySQL 伺服器的安全連線。 link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["深入瞭解"]



 a| 
Windows外掛程式主機
 a| 
135 、 445
 a| 
TCP
 a| 
 a| 
此連接埠用於 SnapCenter 伺服器與正在安裝外掛程式的主機之間的通訊。Microsoft 指定的其他動態連接埠範圍也應該是開放的。



 a| 
Linux或AIX外掛程式主機
 a| 
22
 a| 
SSH
 a| 
單向
 a| 
此連接埠用於 SnapCenter 伺服器與主機之間的通訊，從伺服器啟動至用戶端主機。



 a| 
適用於 Windows ， Linux 或 AIX 的 SnapCenter 外掛程式套件
 a| 
8145
 a| 
HTTPS
 a| 
雙向
 a| 
此連接埠用於 SMCore 與安裝外掛程式套件的主機之間的通訊。可自訂。

您可以自訂連接埠號碼。



 a| 
Oracle資料庫的支援外掛程式SnapCenter
 a| 
27216
 a| 
 a| 
 a| 
Oracle的外掛程式會使用預設的JDBC連接埠來連線至Oracle資料庫。



 a| 
SnapCenter Plug-in for Exchange 資料庫
 a| 
909
 a| 
 a| 
 a| 
預設的 NET 。 Windows 外掛程式使用 TCP 連接埠來連線至 Exchange VSS 回撥。



 a| 
NetApp 支援的 SnapCenter 外掛程式
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
這是僅用於自訂外掛程式主機的內部連接埠、不需要防火牆例外。

透過連接埠8145、即可在伺服SnapCenter 器與自訂外掛程式之間進行通訊。



 a| 
叢集或SVM通訊連接埠ONTAP
 a| 
* 443（HTTPS）
* 80（HTTP）

 a| 
* HTTPS
* HTTP

 a| 
雙向
 a| 
此連接埠由SAL（Storage Abstraction Layer、Storage Abstraction Layer）使用、用於執行SnapCenter 支援服務器和SVM的主機之間的通訊。此連接埠目前也用於SnapCenter Windows外掛程式主機上的SAL、用於SnapCenter 在支援該外掛程式的主機和SVM之間進行通訊。



 a| 
SAP HANA資料庫適用的插件SnapCenter
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
雙向
 a| 
對於多租戶資料庫容器（MDC）單一租戶、連接埠編號以13結尾；對於非MDC、連接埠編號以15結尾。

您可以自訂連接埠號碼。



 a| 
適用於 PostgreSQL 的 SnapCenter 外掛程式
 a| 
5432
 a| 
 a| 
 a| 
此連接埠是預設的 PostgreSQL 連接埠，可讓 PostgreSQL 外掛程式與 PostgreSQL 叢集進行通訊。

您可以自訂連接埠號碼。

|===
若要修改連接埠詳細資料、請參閱 link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["修改外掛程式主機"]。
