---
permalink: install/reference_space_and_sizing_requirements.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 安裝SnapCenter 完此伺服器之前、您應該先熟悉空間和規模需求。您也應該套用可用的系統和安全性更新。 
---
= 空間與規模需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝SnapCenter 完此伺服器之前、您應該先熟悉空間和規模需求。您也應該套用可用的系統和安全性更新。

|===
| 項目 | Windows 主機需求 | Linux 主機需求 


 a| 
作業系統
 a| 
Microsoft Windows

僅支援英文、德文、日文及簡體中文版的作業系統。

如需支援版本的最新資訊，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121033;&solution=1258&isHWU&src=IMT["NetApp 互通性對照表工具"^]。
 a| 
* Red Hat Enterprise Linux （ RHEL ） 8 和 9
* SUSE Linux Enterprise Server （ SLES ） 15.


如需支援版本的最新資訊，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121032;&solution=1258&isHWU&src=IMT["NetApp 互通性對照表工具"^]。



 a| 
最小CPU數
 a| 
4核心
 a| 
4核心



 a| 
最低RAM
 a| 
8 GB


NOTE: MySQL伺服器緩衝資源池使用總RAM的20%。
 a| 
8 GB



 a| 
不需佔用SnapCenter 太多硬碟空間、即可容納整個伺服器軟體和記錄
 a| 
7 GB


NOTE: 如果SnapCenter 您在SnapCenter 安裝了S什麼 伺服器的同一個磁碟機上有這個版本的資訊庫、建議您使用15 GB的容量。
 a| 
15 GB



 a| 
不需SnapCenter 佔用太多硬碟空間
 a| 
8 GB


NOTE: 附註：如果SnapCenter 您在SnapCenter 安裝了該系統資訊庫的同一個磁碟機中安裝了該伺服器、則建議您使用15 GB的容量。
 a| 
不適用



 a| 
必要的軟體套件
 a| 
* ASP.NET Core Runtime 8.0.12 （以及所有後續 8.0.x 修補程式）代管產品組合
* PowerShell 7.4.2 或更新版本


如需 .NET 特定疑難排解資訊、請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["對於沒有網際網路連線的舊版系統、 SnapCenter 升級或安裝失敗"^]。
 a| 
* NET Framework 8.0.12 （以及所有後續的 8.0.x 修補程式）
* PowerShell 7.4.2 或更新版本
* Nginx 是可做為反向 Proxy 的 Web 伺服器
* Pam-devel
+
PAM （可插拔驗證模組）是一種系統安全工具、可讓系統管理員設定驗證原則、而無需重新編譯執行驗證的程式。



|===

NOTE: ASP.NET 核心需要 IIS_IUSRS 來存取 Windows 上 SnapCenter Server 中的暫存檔系統。
