---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks, create, manage, clustered disks, view 
summary: Windows主機將儲存系統上的LUN視為虛擬磁碟。您可以使用SnapCenter 支援功能來建立及設定FC連接或iSCSI連接的LUN。 
---
= 建立及管理磁碟
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows主機將儲存系統上的LUN視為虛擬磁碟。您可以使用SnapCenter 支援功能來建立及設定FC連接或iSCSI連接的LUN。

* 支援僅基本磁碟。SnapCenter不支援動態磁碟。
* 若為GPT、則僅允許一個資料分割區和一個主分割區使用NTFS或CSVFS格式化一個磁碟區、並有一個掛載路徑。
* 支援的分割區樣式：GPT、MBR;在VMware UEFI VM中、僅支援iSCSI磁碟



NOTE: 不支援重新命名磁碟。SnapCenter如果SnapCenter 以這個名稱重新命名由該系統管理的磁碟、SnapCenter 則無法成功執行此功能。



== 檢視主機上的磁碟

您可以在每個使用SnapCenter 支援的Windows主機上檢視磁碟。

*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*磁碟*」。
. 從*主機*下拉式清單中選取主機。
+
隨即列出磁碟。





== 檢視叢集式磁碟

您可以檢視SnapCenter 叢集上的叢集式磁碟、並使用NetApp進行管理。叢集式磁碟只有在您從「主機」下拉式清單中選取叢集時才會顯示。

*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*磁碟*」。
. 從*主機*下拉式清單中選取叢集。
+
隨即列出磁碟。





== 建立FC連接或iSCSI連接的LUN或磁碟

Windows主機將儲存系統上的LUN視為虛擬磁碟。您可以使用SnapCenter 支援功能來建立及設定FC連接或iSCSI連接的LUN。

如果您想要建立及格式化SnapCenter 非支援的磁碟、則僅支援NTFS和CSVFS檔案系統。

*您需要的是什麼*

* 您必須為儲存系統上的LUN建立磁碟區。
+
磁碟區只能容納LUN、而只能容納使用SnapCenter NetApp建立的LUN。

+

NOTE: 除非已分割實體複本、否則您無法在SnapCenter建立的實體複本磁碟區上建立LUN。

* 您必須已在儲存系統上啟動FC或iSCSI服務。
* 如果您使用iSCSI、則必須已與儲存系統建立iSCSI工作階段。
* 適用於Windows的支援功能外掛程式套件只能安裝在您要建立磁碟的主機上。SnapCenter


*關於此工作*

* 除非Windows Server容錯移轉叢集中的主機共用LUN、否則您無法將LUN連線至多個主機。
* 如果LUN由使用CSV（叢集共用磁碟區）的Windows Server容錯移轉叢集主機共用、則必須在擁有叢集群組的主機上建立磁碟。


*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*磁碟*」。
. 從*主機*下拉式清單中選取主機。
. 按一下「*新增*」。
+
「Create Disk（建立磁碟）」精靈隨即開啟。

. 在LUN Name（LUN名稱）頁面中、識別LUN：
+
|===
| 在此欄位中... | 執行此動作... 


 a| 
儲存系統
 a| 
選取LUN的SVM。



 a| 
LUN路徑
 a| 
單擊*瀏覽*以選擇包含LUN的文件夾的完整路徑。



 a| 
LUN名稱
 a| 
輸入LUN的名稱。



 a| 
叢集大小
 a| 
選取叢集的LUN區塊配置大小。

叢集大小取決於作業系統和應用程式。



 a| 
LUN標籤
 a| 
（可選）輸入LUN的描述性文字。

|===
. 在「磁碟類型」頁面中、選取磁碟類型：
+
|===
| 選取... | 如果... 


 a| 
專用磁碟
 a| 
LUN只能由一部主機存取。

忽略*資源群組*欄位。



 a| 
共享磁碟
 a| 
LUN由Windows Server容錯移轉叢集中的主機共用。

在「*資源群組*」欄位中輸入叢集資源群組的名稱。您只需要在容錯移轉叢集中的一部主機上建立磁碟。



 a| 
叢集共用Volume（CSV）
 a| 
LUN由使用CSV的Windows Server容錯移轉叢集中的主機共用。

在「*資源群組*」欄位中輸入叢集資源群組的名稱。請確定您要在其中建立磁碟的主機是叢集群組的擁有者。

|===
. 在「磁碟機內容」頁面中、指定磁碟機內容：
+
|===
| 屬性 | 說明 


 a| 
自動指派掛載點
 a| 
根據系統磁碟機自動指派磁碟區掛載點。SnapCenter

例如、如果您的系統磁碟機為C：、則自動指派會在C：磁碟機（C：\scmnpt\）下建立磁碟區掛載點。共享磁碟不支援自動指派。



 a| 
指派磁碟機代號
 a| 
將磁碟掛載到您在鄰近下拉式清單中選取的磁碟機。



 a| 
使用Volume掛載點
 a| 
將磁碟掛載到您在鄰近欄位中指定的磁碟機路徑。

磁碟區掛載點的根目錄必須由您建立磁碟的主機擁有。



 a| 
請勿指派磁碟機代號或磁碟區掛載點
 a| 
如果您偏好在Windows中手動掛載磁碟、請選擇此選項。



 a| 
LUN大小
 a| 
指定LUN大小；至少150 MB。

在鄰近的下拉式清單中選取MB、GB或TB。



 a| 
針對裝載此LUN的磁碟區使用精簡配置
 a| 
精簡配置LUN。

資源隨需配置一次只會配置所需的儲存空間、讓LUN能夠有效率地擴充至最大可用容量。

請確定磁碟區上有足夠的可用空間、以容納您認為需要的所有LUN儲存設備。



 a| 
選擇分割區類型
 a| 
選取「Guid分割表」的GPT分割區、或「主開機記錄」的「MBR-分割區」。

在Windows Server容錯移轉叢集中、MBR分 區可能會導致錯誤對齊問題。


NOTE: 不支援統一化可延伸韌體介面（UEFI）分割磁碟。

|===
. 在「Map LUN（對應LUN）」頁面中、選取主機上的iSCSI或FC啟動器：
+
|===
| 在此欄位中... | 執行此動作... 


 a| 
主機
 a| 
按兩下叢集群組名稱以顯示下拉式清單、其中會顯示屬於叢集的主機、然後選取啟動器的主機。

此欄位只有在Windows Server容錯移轉叢集中的主機共用LUN時才會顯示。



 a| 
選擇主機啟動器
 a| 
選取* Fibre Channel*或* iscsi *、然後選取主機上的啟動器。

如果您使用FC搭配多重路徑I/O（MPIO）、則可以選取多個FC啟動器。

|===
. 在「群組類型」頁面中、指定要將現有的igroup對應至LUN、或是建立新的igroup：
+
|===
| 選取... | 如果... 


 a| 
為選取的啟動器建立新的igroup
 a| 
您想要為選取的啟動器建立新的igroup。



 a| 
選擇現有的igroup或為選取的啟動器指定新的igroup
 a| 
您想要為選取的啟動器指定現有的igroup、或使用您指定的名稱建立新的igroup。

在* igroup name*欄位中輸入igroup名稱。輸入現有igroup名稱的前幾個字母、以自動填寫欄位。

|===
. 在「摘要」頁面中、檢閱您的選擇、然後按一下「*完成*」。
+
實體建立LUN、並將其連接至主機上的指定磁碟機或磁碟機路徑。SnapCenter





== 調整磁碟大小

您可以隨著儲存系統的需求變更而增加或減少磁碟的大小。

*關於此工作*

* 對於精簡配置的LUN、ONTAP 將以最大大小顯示LUN幾何大小。
* 對於完整配置的LUN、可擴充的大小（磁碟區中可用的大小）會顯示為最大大小。
* 具有MBR-型分割區的LUN大小上限為2 TB。
* 具有GPT型分割區的LUN儲存系統大小上限為16 TB。
* 在調整LUN大小之前、最好先建立Snapshot複本。
* 如果您需要從調整LUN大小之前所製作的Snapshot複本還原LUN、SnapCenter 則會自動將LUN重新調整為Snapshot複本的大小。
+
還原作業完成後、調整大小後新增至LUN的資料必須從調整大小後所製作的Snapshot複本中還原。



*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*磁碟*」。
. 從主機下拉式清單中選取主機。
+
隨即列出磁碟。

. 選取您要調整大小的磁碟、然後按一下「*調整大小*」。
. 在「調整磁碟大小」對話方塊中、使用滑桿工具來指定磁碟的新大小、或是在「大小」欄位中輸入新的大小。
+

NOTE: 如果您手動輸入大小、則必須在適當啟用「縮小或擴充」按鈕之前、先在「大小」欄位外按一下。此外、您必須按一下MB、GB或TB以指定測量單位。

. 如果您對輸入項目滿意、請視需要按一下*縮小*或*展開*。
+
可重新調整磁碟大小。SnapCenter





== 連接磁碟

您可以使用「連線磁碟」精靈、將現有的LUN連線至主機、或重新連線已中斷連線的LUN。

*您需要的是什麼*

* 您必須已在儲存系統上啟動FC或iSCSI服務。
* 如果您使用iSCSI、則必須已與儲存系統建立iSCSI工作階段。
* 除非Windows Server容錯移轉叢集中的主機共用LUN、否則您無法將LUN連線至多個主機。
* 如果LUN由使用CSV（叢集共用磁碟區）的Windows Server容錯移轉叢集主機共用、則您必須連接擁有叢集群組的主機上的磁碟。
* Windows外掛程式只需安裝在要連接磁碟的主機上。


*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*磁碟*」。
. 從*主機*下拉式清單中選取主機。
. 按一下「*連線*」。
+
「連線磁碟」精靈隨即開啟。

. 在LUN Name（LUN名稱）頁面中、識別要連線的LUN：
+
|===
| 在此欄位中... | 執行此動作... 


 a| 
儲存系統
 a| 
選取LUN的SVM。



 a| 
LUN路徑
 a| 
按一下*瀏覽*以選取包含LUN的磁碟區完整路徑。



 a| 
LUN名稱
 a| 
輸入LUN的名稱。



 a| 
叢集大小
 a| 
選取叢集的LUN區塊配置大小。

叢集大小取決於作業系統和應用程式。



 a| 
LUN標籤
 a| 
（可選）輸入LUN的描述性文字。

|===
. 在「磁碟類型」頁面中、選取磁碟類型：
+
|===
| 選取... | 如果... 


 a| 
專用磁碟
 a| 
LUN只能由一部主機存取。



 a| 
共享磁碟
 a| 
LUN由Windows Server容錯移轉叢集中的主機共用。

您只需要將磁碟連接至容錯移轉叢集中的一部主機。



 a| 
叢集共用Volume（CSV）
 a| 
LUN由使用CSV的Windows Server容錯移轉叢集中的主機共用。

請確定您要連線至磁碟的主機是叢集群組的擁有者。

|===
. 在「磁碟機內容」頁面中、指定磁碟機內容：
+
|===
| 屬性 | 說明 


 a| 
自動指派
 a| 
讓SnapCenter 我們根據系統磁碟機自動指派磁碟區掛載點。

例如、如果您的系統磁碟機為C：、則自動指派內容會在C：磁碟機（C：\scmnpt\）下建立磁碟區掛載點。共享磁碟不支援自動指派內容。



 a| 
指派磁碟機代號
 a| 
將磁碟掛載到您在鄰近下拉式清單中選取的磁碟機。



 a| 
使用Volume掛載點
 a| 
將磁碟掛載到您在鄰近欄位中指定的磁碟機路徑。

磁碟區掛載點的根目錄必須由您建立磁碟的主機擁有。



 a| 
請勿指派磁碟機代號或磁碟區掛載點
 a| 
如果您偏好在Windows中手動掛載磁碟、請選擇此選項。

|===
. 在「Map LUN（對應LUN）」頁面中、選取主機上的iSCSI或FC啟動器：
+
|===
| 在此欄位中... | 執行此動作... 


 a| 
主機
 a| 
按兩下叢集群組名稱以顯示下拉式清單、其中會顯示屬於叢集的主機、然後選取啟動器的主機。

此欄位只有在Windows Server容錯移轉叢集中的主機共用LUN時才會顯示。



 a| 
選擇主機啟動器
 a| 
選取* Fibre Channel*或* iscsi *、然後選取主機上的啟動器。

如果您使用FC搭配MPIO、則可以選取多個FC啟動器。

|===
. 在「群組類型」頁面中、指定要將現有的igroup對應至LUN、還是要建立新的igroup：
+
|===
| 選取... | 如果... 


 a| 
為選取的啟動器建立新的igroup
 a| 
您想要為選取的啟動器建立新的igroup。



 a| 
選擇現有的igroup或為選取的啟動器指定新的igroup
 a| 
您想要為選取的啟動器指定現有的igroup、或使用您指定的名稱建立新的igroup。

在* igroup name*欄位中輸入igroup名稱。輸入現有igroup名稱的前幾個字母、以自動填寫欄位。

|===
. 在「摘要」頁面中、檢閱您的選擇、然後按一下「*完成*」。
+
將LUN連接到主機上指定的磁碟機或磁碟機路徑。SnapCenter





== 中斷磁碟連線

您可以中斷LUN與主機的連線、而不影響LUN的內容、但有一項例外：如果您在將實體複本分割之前中斷連線、則會遺失該實體複本的內容。

*您需要的是什麼*

* 請確定任何應用程式都未使用LUN。
* 請確定未使用監控軟體監控LUN。
* 如果LUN是共享的、請務必從LUN移除叢集資源相依性、並確認叢集中的所有節點都已開啟電源、正常運作且可供SnapCenter 使用。


*關於此工作*

如果您中斷SnapCenter 連接已建立的FlexClone Volume中的LUN、且該磁碟區上沒有連接其他LUN、SnapCenter 則會刪除該磁碟區。在中斷LUN連線之前SnapCenter 、將會顯示一則訊息、警告您FlexClone Volume可能會被刪除。

為了避免自動刪除FlexClone Volume、您應該在中斷連接最後一個LUN之前、重新命名該磁碟區。當您重新命名Volume時、請務必變更多個字元、而非僅變更名稱中的最後一個字元。

*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*磁碟*」。
. 從*主機*下拉式清單中選取主機。
+
隨即列出磁碟。

. 選取您要中斷連線的磁碟、然後按一下「*中斷連線*」。
. 在「中斷磁碟連線」對話方塊中、按一下「*確定*」。
+
中斷磁碟連線。SnapCenter





== 刪除磁碟

您可以在不再需要時刪除磁碟。刪除磁碟之後、您無法取消刪除該磁碟。

*步驟*

. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*磁碟*」。
. 從*主機*下拉式清單中選取主機。
+
隨即列出磁碟。

. 選取您要刪除的磁碟、然後按一下*刪除*。
. 在刪除磁碟對話方塊中、按一下*確定*。
+
系統會刪除磁碟。SnapCenter


