---
permalink: protect-scu/concept_overview_snapcenter_plug_in_for_UNIX_file_systems.html 
sidebar: sidebar 
keywords: overview, unix file system, plug-in for unix file system, backup, restore, clone 
summary: 適用於 Unix 檔案系統的外掛程式支援 Unix 檔案系統的備份、還原及複製。 
---
= SnapCenter Plug-in for Unix 檔案系統的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您的環境中安裝了適用於 Unix 檔案系統的外掛程式時、您可以使用 SnapCenter 來備份、還原及複製 Unix 檔案系統。您也可以執行支援這些作業的工作。

* 探索資源
* 備份 Unix 檔案系統
* 排程備份作業
* 還原檔案系統備份
* 複製檔案系統備份
* 監控備份、還原及複製作業




== 支援的組態

|===
| 項目 | 支援的組態 


 a| 
環境
 a| 
* 實體伺服器
* 虛擬伺服器
+
NFS 和 SAN 上的 VVOL 資料存放區。 VVOL 資料存放區只能使用適用於 VMware vSphere 的 ONTAP 工具進行資源配置。





 a| 
作業系統
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server（SLES）




 a| 
檔案系統
 a| 
* SAN：
+
** LVM 和非 LVM 型檔案系統
** VMDK ext3 、 ext4 和 xfs 上的 LVM


* NFS ： NFS v3 、 NFS v4.x




 a| 
通訊協定
 a| 
* FC
* FCoE
* iSCSI
* NFS




 a| 
多重路徑
 a| 
是的

|===


== 限制

* 不支援在磁碟區群組中混合使用 RDM 和虛擬磁碟。
* 不支援檔案層級還原。
+
不過、您可以手動執行檔案層級還原、方法是複製備份、然後手動複製檔案。

* 不支援在 NFS 和 VMFS 資料存放區的 VMDK 之間混合使用檔案系統。
* NVMe 不受支援。
* 不支援資源配置。




== 功能

* 讓Oracle資料庫外掛程式能夠處理Linux或AIX系統上的基礎主機儲存堆疊、在Oracle資料庫上執行資料保護作業
* 支援執行ONTAP 支援的儲存系統上的網路檔案系統（NFS）和儲存區域網路（SAN）傳輸協定。
* 對於Linux系統、當您部署SnapCenter 適用於VMware vSphere的VMware vSphere的VMware vCenter外掛程式、並使用SnapCenter VMware vCenter登錄外掛程式時、即可支援VMDK和RDM LUN上的Oracle資料庫。
* 在SAN檔案系統和LVM配置上支援Mount Guard for AIX。
* 支援增強的日誌式檔案系統（JFS2）、只有在SAN檔案系統上進行即時記錄、以及僅適用於AIX系統的LVM配置。
+
SAN原生裝置、檔案系統及以SAN裝置為建置基礎的LVM配置均受到支援。

* 自動化 SnapCenter 環境中 UNIX 檔案系統的應用程式感知備份、還原及複製作業

