---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: 為您要備份的 Unix 檔案系統建立備份原則。 
---
= 為 Unix 檔案系統建立備份原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 SnapCenter 備份 Unix 檔案系統之前、您必須先為要備份的資源或資源群組建立備份原則。備份原則是一組規則、可管理您管理、排程及保留備份的方式。您也可以指定複寫、指令碼及備份類型設定。當您想要在其他資源或資源群組上重複使用原則時、建立原則可節省時間。

.開始之前
* 您必須完成安裝 SnapCenter 、新增主機、探索檔案系統及建立儲存系統連線等工作、以準備好保護資料。
* 如果您要將快照複製到鏡像或資料保險箱次要儲存設備、 SnapCenter 管理員必須將來源和目的地磁碟區的 SVM 指派給您。
* 查看 SnapMirror 主動同步的特定先決條件和限制。如需相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror 主動同步的物件限制"]。


.關於這項工作
* SnapLock
+
** 如果選取「保留特定天數的備份複本」選項、則 SnapLock 保留期間必須小於或等於所述保留天數。
+
指定 Snapshot 鎖定期間可防止在保留期間到期之前刪除 Snapshot 。  這可能會導致保留的快照數量超過原則中指定的數量。

+
對於 ONTAP 9.12.1 及更低版本、從 SnapLock 資料保險箱快照建立的複本作為還原的一部分、將會繼承 SnapLock 資料保險箱到期時間。儲存管理員應在 SnapLock 到期後手動清理複本。





.步驟
. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下*原則*。
. 從下拉列表中選擇 *Unix File Systems* 。
. 按一下「*新增*」。
. 在「名稱」頁面中，輸入原則名稱和詳細資料。
. 在「備份與複寫」頁面中，執行下列動作：
+
.. 指定備份設定。
.. 選取*隨選*、*每小時*、*每日*、*每週*或*每月*、以指定排程頻率。
.. 在 [ 選取次要複寫選項 ] 區段中，選取下列其中一個或兩個次要複寫選項：


+
|===
| 針對此欄位... | 執行此動作... 


 a| 
建立本機Snapshot複本之後、請更新SnapMirror
 a| 
選取此欄位可在另一個磁碟區（SnapMirror複寫）上建立備份集的鏡射複本。

應啟用此選項以進行 SnapMirror 主動同步。



 a| 
建立本機Snapshot複本後再更新SnapVault
 a| 
選取此選項以執行磁碟對磁碟備份複寫（SnapVault 還原備份）。



 a| 
重試次數錯誤
 a| 
輸入作業停止前可允許的最大複寫嘗試次數。

|===
. 在「保留」頁面中，指定備份類型的保留設定，以及在「備份與複寫」頁面中選取的排程類型：
+
|===


| 如果您想要... | 然後... 


 a| 
保留一定數量的快照
 a| 
選取 * 要保留的複本 * ，然後指定要保留的快照數。

如果快照數量超過指定數量、則會先刪除最舊的複本、然後刪除快照。


NOTE: 最大保留值為 1018 。如果保留設定的值高於基礎ONTAP 版支援的值、則備份將會失敗。


IMPORTANT: 如果您打算啟用SnapVault 此功能、則必須將保留數設為2或更高。如果將保留計數設為 1 、則保留作業可能會失敗、因為第一個 Snapshot 是 SnapVault 關係的參考 Snapshot 、直到較新的 Snapshot 複寫到目標為止。



 a| 
將快照保留一定天數
 a| 
選取 * 保留複本 * ，然後指定您要保留快照的天數，再將其刪除。



 a| 
快照副本鎖定期
 a| 
選擇*Snapshot 副本鎖定期限*並指定天、月或年的持續時間。

SnapLock 保留期應少於 100 年。

|===
. 選取原則標籤。
+

NOTE: 您可以為遠端複製的主快照指派SnapMirror標籤，從而允許主快照將快照複製作業從SnapCenter卸載到ONTAP二級系統。無需在策略頁面中啟用SnapMirror或SnapVault選項即可完成此操作。

. 在「指令碼」頁面中、分別輸入您要在備份作業之前或之後執行的指令碼或指令碼路徑和引數。
+

NOTE: 您應該檢查插件主機上的命令列表中是否存在這些命令，該命令位於 _ /opt/oracle/scc/etc/allowed_commands.config_ NetApp 路徑中 SnapCenter 。

+
您也可以指定指令碼逾時值。預設值為60秒。

. 檢閱摘要、然後按一下「*完成*」。

