---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: 為您要備份的 Unix 檔案系統建立備份原則。 
---
= 為 Unix 檔案系統建立備份原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 SnapCenter 備份 Unix 檔案系統之前、您必須先為要備份的資源或資源群組建立備份原則。備份原則是一組規則、可管理您管理、排程及保留備份的方式。您也可以指定複寫、指令碼及備份類型設定。當您想要在其他資源或資源群組上重複使用原則時、建立原則可節省時間。

.開始之前
* 您必須完成安裝 SnapCenter 、新增主機、探索檔案系統及建立儲存系統連線等工作、以準備好保護資料。
* 如果您要將快照複製到鏡像或資料保險箱次要儲存設備、 SnapCenter 管理員必須將來源和目的地磁碟區的 SVM 指派給您。
* 查看 SnapMirror 主動同步的特定先決條件和限制。如需相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror 主動同步的物件限制"]。


.步驟
. 在左側導覽窗格中、按一下*設定*。
. 在「設定」頁面中、按一下*原則*。
. 從下拉列表中選擇 *Unix File Systems* 。
. 按一下「*新增*」。
. 在「名稱」頁面中、輸入原則名稱和說明。
. 選取*隨選*、*每小時*、*每日*、*每週*或*每月*、以指定排程頻率。
. 在「保留」頁面中、指定備份類型的保留設定、以及在「備份類型」頁面中選取的排程類型：
+
|===


| 如果您想要... | 然後... 


 a| 
保留一定數量的快照
 a| 
選取 * 要保留的 Snapshot 複本總數 * 、然後指定要保留的 Snapshot 數。

如果快照數量超過指定數量、則會先刪除最舊的複本、然後刪除快照。


NOTE: 對於使用率為1018的ONTAP 資源、如使用率為0、9.4或更新版本、ONTAP 而使用率為254的資源、如使用率為0、9.3或更新版本。如果保留設定的值高於基礎ONTAP 版支援的值、則備份將會失敗。


IMPORTANT: 如果您打算啟用SnapVault 此功能、則必須將保留數設為2或更高。如果將保留計數設為 1 、則保留作業可能會失敗、因為第一個 Snapshot 是 SnapVault 關係的參考 Snapshot 、直到較新的 Snapshot 複寫到目標為止。



 a| 
將快照保留一定天數
 a| 
選取 * 保留 Snapshot 複本 * 、然後指定您要保留 Snapshot 的天數、再將其刪除。

|===
+

NOTE: 只有在您選擇歸檔記錄檔做為備份的一部分時、才能保留歸檔記錄備份。

. 在「複寫」頁面中、指定複寫設定：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
建立本機Snapshot複本之後、請更新SnapMirror
 a| 
選取此欄位可在另一個磁碟區（SnapMirror複寫）上建立備份集的鏡射複本。

應啟用此選項以進行 SnapMirror 主動同步。



 a| 
建立本機Snapshot複本後再更新SnapVault
 a| 
選取此選項以執行磁碟對磁碟備份複寫（SnapVault 還原備份）。



 a| 
次要原則標籤
 a| 
選取Snapshot標籤。

根據您選取的 Snapshot 標籤、 ONTAP 會套用符合標籤的次要 Snapshot 保留原則。


NOTE: 如果您在建立本機Snapshot複本之後選擇*更新SnapMirror、您可以選擇性地指定次要原則標籤。不過、如果SnapVault 您在建立本機Snapshot複本*之後選擇*更新SUpdate、則應指定次要原則標籤。



 a| 
重試次數錯誤
 a| 
輸入作業停止前可允許的最大複寫嘗試次數。

|===
+

NOTE: 您應該在 ONTAP 中為次要儲存設備設定 SnapMirror 保留原則、以避免達到次要儲存設備快照的上限。

. 在「指令碼」頁面中、分別輸入您要在備份作業之前或之後執行的指令碼或指令碼路徑和引數。
+

NOTE: 您應該檢查插件主機上的命令列表中是否存在這些命令（可從 _/opt/netapp/sapcenter/SCC /etc/allowed_commands.config_ 路徑下找到）。

+
您也可以指定指令碼逾時值。預設值為60秒。

. 檢閱摘要、然後按一下「*完成*」。

