---
permalink: protect-db2/add-hosts-and-install-plug-in-packages-on-remote-hosts-ibm-db2.html 
sidebar: sidebar 
keywords: credentials 
summary: 您必須使用SnapCenter 「更新主機」頁面來新增主機、然後安裝外掛程式套件。外掛程式會自動安裝在遠端主機上。您可以為個別主機或叢集新增主機並安裝外掛程式套件。 
---
= 新增主機並在遠端主機上安裝外掛程式套件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須使用SnapCenter 「更新主機」頁面來新增主機、然後安裝外掛程式套件。外掛程式會自動安裝在遠端主機上。您可以為個別主機或叢集新增主機並安裝外掛程式套件。

.開始之前
* 如果 SnapCenter 伺服器主機的作業系統為 Windows 2019 、而外掛主機的作業系統為 Windows 2022 、則應執行下列步驟：
+
** 升級至 Windows Server 2019 （ OS Build 17763.5936 ）或更新版本
** 升級至 Windows Server 2022 （ OS Build 20348.2402 ）或更新版本


* 您必須是指派給具有外掛安裝和解除安裝權限之角色的使用者、例如SnapCenter 「支援管理員」角色。
* 在Windows主機上安裝外掛程式時、如果您指定的認證不是內建的、或是使用者屬於本機工作群組使用者、則必須停用主機上的UAC.
* 您應確保訊息佇列服務正在執行中。
* 管理文件包含有關管理主機的資訊。
* 如果您使用群組託管服務帳戶（GMSA）、則應該使用管理權限來設定GMSA。
+
link:../protect-db2/configure-gMSA-on-windows-server-2012-or-later.html["在適用於 IBM DB2 的 Windows Server 2016 或更新版本上設定群組託管服務帳戶"^]



.關於這項工作
* 您無法將SnapCenter 某個支援服務器作為外掛主機新增至另SnapCenter 一個支援服務器。


.步驟
. 在左側導覽窗格中、按一下*主機*。
. 驗證頂端是否已選取*託管主機*索引標籤。
. 按一下「 * 新增 * 」。
. 在「hosts」（主機）頁面中、執行下列動作：
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
主機類型
 a| 
選取主機類型：

** Windows
** Linux
+

NOTE: IBM DB2 外掛程式安裝在 IBM DB2 用戶端主機上、此主機可以位於 Windows 系統或 Linux 系統上。





 a| 
主機名稱
 a| 
輸入通訊主機名稱。輸入主機的完整網域名稱（FQDN）或IP位址。取決於DNS的正確組態。SnapCenter因此、最佳做法是輸入FQDN。



 a| 
認證資料
 a| 
選取您所建立的認證名稱、或建立新認證。認證資料必須具有遠端主機的管理權限。如需詳細資訊、請參閱建立認證的相關資訊。

您可以將游標放在所提供的認證名稱上、以檢視認證資料的詳細資料。


NOTE: 認證驗證模式取決於您在「新增主機」精靈中指定的主機類型。

|===
. 在選取要安裝的外掛程式區段中、選取要安裝的外掛程式。
+
使用 REST API 安裝 DB2 外掛程式時、您必須將版本傳給 3.0 。例如 DB2 ： 3.0

. （可選）單擊*更多選項*。
+
|===
| 針對此欄位... | 執行此動作... 


 a| 
連接埠
 a| 
保留預設連接埠號碼或指定連接埠號碼。預設連接埠號碼為8145。如果SnapCenter 將該伺服器安裝在自訂連接埠上、該連接埠編號將會顯示為預設連接埠。


NOTE: 如果您手動安裝外掛程式並指定自訂連接埠、則必須指定相同的連接埠。否則、作業將會失敗。



 a| 
安裝路徑
 a| 
IBM DB2 外掛程式安裝在 IBM DB2 用戶端主機上、此主機可以位於 Windows 系統或 Linux 系統上。

** 針對適用於Windows的「更新程式套件」、預設路徑為C:\Program Files\NetApp\SnapCenter。SnapCenter您也可以自訂路徑。
** 對於適用於Linux的「版本套件」、預設路徑為/opp/NetApp/snapcenter。SnapCenter您也可以自訂路徑。




 a| 
跳過預先安裝檢查
 a| 
如果您已手動安裝外掛程式、但不想驗證主機是否符合安裝外掛程式的需求、請選取此核取方塊。



 a| 
使用群組託管服務帳戶（GMSA）來執行外掛程式服務
 a| 
如果您想要使用群組託管服務帳戶（GMSA）來執行外掛程式服務、請針對Windows主機選取此核取方塊。


NOTE: 請以下列格式提供GMSA名稱：domainname\accountName$。


NOTE: GMSA僅會做為SnapCenter Windows版的更新外掛程式服務的登入服務帳戶。

|===
. 按一下*提交*。
+
如果您尚未選取「略過預先檢查」核取方塊、則會驗證主機是否符合安裝外掛程式的需求。 磁碟空間、 RAM 、 PowerShell 版本、。 NET 版本、位置（適用於 Windows 外掛程式）和 Java 11 （適用於 Windows 和 Linux 外掛程式）均根據最低需求進行驗證。如果不符合最低要求、則會顯示適當的錯誤或警告訊息。

+
如果錯誤與磁碟空間或RAM有關、您可以更新位於C:\Program Files\NetApp\SnapCenter Webapp的Web.config檔案、以修改預設值。如果錯誤與其他參數有關、您必須修正問題。

+

NOTE: 在HA設定中、如果您要更新web.config檔案、則必須更新兩個節點上的檔案。

. 如果主機類型為Linux、請驗證指紋、然後按一下*確認並提交*。
+
在叢集設定中、您應該驗證叢集中每個節點的指紋。

+

NOTE: 即使先前已將同一部主機新增至SnapCenter 更新版本、而且指紋已確認、指紋驗證也是必要的。

. 監控安裝進度。
+
** 對於 Windows 外掛程式、安裝與升級記錄檔位於： _C ： \Windows\SnapCenter 外掛程式 <JOBID>
** 對於 Linux 外掛程式、安裝記錄檔位於： <JOBID> 。升級記錄檔位於： <JOBID>




.完成後
如果您想要升級至 SnapCenter 6.0 或更新版本，則會從遠端外掛程式伺服器解除安裝現有的 DB2 Perl 外掛程式。
