---
permalink: protect-db2/prerequisites-to-adding-hosts-and-installing-snapcenter-plug-in-for-ibm-db2.html 
sidebar: sidebar 
keywords: credentials 
summary: 新增主機並安裝外掛程式套件之前、您必須先完成所有需求。適用於 IBM DB2 的 SnapCenter 外掛程式可在 Windows 和 Linux 環境中使用。 
---
= 新增主機及安裝 IBM DB2 SnapCenter 外掛程式的必要條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新增主機並安裝外掛程式套件之前、您必須先完成所有需求。適用於 IBM DB2 的 SnapCenter 外掛程式可在 Windows 和 Linux 環境中使用。

* 您必須在主機上安裝 Java 11 。
+

NOTE: 不支援IBM Java。

* 對於 Windows 、外掛程式建立者服務應使用「 'LocalSystem' 」 Windows 使用者執行、這是以網域管理員身分安裝適用於 IBM DB2 的外掛程式時的預設行為。
* 在Windows主機上安裝外掛程式時、如果您指定的認證不是內建的、或是使用者屬於本機工作群組使用者、則必須停用主機上的UAC.SnapCenter Plug-in for Microsoft Windows 預設會在 Windows 主機上與 IBM DB2 外掛程式一起部署。
* SnapCenter 伺服器應可存取 IBM DB2 主機的外掛程式 8145 或自訂連接埠。




== Windows主機

* 您必須擁有具有本機系統管理員權限的網域使用者、並在遠端主機上具有本機登入權限。
* 在 Windows 主機上安裝適用於 IBM DB2 的外掛程式時、會自動安裝適用於 Microsoft Windows 的 SnapCenter 外掛程式。
* 您必須為root或非root使用者啟用密碼型SSH連線。
* 您必須在 Windows 主機上安裝 Java 11 。
+
http://www.java.com/en/download/manual.jsp["適用於所有作業系統的Java下載"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121066;&solution=1259&isHWU&src=IMT["NetApp 互通性對照表工具"]





== Linux主機

* 您必須為root或非root使用者啟用密碼型SSH連線。
* 您必須在 Linux 主機上安裝 * mksh* 程式庫。
* 您必須在 Linux 主機上安裝 Java 11 。
+
http://www.java.com/en/download/manual.jsp["適用於所有作業系統的Java下載"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121066;&solution=1259&isHWU&src=IMT["NetApp 互通性對照表工具"]

* 對於在 Linux 主機上執行的 IBM DB2 資料庫、當安裝適用於 IBM DB2 的外掛程式時、會自動安裝適用於 UNIX 的 SnapCenter 外掛程式。
* 您應該將 * bash* 作為外掛程式安裝的預設 Shell 。




== 補充命令

若要在適用於 IBM DB2 的 SnapCenter 外掛程式上執行補充命令、您必須將其包含在檔案中 `allowed_commands.config` 。

`allowed_commands.config` 檔案位於 SnapCenter Plug-in for IBM DB2 目錄的「 etc 」子目錄中。

.Windows主機
預設： `C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc\allowed_commands.config`

自訂路徑： `<Custom_Directory>\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc\allowed_commands.config`

.Linux主機
預設： `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

自訂路徑： `<custom_Directory>/NetApp/snapcenter/scc/etc/allowed_commands.config`

若要允許在外掛主機上執行補充命令、請開啟 `allowed_commands.config` 編輯器中的檔案。在單獨的行中輸入每個命令。它不區分大小寫。
例如、

命令： mount

命令： umount

請務必指定完整路徑名稱。如果路徑名稱包含空格、請以引號（ " ）括住路徑名稱。
例如、

命令： "C:\Program Files\NetApp\SnapCreator commands\sdcli.exe"

命令： myscript.bat

如果是 `allowed_commands.config` 檔案不存在、命令或指令碼執行將遭到封鎖、工作流程將失敗並顯示下列錯誤：

"[/mnt/mount -a] 不允許執行。在外掛程式主機上的檔案 %s 中新增命令以進行授權。 "

如果命令或指令碼未出現在中 `allowed_commands.config`、命令或指令碼執行將會遭到封鎖、工作流程將會失敗、並顯示下列錯誤：

"[/mnt/mount -a] 不允許執行。在外掛程式主機上的檔案 %s 中新增命令以進行授權。 "


NOTE: 您不應使用萬用字元項目（ * ）來允許所有命令。



== 為Linux主機的非root使用者設定Sudo權限

非root使用者可利用發行版本的更新版本安裝適用於Linux的《SUSE外掛程式套件」、並開始外掛程序。SnapCenter SnapCenter外掛程式程序將以有效的非root使用者身分執行。您應該為非root使用者設定Sudo權限、以提供對多個路徑的存取權。

*您需要的是什麼*

* Sudo 1.8.7版或更新版本。
* 對於非 root 使用者、請確保非 root 使用者和使用者群組的名稱相同。
* 編輯_/etc/ssh / sshd_config_檔案、以設定訊息驗證代碼演算法：Macs HMAC - SHA2-256和MAC HMAC - SHA2-512。
+
更新組態檔後、重新啟動sshd服務。

+
範例：

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*關於此工作*

您應該為非root使用者設定Sudo權限、以便存取下列路徑：

* /home/_Linux使用者_/.sc_NetApp/snapcenter_linux_host_plugin.bin
* /custature_location / NetApp/snapcenter/spl/installal/plugins/uninstall
* /cust_LOUSE/NetApp/snapcenter/spl/bin/spl


*步驟*

. 登入您要安裝SnapCenter 適用於Linux的支援套件的Linux主機。
. 使用visudo Linux公用程式、將下列行新增至/etc/udoers檔案。
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+

NOTE: 如果您有RAC設定、以及其他允許的命令、您應該將下列項目新增至/etc/udoers檔案：「/setc/bin/olsnodes <crs_home> 」



您可以從/etc/oracle/OLR.loc_檔案取得_crs_home_的 值。

_Linux使用者_是您所建立的非root使用者名稱。

您可以從 *SC_UNIT_plugins_checksum ． txt* 檔案取得 _checksum 值 _ 、檔案位於：

* _C ： \ProgramData\NetApp\SnapCenter\Package 儲存庫 \SC_UNIX 外掛程式 _checksum ． txt_ （如果 SnapCenter 伺服器安裝在 Windows 主機上）。
* 如果 SnapCenter 伺服器安裝在 Linux 主機上、則為 /opt/NetApp/snapcenter/SnapManagerWeb/Repository /SC_UNIT_plugin_checksum ． txt_ 。



IMPORTANT: 此範例只能做為建立自己資料的參考。
