---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: 在新增主機並安裝外掛程式套件之前、您必須先完成所有需求。NetApp 支援的外掛程式可同時用於 Windows ， Linux 或 AIX 環境。 
---
= 新增主機和安裝 Windows ， Linux 或 AIX 外掛程式套件的必要條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在新增主機並安裝外掛程式套件之前、您必須先完成所有需求。Windows ， Linux 和 AIX 環境支援 NetApp 支援的外掛程式。


NOTE: AIX 支援儲存設備和 Oracle 應用程式。

* 您必須在 Linux ， Windows 或 AIX 主機上安裝 Java 11 。
+

NOTE: IBM Java 在 Windows 和 Linux 主機上不受支援。

* 在Windows主機上安裝外掛程式時、如果您指定的認證不是內建的、或是使用者屬於本機工作群組使用者、則必須停用主機上的UAC.
* NetApp 支援的外掛程式（例如 MongoDB ， ORASCPM ， Oracle 應用程式， SAP ASE ， SAP MaxDB 和儲存外掛程式）必須可在執行新增主機作業的用戶端主機上使用。




== 一般

如果您使用iSCSI、iSCSI服務應該會執行。



== Windows主機

* 您必須擁有具有本機系統管理員權限的網域使用者、並在遠端主機上具有本機登入權限。
* 如果您管理SnapCenter 的是叢集節點、則必須有擁有叢集中所有節點管理權限的使用者。
* 您必須手動選擇適用於 Microsoft Windows 的 SnapCenter 外掛程式。
+
http://www.java.com/en/download/manual.jsp["下載適用於 Windows 的 JAVA"]





== Linux 和 AIX 主機


NOTE: AIX 支援儲存設備和 Oracle 應用程式。

* 您必須為root或非root使用者啟用密碼型SSH連線。
* 您必須在 Linux 主機上安裝 Java 11 。
+
如果您使用 Windows Server 2019 或 Windows Server 2016 作為 SnapCenter 伺服器主機、則必須安裝 Java 11 。互通性對照表工具IMT （英文）包含有關需求的最新資訊。

+
http://www.java.com/en/download/manual.jsp["下載適用於 Linux 的 JAVA"]

+
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?license=IBM["下載適用於 AIX 的 JAVA"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp 互通性對照表工具"]

* 您必須為非root使用者設定Sudo權限、才能存取多個路徑。使用visudo Linux公用程式、將下列行新增至/etc/udoers檔案。
+

NOTE: 請確定您使用的是Sudo 1.8.7版或更新版本。

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_Linux使用者_是您所建立的非root使用者名稱。

+
您可以從 *SC_UNIT_plugins_checksum ． txt* 檔案取得 _checksum 值 _ 、檔案位於：

+
** _C ： \ProgramData\NetApp\SnapCenter\Package 儲存庫 \SC_UNIX 外掛程式 _checksum ． txt_ （如果 SnapCenter 伺服器安裝在 Windows 主機上）。
** 如果 SnapCenter 伺服器安裝在 Linux 主機上、則為 /opt/NetApp/snapcenter/SnapManagerWeb/Repository /SC_UNIT_plugin_checksum ． txt_ 。
+

IMPORTANT: 此範例只能做為建立自己資料的參考。







== AIX主機需求

在安裝SnapCenter 適用於AIX的支援套件之前、您應確保主機符合要求。


NOTE: AIX 支援儲存設備和 Oracle 應用程式。


NOTE: 作爲適用於AIX的支援不支援並行Volume群組的《支援UNIX的程式集》外掛程式。SnapCenter SnapCenter

|===
| 項目 | 需求 


 a| 
作業系統
 a| 
部分7.1或更新版本AIX



 a| 
主機上安裝的不需使用的RAM SnapCenter
 a| 
4 GB



 a| 
主機上安裝及記錄SnapCenter 插件的最低空間
 a| 
2 GB


NOTE: 您應該配置足夠的磁碟空間、並監控logs資料夾的儲存使用量。所需的記錄空間會因受保護的實體數量和資料保護作業的頻率而有所不同。如果沒有足夠的磁碟空間、將不會針對最近執行的作業建立記錄。



 a| 
必要的軟體套件
 a| 
Java 11 IBM Java

如果您已將Java升級至最新版本、則必須確定位於/var/opt/snapcenter/spl/etc/spl.properties的Java_home選項已設定為正確的Java版本和正確的路徑。

|===
如需支援版本的最新資訊，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["NetApp 互通性對照表工具"^]。



=== 為非root使用者設定適用於AIX主機的Sudo權限

支援非root使用者安裝適用於AIX的支援套件、並啟動外掛程式的程序。SnapCenter SnapCenter外掛程式程序將以有效的非root使用者身分執行。您應該為非root使用者設定Sudo權限、以提供對多個路徑的存取權。

*您需要的是什麼*

* Sudo 1.8.7版或更新版本。
* 編輯_/etc/ssh / sshd_config_檔案、以設定訊息驗證代碼演算法：Macs HMAC - SHA2-256和MAC HMAC - SHA2-512。
+
更新組態檔後、重新啟動sshd服務。

+
範例：

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*關於此工作*

您應該為非root使用者設定Sudo權限、以便存取下列路徑：

* /home/_AIX_USER_/.SC_NetApp/snapcenter_AIX_host_plugin.bsx
* /custature_location / NetApp/snapcenter/spl/installal/plugins/uninstall
* /cust_LOUSE/NetApp/snapcenter/spl/bin/spl


*步驟*

. 登入您要在其中安裝SnapCenter 適用於AIX的整套件的AIX主機。
. 使用visudo Linux公用程式、將下列行新增至/etc/udoers檔案。
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+

NOTE: 如果您有RAC設定、以及其他允許的命令、您應該將下列項目新增至/etc/udoers檔案：「/setc/bin/olsnodes <crs_home> 」



您可以從/etc/oracle/OLR.loc_檔案取得_crs_home_的 值。

_AIX_USER_是您所建立的非root使用者名稱。

您可以從 *SC_UNIT_plugins_checksum ． txt* 檔案取得 _checksum 值 _ 、檔案位於：

* _C ： \ProgramData\NetApp\SnapCenter\Package 儲存庫 \SC_UNIX 外掛程式 _checksum ． txt_ （如果 SnapCenter 伺服器安裝在 Windows 主機上）。
* 如果 SnapCenter 伺服器安裝在 Linux 主機上、則為 /opt/NetApp/snapcenter/SnapManagerWeb/Repository /SC_UNIT_plugin_checksum ． txt_ 。



IMPORTANT: 此範例只能做為建立自己資料的參考。
