---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: 認證資料會根據應用程式或環境使用不同的驗證方法。認證資料會驗證使用者、讓他們能夠執行SnapCenter 功能不中斷的作業。您應該建立一組認證來安裝外掛程式、並建立另一組用於資料保護作業的認證。 
---
= SnapCenter 認證的驗證方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
認證會根據應用程式或環境使用不同的驗證方法。認證資料會驗證使用者、讓他們能夠執行SnapCenter 功能不中斷的作業。您應該建立一組認證來安裝外掛程式，另一組則用於資料保護作業。



== Windows驗證

Windows驗證方法會根據Active Directory進行驗證。對於Windows驗證、Active Directory是設定在SnapCenter 非功能性的環境中。無需額外組態即可驗證。SnapCenter您需要 Windows 認證來新增主機，安裝外掛程式套件，以及排程工作。



== 不受信任的網域驗證

SnapCenter 可讓不受信任網域的使用者和群組建立 Windows 認證。若要驗證成功、您應該使用SnapCenter NetApp註冊不受信任的網域。



== 本機工作群組驗證

支援與本機工作群組使用者和群組一起建立Windows認證。SnapCenter本機工作群組使用者和群組的 Windows 驗證不會在 Windows 認證建立期間發生，但會延遲到執行主機登錄和其他主機作業為止。



== SQL Server驗證

SQL驗證方法會針對SQL Server執行個體進行驗證。這表示SQL Server執行個體必須在SnapCenter 支援中發現。因此、在新增SQL認證之前、您必須先新增主機、安裝外掛程式套件、以及重新整理資源。您需要 SQL Server 驗證才能執行如 SQL Server 排程或探索資源等作業。



== Linux驗證

Linux驗證方法會針對Linux主機進行驗證。您需要在新增Linux主機並從SnapCenter 支援程式介面從遠端安裝適用於Linux的支援程式套件的初始步驟中進行Linux驗證SnapCenter 。



== AIX驗證

AIX驗證方法會針對AIX主機進行驗證。在新增AIX主機並從SnapCenter 支援程式GUI遠端安裝適用於AIX的支援程式套件的初始步驟中、您需要AIX驗證SnapCenter 。



== Oracle資料庫驗證

Oracle資料庫驗證方法會根據Oracle資料庫進行驗證。如果在資料庫主機上停用作業系統（OS）驗證、您需要Oracle資料庫驗證才能在Oracle資料庫上執行作業。因此，在新增 Oracle 資料庫認證之前，您應該在 Oracle 資料庫中使用 sysdba Privileges 建立 Oracle 使用者。



== Oracle ASM驗證

Oracle ASM驗證方法會針對Oracle自動儲存管理（ASM）執行個體進行驗證。如果您需要存取 Oracle ASM 執行個體，則需要 Oracle ASM 驗證，且資料庫主機上的 OS 驗證已停用。在新增 Oracle ASM 認證之前，請先在 ASM 執行個體中使用系統 Privileges 建立 Oracle 使用者。



== RMAN目錄驗證

RMAN目錄驗證方法會根據Oracle Recovery Manager（RMAN）目錄資料庫進行驗證。如果您已設定外部目錄機制並將資料庫登錄至目錄資料庫、則需要新增RMAN目錄驗證。
