---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: 在您使用SnapCenter 原地複製之前、先瞭解與您想要執行的備份、複製及還原作業相關的基本概念非常實用。 
---
= 資料保護的關鍵概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 SnapCenter 之前，請先瞭解備份，複製和還原的重要概念。



== 資源

資源包括資料庫， Windows 檔案系統，或是與 SnapCenter 備份或複製的檔案共用。視您的環境而定，資源也可能是資料庫執行個體， SQL Server 可用性群組， Oracle 資料庫， RAC 資料庫或自訂應用程式群組。



== 資源群組

資源群組是主機或叢集上的資源集合，可能來自多個主機和叢集。在資源群組上執行的作業會根據指定的排程套用至其所有資源。您可以針對個別資源或群組執行隨需或排程備份。


NOTE: 如果共享資源群組中的一部主機進入維護模式，則該群組的所有排程作業都會在所有主機上暫停。

使用相關外掛程式來備份特定資源：資料庫的資料庫外掛程式，檔案系統的檔案系統外掛程式，以及適用於 VM 和資料存放區的 SnapCenter Plug-in for VMware vSphere 。



== 原則

原則指定資料保護作業的備份頻率，複本保留，複寫，指令碼及其他特性。

建立資源群組或執行隨選備份時，可以選取一或多個原則。

資源群組會定義需要保護的內容，以及在日期和時間方面應保護的時間。原則說明如何執行保護。例如，如果需要備份主機的所有資料庫或檔案系統，則可能會建立一個資源群組，其中包括主機中的所有資料庫或檔案系統。然後可以將兩個原則附加到資源群組：每日原則和每小時原則。

建立資源群組並附加原則時，可以將其設定為每天執行完整備份，以及每小時執行另一個記錄備份排程。

自訂預先編寫和後置指令碼可用於資料保護作業。這些指令碼可在資料保護工作之前或之後自動執行。例如，指令碼可能會自動通知資料保護工作失敗或警告。在設定預先編寫和後置指令碼之前，瞭解建立這些指令碼的需求至關重要。



== 使用預先編寫和後置指令碼

自訂預先編寫和後置指令碼可在工作前後自動執行資料保護工作。例如，您可以新增指令碼來通知您工作失敗或警告。在設定指令碼之前，請先確定您瞭解這些指令碼的需求。



=== 支援的指令碼類型

Windows支援下列指令碼類型：

* 批次檔案
* PowerShell指令碼
* Perl指令碼


UNIX支援下列類型的指令碼：

* Perl指令碼
* Python指令碼
* Shell指令碼
+

NOTE: 除了預設的Bash Shell、也支援諸如sh-shell、k-shell和c-shell等其他Shell。





=== 指令碼路徑

在非虛擬化和虛擬化儲存系統上，所有作為 SnapCenter 作業一部分執行的預先編寫和後指令碼都會在外掛主機上執行。

* Windows指令碼應位於外掛程式主機上。



NOTE: 預先編寫或後製指令碼路徑不應包含磁碟機或共用區。路徑應相對於指令碼路徑。

* UNIX指令碼應位於外掛程式主機上。



NOTE: 指令碼路徑會在執行時驗證。



=== 指令碼的指定位置

指令碼是在備份原則中指定。當備份工作啟動時，原則會自動將指令碼與要備份的資源建立關聯。建立備份原則時、您可以指定pretced和postscript引數。


NOTE: 您無法指定多個指令碼。



=== 指令碼逾時

依預設、逾時設定為60秒。您可以修改逾時值。



=== 指令碼輸出

Windows預先編寫和後指令碼輸出檔案的預設目錄為Windows\System32。

UNIX規範和後置指令碼沒有預設位置。您可以將輸出檔案重新導向至任何偏好的位置。
