---
permalink: uninstall/task_uninstall_plug_ins_from_a_host_using_the_snapcenter_gui.html 
sidebar: sidebar 
keywords: uninstall, gui 
summary: 當您決定不再需要個別的外掛程式或外掛程式套件時、可以使用SnapCenter 這個介面將其解除安裝。 
---
= 使用SnapCenter 無法使用的GUI解除安裝外掛程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您決定不再需要個別的外掛程式或外掛程式套件時、可以使用SnapCenter 這個介面將其解除安裝。

.開始之前
* 您應該已經移除要解除安裝之外掛程式套件的資源群組。
* 您應該已針對要解除安裝的外掛程式套件、移除與資源群組相關的原則。


.關於這項工作
您可以解除安裝個別的外掛程式。例如、您可能需要解除安裝SnapCenter 適用於Microsoft SQL Server的不支援功能外掛程式、因為主機的資源不足、而且您想要將該外掛程式移到功能更強大的主機上。您也可以解除安裝整個外掛程式套件。例如、您可能需要解除安裝SnapCenter 適用於Linux的支援功能、其中包括SnapCenter 適用於Oracle資料庫的支援功能、SnapCenter 以及適用於UNIX的支援功能。

* 移除主機包括解除安裝所有外掛程式。
+
當您將主機從SnapCenter 支援環境中移除時、SnapCenter 在移除主機之前、將會先在主機上解除安裝所有外掛程式套件。

* 支援使用者介面可一次從一部主機移除外掛程式。SnapCenter
+
當您使用SnapCenter Suse GUI時、一次只能在一部主機上解除安裝外掛程式。不過、您可以同時執行數個解除安裝作業。

+
您也可以使用_uninstall-SmHostPackage_ Cmdlet和必要的參數、從多個主機解除安裝外掛程式。您可以執行_Get-Help命令name_來取得可搭配Cmdlet使用之參數及其說明的相關資訊。或者、您也可以參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205["《軟件指令程式參考指南》SnapCenter"^]。




IMPORTANT: 從SnapCenter 安裝了此功能的主機上解除安裝適用於Windows的功能更新套件SnapCenter 、將會損壞SnapCenter 安裝此功能的支援服務器。除非SnapCenter 您確定不再需要SnapCenter 使用此伺服器、否則請勿解除安裝適用於Windows的功能強大的功能。

.步驟
. 在左側導覽窗格中、按一下*主機*。
. 在「主機」頁面中、按一下「*託管主機*」。
. 在「受管理的主機」頁面中、選取您要從中解除安裝外掛程式或外掛程式套件的主機。
. 在您要移除的外掛程式旁邊、按一下「*移除*」>「*提交*」。


.完成後
您應等待5分鐘、然後再重新安裝該主機上的外掛程式。這段時間足以讓SnapCenter 整套圖形使用者介面重新整理託管主機的狀態。如果您立即重新安裝外掛程式、安裝將會失敗。

如果您要解除安裝SnapCenter 適用於Linux的效能分析外掛程式套件、請至：_/custom位置/snapcenter/log_取得解除安裝特定的記錄檔。
