---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: SnapCenter 軟體 6.0 版包含數項新功能與增強功能。 
---
= SnapCenter 軟體 6.0 的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 軟體 6.0 版包含數項新功能與增強功能。

|===
| 更新 | 說明 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["支援 NetApp 的企業工作負載外掛程式"]  a| 
SnapCenter 提供外掛程式來管理 PostgreSQL ， MySQL 和 IBM DB2 等工作負載。您可以自動探索，備份，還原，裝載及複製工作負載。

SnapCenter 也提供外掛程式來管理工作負載，例如 SAP ASE ， SAP MaxDB ， MongoDB ， Oracle 應用程式和 ONTAP 儲存設備。您可以備份，還原及複製工作負載。



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["支援 Linux 版本的 SnapCenter ，同時適用於雲端和內部部署工作負載"]  a| 
現在， Red Hat Enterprise Linux （ RHEL ）， Oracle Linux 和 SUSE Linux Enterprise Server （ SLES ）等 Linux 版本均可使用獨立的 SnapCenter 二進位檔。

* 支援 Azure NetApp Files ， Amazon FSX for NetApp ONTAP ， Cloud Volumes ONTAP 和 ONTAP 儲存設備。
* Linux 版本的獨立二進位檔，例如 Red Hat Enterprise Linux （ RHEL ）， Oracle Linux 和 SUSE Linux Enterprise Server （ SLES ）。
* 支援 SAP HANA ， Oracle ， IBM DB2 ， SAP ASE ， SAP MaxDB 等傳統資料庫。
* 支援 PostgreSQL ， MySQL 和 MongoDB 等現代化工作負載。
* 支援 ONTAP Volume 和 Linux 檔案系統的外掛程式，以保護任何不受支援或自行開發的應用程式。




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["支援 SnapMirror 主動式同步"]  a| 
您現在可以使用 SnapCenter 來設定 SnapMirror 主動式同步功能，並有效備份，還原及複製資料庫和 VMware VM 的 SAN 工作負載。如此可確保透明化的應用程式容錯移轉和營運持續性。



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["支援 SMB3 上的 Microsoft SQL Server"]  a| 
您現在可以使用 SnapCenter 來保護部署在 ONTAP ， Azure NetApp Files ， Amazon FSX for NetApp ONTAP 和 Cloud Volumes ONTAP 中 SMB3 傳輸協定上的 Microsoft SQL Server 資料庫。



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["支援 NVMe / TCP"]  a| 
SnapCenter 現在支援 NVMe over TCP 傳輸協定，可備份及恢復應用程式和檔案系統。



| 支援 VMware vSphere 虛擬磁碟區（ VVols ）  a| 
您現在可以使用 SnapCenter 來保護部署在 vVols 上的資料庫和檔案系統。

|===